'files': [
  {
    'source': '/src/locales/en/v2/**/*',
    'translation': '/src/locales/%two_letters_code%/v2/**/%original_file_name%',
    'excluded_target_languages': ['ar', 'es-ES', 'fr', 'he', 'iu', 'oj']
  },
  {
    'source': '/src/locales/en/v1/**/every',
    'translation': '/src/locales/%two_letters_code%/v1/**/%original_file_name%',
    'excluded_target_languages': [ 'ar', 'es-ES', 'fr', 'he', 'iu', 'oj' ]
  },
  {
    'source': '/src/locales/en/v1/**/the-earSketch-api*',
    'translation': '/src/locales/%two_letters_code%/v1/**/%original_file_name%',
    'excluded_target_languages': [ 'ar', 'es-ES', 'fr', 'he', 'iu', 'oj' ]
  },
  {
    'source': '/src/locales/en/v1/**/ch_Hour*',
    'translation': '/src/locales/%two_letters_code%/v1/**/%original_file_name%',
    'excluded_target_languages': [ 'ar', 'es-ES', 'fr', 'he', 'iu', 'oj' ]
  }
]
