[[mixingwithconditionnals]]
== Shartlar bilan Mix Qilamiz!

:nofooter:

Dasturlashda siz xar xil narsalarni va jarayonlarni avtomatlashtirishingiz mumkin. Siz robotni to'siq aniqlanganda to'xtab qoladigan tarzda dasturlashtirishingiz avtomatlashtirishga misol bo'ladi. Ushbu stsenariyda robotga to'xtashni aytish uchun inson kerak bo'lmaydi. Buning o'rniga robotda to'siqlarni aniqlaydigan sensor bo'ladi va agar to'siq mavjud bo'lsa, u to'xtaydi. Biz EarSketch-da shartlar (`if` bayonotlari) yordamida musiqiy avtomatlashtirishni amalga oshirishimiz mumkin. Biz treklarni miks qilish qanday avtomatlashtirishini ko'rib chiqamiz. Miks qilish bu shuni bildiradi: agar trek juda baland bo'lsa, biz uning ovoz balandligini pasaytiramiz va juda past bo'lsa, biz uning ovoz balandligini oshiramiz.

[[analyzetrack]]
=== `analyzeTrack()`dan foydalaning

Biz trekning ovoz balandligi yoki tovushini qanday aniqlashni ko'rib chiqamiz. Tovush pardasi (yuqori yoki past) va ovoz balandligi (baland yoki sokin) o'rtasidagi farqni tushunganingizga ishonch hosil qiling. Biz `analyzeTrack()` deb nomlangan EarSketch funktsiyasidan foydalanamiz. Quyidagi kodni nusxalang va ishga tushiring:

[role="curriculum-python"]
[source,python]
----
include::code-examples/mixing-with-conditionals-analyzetrack.py.txt[]
----

[role="curriculum-javascript"]
[source,javascript]
----
include::code-examples/mixing-with-conditionals-analyzetrack.js.txt[]
----

Konsolingizda chop etilgan ovoz balandligi 0,10306035109110138 ekanligini o'qishingiz mumkin.

* Ovoz balandligi 0 dan (sukunat) 1 gacha (maksimal ovoz balandligi) bo'lishi mumkin.
* Ba'zan siz shunga o'xshash raqamni ko'rasiz: 1.74630733714e-05. Bunga ilmiy belgilash deyiladi: oxiridagi e-05 ni ko'ryapsizmi? Bu o'nli kasrni 5 taga chapga ko'chirishni anglatadi (kerak bo'lsa 0 bilan almashtiring). Bu 0.0000174630733714 ga teng.
* Aksariyat tovushlarning balandligi 0.4 dan past bo'ladi

`analyzeTrack()` funktsiyasi 2 ta argumentni oladi:

. *track*: Trek raqami
. *feature*: Analiz konstantasi, masalan `RMS_AMPLITUDE`

.AMALIYOT
****
. Chiqishda nimani yangrashini ko'rish uchun yuqorida berilgan kodni turli tovushlar bilan ishlatib ko'ring (`sound` o'zgaruvchisini o'zgartiring).
. Ikkinchi trekni qo'shing va uning ovoz balandligini konsolda chop etish uchun `analyzeTrack()` funktsiyasidan foydalaning. Kodni ishga tushirganingizda, konsolingizga qarashdan avval musiqangizni tinglang va qaysi trek balandroq ekanligini taxmin qilishga harakat qiling.
****

`analyzeTrack()` parametri ovoz balandligini baholash uchun `RMS_AMPLITUDE` yoki tovush yorqinligini tahlil qilish uchun `SPECTRAL_CENTROID` boʻlishi mumkin. Biz ushbu bobda ovoz balandligini tahlil qilishga e'tibor qaratamiz.

[[booleansandcomparisons]]
=== Mantiqiy qiymatlar va taqqoslashlar

Endi biz *Boolean mantig'i*ning qanday ishlashini ko'rib chiqamiz. Bu bizga ba'zi vazifalarni avtomatlashtirishga yordam beradi.

[role="curriculum-python"]
*Mantiqiy qiymatlar* ma'lumotlar turidir. Boolean ma'lumotlar turi faqat ikkita mumkin bo'lgan qiymatga ega, `True` va `False`. `True` va `False` soʻzlari bosh harf bilan boshlanadi va qo'shtirnoqsiz yoziladi.

[role="curriculum-javascript"]
*Mantiqiy qiymatlar* ma'lumotlar turidir. Boolean ma'lumotlar turi faqat ikkita mumkin bo'lgan qiymatga ega, `true` va `false`. `true` va `false` kichik harf bilan boshlanadi va qo'shtirnoqsiz yoziladi.

[role="curriculum-python"]
--
Mantiqiy qiymat yaratish uchun siz o‘zgaruvchini ishga tushirishingiz mumkin (`var variable1 = True;`) yoki taqqoslashdan foydalanishingiz mumkin. Taqqoslash uchun biz *taqqoslash operatoridan* foydalanamiz. Quyida taqqoslash operatorlari:

[cols="^h,1"]
|===
|==
|... ga teng

|!=
|... ga teng emas

|>
|...dan kattaroq

|>=
|...dan kattaroq yoki barobar

|<
|...dan kam

|\<=
|...dan kichik yoki teng
|===

Bular o'rtasidagi farqqa e'tibor bering:

1. Ikki qiymatni taqqoslash, ularning bir xilligini aniqlash uchun: `==`
1. O'zgaruvchiga qiymat tayinlash: `=`
--

[role="curriculum-javascript"]
--
Mantiqiy qiymat yaratish uchun siz o‘zgaruvchini ishga tushirishingiz mumkin (`var variable1 = true;`) yoki taqqoslashdan foydalanishingiz mumkin. Taqqoslash uchun biz *taqqoslash operatoridan* foydalanamiz. Quyida taqqoslash operatorlari:

[cols="^h,1"]
|===
|===
|... ga teng

|!==
|... ga teng emas

|>
|...dan kattaroq

|>=
|...dan kattaroq yoki barobar

|<
|...dan kam

|\<=
|...dan kichik yoki teng
|===

Bular o'rtasidagi farqqa e'tibor bering:

1. Ikki qiymatni taqqoslash, ularning bir xilligini aniqlash uchun: `===`
1. O'zgaruvchiga qiymat tayinlash: `=`
--

[role="curriculum-python curriculum-mp4"]
[[video17apy]]
video::./videoMedia/6_2_1_boolean_py.mp4[]

[role="curriculum-javascript curriculum-mp4"]
[[video17ajs]]
video::./videoMedia/6_2_1_boolean_js.mp4[]

// this video will be cut at 2' to delete the section about boolean operators//

[role="curriculum-python"]
.AMALIYOT
****
* Yangi skript yarating va 2 trekka tovush qo'shing.
* Agar birinchi trek ikkinchi trekdan balandroq bo'lsa, `Rost`, aks holda `Yolg'on` deb chop eting.
* Har bir trek uchun ovoz balandligi 0,01 dan aniq katta ekanligini tekshirish uchun `trek` hisoblagichi bilan for halqasidan foydalaning. Agar shunday bo'lsa, `Rost`ni, bo'lmasa, `Yolg'on`ni chop eting.
* Siz `True` yoki `False`ni chop etishdan oldin qo‘shimcha chop etish bayonotlaridan foydalanishingiz mumkin, shunda konsolni o‘qiganingizda nima `Rost` yoki `Yolg'on` ekanligini bilib olasiz. Masalan, avval trek raqamini, so'ngra 'Rost' yoki 'Yolg'on'ni chop etishingiz mumkin.
****

[role="curriculum-javascript"]
.AMALIYOT
****
* Yangi skript yarating va 2 trekka tovush qo'shing.
* Agar birinchi trek ikkinchi trekdan balandroq bo'lsa, `rost`, aks holda `yolg'on` deb chop eting.
* Har bir trek uchun ovoz balandligi 0,01 dan aniq katta ekanligini tekshirish uchun `trek` hisoblagichi bilan for halqasidan foydalaning. Agar shunday bo'lsa, `rost`ni, bo'lmasa, `yolg'on`ni chop eting.
* Siz `true` yoki `false`ni chop etishdan oldin qo‘shimcha chop etish bayonotlaridan foydalanishingiz mumkin, shunda konsolni o‘qiganingizda nima `rost` yoki `yolg'on` ekanligini bilib olasiz. Masalan, avval trek raqamini, so'ngra 'rost' yoki 'yolg'on'ni chop etishingiz mumkin.
****

Mana bir misol:

[role="curriculum-python"]
[source,python]
----
include::code-examples/mixing-with-conditionals-boolean-example.py.txt[]
----

[role="curriculum-javascript"]
[source,javascript]
----
include::code-examples/mixing-with-conditionals-boolean-example.js.txt[]
----

[role="curriculum-python"]
Bu misolda biz konsoldagi ma'lumotni o'qiy olishimiz uchun `print()` va satrlardan foydalandik.  Biz `+` operatoridan *yopishtirish* yoki satrlarni qoʻshish uchun, str() funktsiyasidan esa raqamlarni satrlarga aylantirish uchun foydalandik.

[role="curriculum-javascript"]
Bu misolda biz konsoldagi ma'lumotni o'qiy olishimiz uchun `print()` va satrlardan foydalandik. Biz `+` operatoridan *yopishtirish* yoki satrlarni qoʻshish uchun foydalandik.

[[conditionalstatements]]
=== Shartli Bayonotlar

Shartli Bayonot nima? *Bayonot* - bu kompyuter uchun ko'rsatma. *Shartli bayonot* - bu ma'lum bir *shart* rost bo'lgandagina bajarilishi kerak bo'lgan ko'rsatma. Misol uchun, agar siz robotni to'siq oldida to'xtash uchun dasturlashtirsangiz, shart "to'siq bormi?" bo'ladi. Ha bo'lsa, to'xtating. Agar yo'q bo'lsa, hech narsa qilmang (davom eting).

Quyida shartli bayonotning namunasi keltirilgan, for halqasi bilan o'xshashligiga e'tibor bering:

[role="curriculum-python"]
[source,python]
----
include::code-examples/mixing-with-conditionals-untitled1.py.txt[]
----

[role="curriculum-javascript"]
[source,javascript]
----
include::code-examples/mixing-with-conditionals-untitled1.js.txt[]
----

.AMALIYOT
****
* 2 trekdan iborat yangi skript yarating.
* Agar birinchi trekning ovozi ikkinchisidan balandroq bo'lsa, uning ovozini pasaytiring. Sizga `analyzeTrack()` va `setEffect()` funktsiyalari hamda `if` bayonoti kerak bo`ladi.
* Ovozni pasaytirish uchun sizga salbiy o'sish (-1dB va -60dB oralig'ida) kerak bo'ladi.
****

Mana bir misol:

[role="curriculum-python"]
[source,python]
----
include::code-examples/mixing-with-conditionals-automatic-mixing-1.py.txt[]
----

[role="curriculum-javascript"]
[source,javascript]
----
include::code-examples/mixing-with-conditionals-automatic-mixing-1.js.txt[]
----

We might want to check several conditions and execute a different set of statements depending on each condition. You can chain multiple conditions together. We use the following syntax:

[role="curriculum-python"]
[source,python]
----
include::code-examples/mixing-with-conditionals-untitled2.py.txt[]
----

[role="curriculum-javascript"]
[source,javascript]
----
include::code-examples/mixing-with-conditionals-untitled2.js.txt[]
----

[[mixingyourtracks]]
=== Mix your tracks

Keling, qo'shiqni miks qilish uchun ushbu barcha vositalardan foydalanaylik. Mixing is modifying the volume of tracks so that they sound well balanced together.

[role="curriculum-python"]
.AMALIYOT
****
* Create a new script.
* Add sounds on at least three tracks for at least sixteen measures.
* You can use the `makeBeat()` function and a `for` loop to add percussion.
* Choose your "main" track. It can be your melody, or one track that you wish to highlight.
* Agar sizning asosiy trekingiz boshqa treklardan balandroq bo'lmasa, `setEffect()` funktsiyasidan foydalanib uning ovoz balandligini oshirganingizga ishonch hosil qiling. Don't take the percussive track into account, as `analyzeTrack()` is not relevant for percussion. `analyzeTrack()` returns a mean whereas percussion are bursts of sound, so a mean doesn't really evaluate the loudness.
* Use `print()` to show your process in the console. Here is an example: `print("Is track number" + str(track) + "greater than 0.01?")`, if the counter `track` is equal to `1`, this will print "Is track number 1 greater than 0.01?". The function `str()` converts a number (ex: `1`) into a string (ex: `"1"`).
****

[role="curriculum-javascript"]
.AMALIYOT
****
* Create a new script.
* Add sounds on at least three tracks for at least sixteen measures.
* You can use the `makeBeat()` function and a `for` loop to add percussion.
* Choose your "main" track. It can be your melody, or the track that you wish to highlight.
* Agar sizning asosiy trekingiz boshqa treklardan balandroq bo'lmasa, `setEffect()` funktsiyasidan foydalanib uning ovoz balandligini oshirganingizga ishonch hosil qiling. Don't take the percussive track into account, as `analyzeTrack()` is not relevant for percussion. `analyzeTrack()` returns a mean whereas percussion are bursts of sound, so a mean doesn't really evaluate the loudness.
* Use `println()` to show your process in the console. Here is an example: `println("Is track number" + track + "greater than 0.01?")`, if the counter `track` is equal to `1`, this will print "Is track number 1 greater than 0.01?".
****

Keling, ba'zi lug'atlarni ko'rib chiqaylik:

1. *Operator*: harakatni ifodalovchi belgi. We have seen arithmetic operators (`\+`, `-`, `\*`, `=`) and comparison operators (`>`, `>=`, `<`, `\<=`, `===`, `!==`).
1. *Ifoda*: qiymatlar, konstantalar, o‘zgaruvchilar, operatorlar va funktsiyalar birikmasi. The computer evaluates expressions to produce a result, usually a single numeric or boolean value.  For example: `1 + 2` (evaluated to 3) or `1 < 2` (evaluated to True) or `analyzeTrack(1, RMS_AMPLITUDE)` (evaluated to the loudness of track `1`, a float between 0 and 1).
1. *Bayonotllar* - bu kompyuter bajarishi uchun ko'rsatma.

Below is an example of automated mixing. Agar siz bir yoki bir nechta tovushni o'zgartirsangiz, ularning ovoz balandligini tekshirishingiz va o'zingiz o'zgartirishingiz shart emas, chunki u allaqachon kodga kiritilgan. Shuning uchun biz buni avtomatlashtirilgan deb aytishimiz mumkin.

[role="curriculum-python"]
[source,python]
----
include::code-examples/mixing-with-conditionals-automatic-mixing-2.py.txt[]
----

[role="curriculum-javascript"]
[source,javascript]
----
include::code-examples/mixing-with-conditionals-automatic-mixing-2.js.txt[]
----

{nbsp} +

[[chapter6summary]]
=== Chapter 6 Summary

[role="curriculum-python"]
* The `analyzeTrack()` function takes two arguments: the track and feature. When the feature is `RMS_AMPLITUDE`, the function will return the loudness of the track (a number between 0 and 1). When the feature is `SPECTRAL_CENTROID`, the function will return the brightness of the track.
* *Boolean* maʼlumotlar turi faqat ikkita mumkin boʻlgan qiymatga ega, `True` va `False`.
* Mantiqiy qiymatlar ushbu taqqoslash operatorlari tomonidan hosil qilinadi: `==`, `!=`, `>`, `>=`, `<`, `\<=`.
* `==` 2 ta qiymat tengligini baholaydi, `=` esa o`zgaruvchiga qiymat tayinlaydi.
* *Operator*: harakatni ifodalovchi belgi.
* *Ifodalar* qiymat ishlab chiqarish uchun kompyuter tomonidan baholanadi.
* *Bayonot* - bu kompyuter uchun ko'rsatma.
* *Shart* `Rost` yoki `Yolg'on` deb baholanadigan iboradir.
* The `if` statement only executes its code block when its condition is `True`.
* In the event that an `if` statement's condition is `False`, an optional `else` statement allows an alternative code block to be executed.

[role="curriculum-javascript"]
* The `analyzeTrack()` function takes two arguments: the track and feature. When the feature is `RMS_AMPLITUDE`, the function will return the loudness of the track (a number between 0 and 1). When the feature is `SPECTRAL_CENTROID`, the function will return the brightness of the track.
* *Boolean* maʼlumotlar turi faqat ikkita mumkin boʻlgan qiymatga ega, `true` va `false`.
* Boolean values are generated by comparison operators: `===`, `!==`, `>`, `>=`, `<`, `\<=`.
* `===` evaluates if 2 values are equal, whereas `=` assigns a value to a variable.
* *Operator*: harakatni ifodalovchi belgi.
* *Ifodalar* qiymat ishlab chiqarish uchun kompyuter tomonidan baholanadi.
* *Bayonot* - bu kompyuter uchun ko'rsatma.
* *Shart* `rost` yoki `yolg'on` deb baholanadigan iboradir.
* The `if` statement only executes its code block when its condition is `true`.
* In the event that an `if` statement's condition is `false`, an optional `else` statement allows an alternative code block to be executed.

[[chapter-questions]]
=== Questions

[question]
--
Which of the following elements is a boolean?

[answers]
* `5+4 === 5`
* `o'lchov = 1`
* `2<3<4`
* `False()`
--

[role="curriculum-python"]
[question]
--
What would the output of this block of code be (what would print to the console)?

[source,python]
----
include::code-examples/mixing-with-conditionals-untitled3.py.txt[]
----

[answers]
* 10
* 5
* True
* False
--

[role="curriculum-javascript"]
[question]
--
What would the output of this block of code be (what would print to the console)?

[source,javascript]
----
include::code-examples/mixing-with-conditionals-untitled3.js.txt[]
----

[answers]
* 10
* 5
* True
* False
--

[question]
--
What is mixing?

[answers]
* adapting the volume of each track so they sound well balanced
* adapting the pitch of each track so they sound well balanced
* adding a fade in
* adding a fade out
--

[question]
--
How many conditions can you check in a conditional statement?

[answers]
* any number of conditions
* 1 condition
* 2 conditions
* 3 conditions
--