[[welcome]]
== Welcome Students and Teachers!

:nofooter:

Welcome to EarSketch!

*O‘qituvchilar*: https://earsketch.gatech.edu/teachermaterials/EarSketch_Alignment_Guide.pdf[yangi o‘quv dasturi bo‘yicha qo‘llanma^] bilan tanishing va qo‘shimcha ma’lumot uchun https://www.teachers.earsketch.org[EarSketch O'qituvchi Saytiga^] tashrif buyuring.

*Talabalar*: EarSketch haqida batafsil ma'lumot olish uchun quyida davom eting

Here you will learn computer science and music technology side by side. You will use either Python or JavaScript to create your own music.

Musicians and programmers write computer code to create new sounds, effects, and songs.

[role="curriculum-mp4"]
[[video0]]
video::../landing/media/homepagevid.a1cf3d01.mp4[poster=../landing/img/homepagevid-poster.8993a985.png]

Learning to write computer code is a skill that will be useful to you in a variety of career paths.

Balki siz afsonaviy musiqa prodyuseri yoki sanoatning eng talabgor ovoz yozish muhandisi bo'lasiz! We wish you good luck on your EarSketch journey.

Click on the right arrow at the top of this text to get started.

Oʻqituvchilar, bepul oʻqituvchi materiallari va hamjamiyatiga kirish uchun https://www.teachers.earsketch.org/[bu yerga^] bosing!