[[customizeyourfirstsong]]
== Birinchi qo'shig'ingizni sozlang
:nofooter:

Ushbu bo'limda siz qo'shig'ingizning tempini qanday o'zgartirishni, kodingizga sharhlar qo'shishni va qo'shiq xabarini kuchaytirish uchun o'z tovushlaringizni yuklashni o'rganasiz.

[[settempo]]
=== `setTempo()` funktsiyasi

[role="curriculum-python"]
--
Hozirga kelib, siz yangi skript yaratishda kodingiz ishlashi uchun mutlaqo saqlashingiz kerak bo'lgan avvaldan mavjud elementlar borligini payqadingiz:

. Kulrang rangda `#` bilan boshlanadigan ba'zi sharhlar: biz buni keyingi bo'limda ko'rib chiqamiz
. loyihaga EarSketch funktsiyalarini (masalan, `fitMedia()`) qo‘shadigan `from earsketch import*` qatori 
. `init()` funktsiyasi RAISni ishga tushiradi yoki yoqadi
. `setTempo(120)` funktsiyasi, biz uni quyida batafsil ko'rib chiqamiz
. `finish()` funktsiyasi: RAISga siz yozishni tugatganingiz va musiqangizni ijro etishga tayyor ekanligingizni bildiradi.
--

[role="curriculum-javascript"]
--
Hozirga kelib, siz yangi skript yaratishda kodingiz ishlashi uchun mutlaqo saqlashingiz kerak bo'lgan avvaldan mavjud elementlar borligini payqadingiz:

. Kulrang rangda `//` bilan boshlanadigan ba'zi sharhlar: biz buni keyingi bo'limda ko'rib chiqamiz
. `init()` funktsiyasi RAISni ishga tushiradi yoki yoqadi
. `setTempo(120)` funktsiyasi, biz uni quyida batafsil ko'rib chiqamiz
. `finish()` funktsiyasi: RAISga siz yozishni tugatganingiz va musiqangizni ijro etishga tayyor ekanligingizni bildiradi.
--

Eslatma: Sizning kodingiz `setTempo()` dan keyin va `finish()` dan oldin keladi.

`setTempo()` funktsiyasi qo'shig'ingiz tezligini belgilaydi. G'arb musiqasida *Temp* - bu daqiqada zarbalar miqdori (dzm) sanaladi. EarSketch-da standart temp (ya'ni tempning boshlang'ich qiymati) 120dzm ga o'rnatiladi, bu tez yurish yoki marsh tezligiga mos keladi. Tempni oʻzgartirish uchun `setTempo()` funktsiyasida qavslar orasidagi raqamni oʻzgartirish kifoya. Temp qanchalik baland bo'lsa, musiqangiz shunchalik tezlashadi. Siz tempni _45dzm va 220dzm_ oraligʻida tanlashingiz mumkin.

.AMALIYOT
****
. Yangi skript yarating. 
. Tovushlarni 2 farqli trekka joylashtiring.
. Tempni o'zgartiring va qo'shiqni tinglang.
. Do'stingiz uchun qo'shiqni 3 farqli tempda ijro eting. So'ng undan eng sekindan eng tez tempga qarab daraja berishini so'rang.
****

Janr - bu shakl, uslub yoki mavzu bo'yicha o'xshashlik bilan tavsiflangan badiiy kompozitsiyaning (masalan, musiqa) toifasi. Turli janrlar turli xil temp diapazonlariga ega. Masalan:

[cols="^3*"]
|===
|JANR|DZM|MISOL

|Hip Hop
|85-95
|Coolio - Gangsta's Paradise (feat. L.V.)
|Pop
|110-130
|Lizzo - Juice 
|Texno
|120-125
|Boris Brejcha - Schleierwolken
|Elektro
|100-130
|Apashe - Behind My Eyes (feat. LIA)
|Haus
|115-130
|DJ Breezy - Kimpinstik (feat. Dahlin Gage & Medikal)
|Dabstep va Tuzoq
|140-150
|Jessica Audiffred & Walshy Fire - Stupid Love (feat. Nia V)
|Drum & Bass
|160-180
|Mollie Collins - Lost & Found
|===

.AMALIYOT
****
. O'zingizga yoqqan ijrochilardan birini tanlang va ular qaysi janrga tegishli ekanligini bilib oling.
. Ushbu janrni qidiring (https://soundcloud.com/[Soundcloud] yoki shunga o'xshash) va shu janrdagi qo'shiqlardan bir nechta parchalarni tinglang.
. Qo'shiqlar orasidagi o'xshashlikni tinglang.
. Shuningdek, janr haqida ko'proq ma'lumot olish uchun Vikipediyani tadqiq qilishingiz mumkin.
****
 
E'tibor bering, ba'zida bitta ovozli klip uni oldindan tinglaganingizda va qo'shig'ingiz ichida ijro etilganda juda farqli yangraydi. Bunga sabab, ovozli klipning tempi qo'shig'ingiz tempidan farqli bo'lishi mumkin. Namunaning aniq tempini bilish uchun Sound Brauzerda klip nomi ustiga kursorni olib boring. Keyin qo'shig'ingiz tempini mos ravishda o'zgartirishingiz yoki qo'shig'ingiz tempiga yaxshiroq mos keladigan ovozli klipni tanlashingiz mumkin.


[[comments]]
=== Kodingizga sharhlar qo'shing

[role="curriculum-python"]
*Sharhlar* - bu kompyuter tomonidan bajarilmaydigan kod qatorlari. Ular faqat odamlar tomonidan kodni tushunishni osonlashtirish, kodni tartibga solish yoki kelajakda foydalanish uchun eslatmalar qoldirishga ishlatiladi. Python-da sharhlar funt belgisi `#` bilan boshlanadigan qator bilan ko'rsatiladi. 

[role="curriculum-javascript"]
*Sharhlar* - bu kompyuter tomonidan bajarilmaydigan kod qatorlari. Ular faqat odamlar tomonidan kodni tushunishni osonlashtirish, kodni tartibga solish yoki kelajakda foydalanish uchun eslatmalar qoldirishga ishlatiladi. Python-da sharhlar ikki yotiq chiziq belgisi `//` bilan boshlanadigan qator bilan ko'rsatiladi.

E'tibor bering, har bir skriptning birinchi satrlari skriptingizni izohlovchi sharhlardir. Har bir yangi skript uchun siz ushbu ma'lumotni to'ldirishingiz kerak bo'ladi. Bu boshqa dasturchilarga kodingiz nima haqida ekanligini tushunishni osonlashtiradi.

.AMALIYOT
****
Joriy skriptingizda kodingiz boshidagi izohlarda quyidagi ma'lumotlarni to'ldiring:

. skript nomi: qo'shiпg'ingiz nomi,
. muallif: ismingiz,
. izoh: bu yerda loyihangizningning qisqacha tavsifini yozing
****

Kodingizning turli bo'limlari nima ish bajarishini ta'riflash uchun sharhlardan ham foydalanishingiz mumkin. Quyida misol keltiramiz. Siz kodni joylashtirishingiz va ishga tushirishingiz mumkin. Sharhlar turli bo'limlarni qanday ta'riflashiga e'tibor bering:

[role="curriculum-python"]
[source,python]
----
# python kodi
#
# skript_nomi: Sharhlash Bo'limlari
#
# muallif: EarSketch Jamoasi
#
# izoh: Bu kod nima ish bajarishini ta'riflash uchun sharhlardan foydalanadigan skriptning qisqacha namunasi
#
#
#

#Sozlash
from earsketch import *
init()
setTempo(130)

#Musiqa
#Yetakchilar
fitMedia(RD_EDM_ANALOGPLUCK_1, 1, 1, 9)
fitMedia(RD_TRAP_ARPBLEEPLEAD_5, 2, 1, 5)
fitMedia(RD_TRAP_ARPBLEEPLEAD_3, 2, 5, 9)

#Zarba
fitMedia(HOUSE_BREAKBEAT_023, 3, 1, 9)
fitMedia(HOUSE_BREAKBEAT_006, 4, 1, 3)
fitMedia(HOUSE_BREAKBEAT_012, 4, 3, 5)
fitMedia(HOUSE_BREAKBEAT_012, 4, 7, 9)

#Bas va shovqin
fitMedia(ELECTRO_ANALOGUE_BASS_008, 5, 1, 9)
fitMedia(TECHNO_WHITENOISESFX_001, 6, 7, 9)

#Yakunlash
finish()
----

[role="curriculum-javascript"]
[source,javascript]
----
// javascript kodi
//
// skript_nomi: Sharhlash Bo'limlari
//
// muallif: EarSketch Jamoasi
//
// tavsifi: Bu kod nima ish bajarishini ta'riflash uchun sharhlardan foydalanadigan skriptning qisqacha namunasi
//
//

//Sozlash
init();
setTempo(130);

//Musiqa
//Yetakchilar
fitMedia(RD_EDM_ANALOGPLUCK_1, 1, 1, 9);
fitMedia(RD_TRAP_ARPBLEEPLEAD_5, 2, 1, 5);
fitMedia(RD_TRAP_ARPBLEEPLEAD_3, 2, 5, 9);

//Zarba
fitMedia(HOUSE_BREAKBEAT_023, 3, 1, 9);
fitMedia(HOUSE_BREAKBEAT_006, 4, 1, 3);
fitMedia(HOUSE_BREAKBEAT_012, 4, 3, 5);
fitMedia(HOUSE_BREAKBEAT_012, 4, 7, 9);

//Bas va shovqin
fitMedia (ELECTRO_ANALOGUE_BASS_008, 5, 1, 9);
fitMedia (TECHNO_WHITENOISESFX_001, 6, 7, 9);

//Yakunlash
finish();
----

{nbsp} +

[[uploadingsounds]]
=== Shaxsiy tovushlaringizni yuklang

_Kontent Menejeri_ orqali shaxsiy audioingizni yuklashingiz mumkin. Ekraningizning chap tomonida _Kontent Menejerini_ oching. Tovush qo'shish oynasini ochish uchun "Tovushlar" yorlig'i ostidagi filtrlardan pastroqda "Tovush qo'shish" tugmasini bosing (agar tugma ko'rinmasa, tizimga kirganingizga ishonch hosil qiling). Keling, birinchi 3 ta variantni ko'rib chiqaylik:

. *Tovushni Yuklash* kompyuteringizda avvaldan mavjud bo'lgan audio fayllarni (.mp3, .aiff va hokazo) tanlash imkonini beradi. Ehtiyoj bo'lsa, fayl nomini o'zgartiring ("doimiy qiymat(talab etilgan)") va "YUKLASH" tugmasini bosing.
. *Tezkor yozib olish* qisqa kliplarni bevosita EarSketch kutubxonasiga yozib olish imkonini beradi. Qo'shimcha ma'lumot olish uchun quyidagi videoni ko'ring.
. *Freesound* ochiq manbali audio ma'lumotlar bazasi bo'lgan Freesound.org dan tovushlarni bevosita import qilish imkonini beradi. Qidiruv satrida siz tovush turini qidirishingiz mumkin (masalan: qushlarning qo'shiqlari, yomg'ir, gavjum ko'cha ...). "Natijalar" ostida tovushlar ro'yxati paydo bo'ladi. Ijro tugmasini bosish orqali tovushlarni oldindan ko'rishingiz mumkin, agar u sizga yoqsa, fayl nomi oldidagi o'zgartirish tugmachasini tanlang, so'ng eng pastki qismidagi "YUKLASH" tugmasini bosing.

Siz hozirgina yuklagan yoki yozib olgan tovushni topish uchun Kontent Menejerining Ovoz yorlig'i ostidagi qidirish satriga uning nomini kiriting.

[role="curriculum-mp4"]
[[video101rec]]
video::./videoMedia/010-01-Recording&UploadingSounds-PY-JS.mp4[]

.AMALIYOT
****
Musiqa va umuman san'at ko'pincha xabarni yetkazishning bir usuli hisoblanadi. Bu qo'shiq matni va/yoki qo'shiqning kayfiyati orqali bo'lishi mumkin. Sizdan nimanidir ifodalovchi qisqa qo'shiq yaratishingizni xohlaymiz. Bu siz baham ko'rmoqchi bo'lgan tuyg'u yoki hikoya bo'lishi mumkin.

. Ifodalashni xohlayotgan narsangizni tasavvur qiling
. Keyin yoki:
.. She'r yozing va uni qo'shiq qilib aytayotganingizni yoki uni o'qiyotganingizni yozib oling, yoki
.. Xabaringiz bilan bog'liq ba'zi tovushlarni yozib oling yoki yuklab oling
. `fitMedia()` funktsiyasidan foydalanib, ushbu yozuvlarni qo'shiqqa qo'shing
. So'ng `fitMedia()` funktsiyasidan foydalanib, qoʻshimcha EarSketch kliplarini qoʻshing
. Qo'shiqni do'stingizga taqdim eting
. Siz o'z qo'shiqlaringizni va ifodalamoqchi bo'lgan narsalarni muhokama qilishingiz mumkin
****

*Jarayonlar* yoki vazifalar kompyuteringizda ishlaydigan dasturlardir. Kompyuter CPU'si yoki *Markaziy Protsessor* ularni amalga oshiradi. 

Kompyuterning *xotirasi* Markaziy Protsessor foydalanishi uchun ma'lumotlar va ishlov berish ko'rsatmalarini o'z ichiga oladi. Xotira, shuningdek, asosiy xotira yoki RAM (Random Access Memory) deb ham ataladi, o'z ma'lumotlarini vaqtincha saqlaydi. Operativ xotirada faqat faol ishlayotgan jarayonlar uchun ma'lumotlar saqlanadi. Bu Markaziy Protsessor uchun ko'rsatmalar va ma'lumotlarga tezkor kirish imkonini beradi.

Xotira (yoki qisqa muddatli saqlash) va uzoq muddatli saqlash o'rtasida farq bor. Qattiq disk yoki bulutli zaxira kabi uzoq muddatli saqlash ikkilamchi xotira deb ataladi. *Ikkilamchi xotira*, hatto kompyuter o'chirilgandan keyin ham uzoq vaqt davomida katta hajmdagi ma'lumotlarni saqlaydi. Markaziy Protsessor to'g'ridan-to'g'ri ikkilamchi xotira bilan o'zaro aloqa qilmaydi. Markaziy Protsessor jarayonni amalga oshirayotganda, protsessor ularga tezda kira olishi uchun ikkilamchi xotiradan olingan ma'lumotlar birinchi navbatda xotiraga joylashtirilishi kerak.

Ba'zida Markaziy Protsessor foydalanishi uchun xotiradagi ma'lumotlar ikkilamchi xotira o'rniga kirish qurilmasidan keladi. *Kirishlar* - bu mikrofondan audio kabi kompyuter tomonidan qabul qilingan signallar yoki ma'lumotlar. Xuddi shunday, *chiqishlar* undan yuboriladigan signallar yoki ma'lumotlar, masalan, karnay orqali audio chiqishi. Kirish/chiqish yoki I/O - bu kompyuterning tashqi dunyo, jumladan, odamlar bilan aloqa vositasi!

Keling, misol sifatida EarSketch-ga ovoz yozishni ko'rib chiqaylik. Avval, biz ma'lumotlarni kompyuterga kiritish qurilmasi - mikrofon orqali yozib olamiz. Markaziy Protsessor bu audio ma'lumotlarni o'z xotirasida saqlaydi. Yozuvingizni tinglash uchun ijro tugmasini bossangiz, Markaziy Protsessor ma'lumotlarga kiradi va ularni chiqish, karnay yoki quloqchinlarga yuboradi. Yuklash tugmasini bosganingizda, Markaziy Protsessor audio ma'lumotlarni standart ovoz fayli formatiga (WAV fayli yoki .wav) o'zgartiruvchi jarayonni ishga tushiradi va uni EarSketch serveriga yuboradi. Server barcha EarSketch foydalanuvchilariga, shu jumladan shaxsiy kompyuteringizga xizmat ko'rsatadigan tashqi tizimdir. EarSketch serveri tovush faylini xotiradan serverning ikkilamchi xotirasiga saqlaydi, shunda siz kelajakda unga kirishingiz mumkin.

Quyidagi qo'shimcha videoni ko'ring:

[role="curriculum-mp4"]
[[video11cpu]]
video::./videoMedia/010-02-ProcessesandMemory-PY-JS.mp4[]

////
END OF OPTIONAL
////

[[copyright]]
=== Mualliflik Huquqidan Oqilona Foydalaning

*Mualliflik huquqi* qonunning *intellektual mulk* yoki musiqa kabi ijodiy ishlarga egalik huquqini qamrab oluvchi qismidir. Namunalarni (kichik musiqa qismlarini) ishlatganda yoki mavjud musiqalarni remiks qilishda siz mualliflarni ko'rsatib o'tishingiz kerak va buni kodingiz sharhlarida amalga oshirishingiz mumkin. Boshqa bastakorlarning tovushlaridan foydalanish va oʻz musiqangizni baham koʻrishdan oldin mualliflik huquqi haqida koʻproq bilib oling!

*Mualliflik huquqi* qonunning *intellektual mulk* yoki musiqa kabi ijodiy ishlarga egalik huquqini qamrab oluvchi qismidir. 

Original va yetarlicha mazmunli narsalarni yaratganingizda, siz avtomatik ravishda mualliflik huquqini olasiz! Qo'shma Shtatlarda, bu siz nusxa ko'chirishingiz, o'zgartirishlar kiritishingiz va yaratgan narsalaringizni baham ko'rishingiz mumkinligini anglatadi.

Qo'shiq bilan bog'liq ikkita mualliflik huquqi mavjud: qo'shiqqa bo'lgan huquqlar (yozuvchi yoki bastakor tomonidan) va tovushli yozuvga bo'lgan huquqlar (ko'pincha ovoz yozish kompaniyasi). Ommaviy chiqishlardan olingan to'lov haqi qo'shiq muallifiga tushadi va qo'shiq yozuvi sotishdan tushgan to'lov haqining aksariyati ovoz yozish kompaniyasiga tushadi. 

*Mualliflik huquqining buzilishi* musiqani noqonuniy yuklab olish kabi mualliflik huquqining buzilishidir. Qo'shma Shtatlarda *adolatli foydalanish* mualliflik huquqi bilan himoyalangan kontentdan ma'lum sharoitlarda, masalan, ta'lim yoki tanqidiy maqsadlarda foydalanishga ruxsat beradi, asarning faqat kichik qismini qayta ishlatishga imkon beradi. Odil foydalanish har bir holat uchun sudya tomonidan alohida-alohida belgilanadi.

Adolatli foydalanishdan tashqari, musiqadan ochiq foydalanish va ulashish usuli ham mavjud. Mualliflik huquqi bizga kam emas, balki ko'proq san'at yaratish va baham ko'rishda yordam berishi kerak. Ijrochilar Tovushlar Kutubxonasidagi *namunalar* (tovushli yozuvning kichik qismi) orqali siz bilan o'z ishlarini baham ko'rgani uchun EarSketch ishlaydi. Bu ijrochilar oʻz namunalarini boshqalarga shaxsiy asarlaridan foydalanishga ruxsat beruvchi *Creative Commons* litsenziyasi ostida ulashishgan. Shunday qilib, EarSketch-da siz ushbu namunalardan ochiq foydalanishingiz va siz EarSketch-da yaratgan barcha musiqalarni baham ko'rishingiz mumkin, biroq siz ularni sota olmaysiz. Musiqangizni baham ko'rish yoki boshqa talabalarga kodingizni remiks qilishiga ruxsat berish - bu badalni to'lash va dunyoga yangi san'at asalarini taqdim etishga yordam berish hisoblanadi.

*Creative Commons* (yoki CC) litsenziyalari ijodkorlarga qanday huquqlarni saqlab qolishi va qanday huquqlar berib yuborilishini belgilash imkonini beradi. Bu yerda CC litsenziyasining mumkin bo'lgan qismlari mavjud: "Siz bu asardan o'zingiz xohlagancha foydalanishingiz mumkin, faqat bu ISTISNOLAR..."

* "...siz u yerda mening ismimni qo'yishingiz shart." - (BY) Atributi
* "...siz uni umuman o'zgartira olmaysiz." - Derivativlarsiz (ND)
* "...siz undan pul ishlay olmaysiz." - Notijorat (NC)
* "...Ijod qilgan har qanday yangi narsangizni siz faqat bir litsenziya ostida baham ko'rishingiz kerak." - Hamkorlikda Foydalanish (SA)

Creative Commons litsenziyasini ko'rsatish uchun faqat turini tanlash va uni ishingizga joylash kifoya. EarSketch-da skriptni baham ko'rganingizda, sizdan qo'shiq uchun litsenziyani ko'rsatish so'raladi. 



[[chapter2summary]]
=== 2-Bob Xulosa

[role="curriculum-python"]
* *Temp* - bu musiqa asarining ijro etilish tezligi, u daqiqada zarba miqdorida (dzm) belgilanadi. Temp janrga bog'liq.
* EarSketch Tovushlar Kutubxonasidagi kliplar tegishli tovushlar papkalarida tashkil etilgan. Klipning aniq tempini ko'rish uchun Tovush Brauzerida kursorni ism ustiga olib boring.
* Sharhlar - bu kompyuter tomonidan bajarilmaydigan kod satrlari. Biroq, ular skript ichida eslatmalar qilish uchun foydalidir.
* `from earsketch import *` loyihangizga EarSketch IDI-ni qo‘shadi. U har bir skriptning yuqori qismiga kiritilishi kerak.
* `init()` musiqani qabul qilish va namoyish qilish uchun RAISni tayyorlaydi. U har bir EarSketch skriptida bo'lishi kerak.
* `setTempo();` qo'shiqning tempini belgilash imkonini beradi. U har bir EarSketch skriptiga kiritilishi kerak.
* `finish()` RAISga kodingiz tugallanganligi haqida xabar beradi. U har bir EarSketch skriptining oxirida kiritilishi kerak.
* Shaxsiy tovushlaringizni Sound Brauzeri orqali EarSketch-ga yuklashingiz mumkin. Shunchaki "Tovush Qo'shish" tugmasini bosing.
* *Jarayon* bu kompyuterda bajariladigan vazifadir. Qayta ishlash - dastur ko'rsatmalarini bajarish uchun mas'ul bo'lgan kompyuterning *Markaziy Protsessori* tomonidan amalga oshiriladi.
* *Xotira* (RAM yoki asosiy xotira deb nomlanadi) Markaziy Protsessor foydalanishi uchun maʼlumotlar va ishlov berish koʻrsatmalarini vaqtincha saqlaydi.
* *Ikkilamchi xotira* ma'lumotlarni uzoq muddatli, ko'pincha katta hajmlarda saqlashni nazarda tutadi. Protsessor ikkilamchi xotiradagi ma'lumotlarga kira olishi uchun ular xotiraga joylashtirilishi kerak.
* *Mualliflik huquqi* - bu musiqa kabi ijodiy ishlarga egalik huquqini qamrab oluvchi qonunning bir qismi. Bastakorlar uchun bu muhim, chunki u boshqa shaxsning ishidan qanday foydalanish va almashish mumkinligini belgilaydi.
* Agar siz aniq va yangi musiqiy asar yaratsangiz, sizda avtomatik ravishda mualliflik huquqi mavjud. Boshqacha qilib aytganda, siz yaratgan asar ustida huquqlarga egasiz.
* Musiqa asarini *litsenziyalash* boshqalarga undan foydalanishga ruxsat beradi. Ba'zan asarga bo'lgan muayyan huquqlar *Creative Commons* litsenziyalari bilan saqlanadi. EarSketch sizga Ulashish oynasi orqali musiqangizga Creative Commons litsenziyalarini qo'shish imkonini beradi.

[role="curriculum-javascript"]
* *Temp* - bu musiqa asarining ijro etilish tezligi, u daqiqada zarba miqdorida (dzm) belgilanadi. Temp janrga bog'liq.
* EarSketch Tovushlar Kutubxonasidagi kliplar tegishli tovushlar papkalarida tashkil etilgan. Klipning aniq tempini ko'rish uchun Tovush Brauzerida kursorni ism ustiga olib boring.
* Sharhlar - bu kompyuter tomonidan bajarilmaydigan kod satrlari. Biroq, ular skript ichida eslatmalar qilish uchun foydalidir.
* `init();` musiqani qabul qilish va namoyish qilish uchun RAISni tayyorlaydi. U har bir EarSketch skriptida bo'lishi kerak.
* `setTempo();` qo'shiqning tempini belgilash imkonini beradi. U har bir EarSketch skriptiga kiritilishi kerak.
* `finish();` RAISga kodingiz tugallanganligi haqida xabar beradi. U har bir EarSketch skriptining oxirida kiritilishi kerak.
* Shaxsiy tovushlaringizni Sound Brauzeri orqali EarSketch-ga yuklashingiz mumkin. Shunchaki "Tovush Qo'shish" tugmasini bosing.
* *Jarayon* bu kompyuterda bajariladigan vazifadir. Qayta ishlash - dastur ko'rsatmalarini bajarish uchun mas'ul bo'lgan kompyuterning *Markaziy Protsessori* tomonidan amalga oshiriladi.
* *Xotira* (RAM yoki asosiy xotira deb nomlanadi) Markaziy Protsessor foydalanishi uchun maʼlumotlar va ishlov berish koʻrsatmalarini vaqtincha saqlaydi.
* *Ikkilamchi xotira* ma'lumotlarni uzoq muddatli, ko'pincha katta hajmlarda saqlashni nazarda tutadi. Protsessor ikkilamchi xotiradagi ma'lumotlarga kira olishi uchun ular xotiraga joylashtirilishi kerak.
* *Mualliflik huquqi* - bu musiqa kabi ijodiy ishlarga egalik huquqini qamrab oluvchi qonunning bir qismi. Bastakorlar uchun bu muhim, chunki u boshqa shaxsning ishidan qanday foydalanish va almashish mumkinligini belgilaydi.
* Agar siz aniq va yangi musiqiy asar yaratsangiz, sizda avtomatik ravishda mualliflik huquqi mavjud. Boshqacha qilib aytganda, siz yaratgan asar ustida huquqlarga egasiz.
* Musiqa asarini *litsenziyalash* boshqalarga undan foydalanishga ruxsat beradi. Ba'zan asarga bo'lgan muayyan huquqlar *Creative Commons* litsenziyalari bilan saqlanadi. EarSketch sizga Ulashish oynasi orqali musiqangizga Creative Commons litsenziyalarini qo'shish imkonini beradi.




[[chapter-questions]]
=== Savollar

[question]
--
`setTempo()` EarSketch-da qanday imkoniyat beradi?
[answers]
* Qo'shiqning tempini belgilash
* Trekka tovush qo'shish
* Baraban zarbasini yaratish
* Loyiha doirasida tovush sifatini o'zgartirish
--

[question]
--
Temp birligi nima?
[answers]
* DZM (Daqiqada Zarba Miqdori)
* O'lchovlar
* Detsibellar(dB)
* Soniyalar
--

[question]
--
Izohlarni nima uchun ishlatishingiz mumkin?
[answers]
* Yuqoridagilarning barchasi
* Kodingizni tartibga solish
* Skriptingizning boshida skriptingiz izohini yozish
* Kodingizni boshqa dasturchilar uchun o'qishni osonlashtiradi
--

[question]
--
Quyidagi bayonotlardan qaysi biri to‘g‘ri?
[answers]
* Qattiq disk ikkilamchi xotiraga misol bo'la oladi
* Audio ma'lumotlar kompyuterning Markaziy Protsessoriga saqlanadi
* Markaziy Protsessor dasturlar uchun ko'rsatma ma'lumotlarini saqlaydi
* Ikkilamchi xotira ma'lumotlarni qisqa vaqt davomida saqlaydi
--

[question]
--
Qanday qilib mualliflik huquqini olasiz?
[answers]
* Har qanday yangi asar yaratish va nashr etish orqali
* Patent sotib olish orqali
* Yashirin tashkilotga a'zo bo'lish orqali
* Ishingiz uchun litsenziya tanlash orqali
--

[question]
--
Creative Commons nima?
[answers]
* Muayyan cheklovlar ostida ishingizni ochiq baham ko'rish uchun litsenziya
* Bastalash jarayoni
* Musiqangizdan foydalanadigan har qanday odamni sudga berish huquqi
* To'lov haqi yig'ish imkonini beruvchi litsenziya
--
