[[customizeyourfirstsong]]
== שנו, לפי טעמכם/ן, את השיר הראשון שלכן/ם

:nofooter:

בפרק זה תלמדו איך לשנות את הקצב של השיר שלכם, להוסיף הערות לקוד ולטעון צלילים משלכם כדי להדגיש את המסר של השיר.

[[settempo]]
=== The `setTempo()` function

[role="curriculum-python"]
--
By now you've noticed that when you create a new script, there are preexisting elements added for your benefit:

. Some comments starting with `#`: we'll cover that in next section
. the `from earsketch import*` line, which adds the EarSketch functions (like `fitMedia()`) to the project
. the `setTempo(120)` function, which we will see in detail below
--

[role="curriculum-javascript"]
--
By now you've noticed that when you create a new script, there are preexisting elements added for your benefit:

. Some comments starting with `//`: we'll cover that in next section
. the `setTempo(120)` function, which we will see in detail below
--

The `setTempo()` function will determine the speed of your song. The *tempo* is a number of beats per minute (bpm) in Western music. ב-EarSketch' ערך ברירת המחדל של הטמפו (כלומר, הערך הראשוני של המפעם) הוא 120bpm, שמתואם להליכה מהירה או מהירות צעידה. To change the tempo, just change the number between the parentheses of the `setTempo()` function. ככל שהטמפו יותר גבוה, המוסיקה יותר מהירה. You can select a tempo between _45bpm and 220bpm_.

.תרגלו
****
. צרו סקריפט חדש.
. Place sounds on two different tracks.
. Modify your tempo and listen to the song.
. Play your song at three different tempos for a friend. בקשו מהחבר/ה לדרג את השירים לפי הטמפו, מהנמוך לגבוה.
****

סוגה (ז'אנר) היא קטגוריה של יצירה אומנותית (לדוגמה: מוסיקה) שמאופיינת בדמיון בצורה, בסגנון ובתוכן. לסוגות שונות של מוזיקה אלקטרונית טווחים שונים של טמפו אופייני. לדוגמה:

[cols="^3*"]
|===
|סוגה |BPM |דוגמה

|Pop (פופ)
|110-130
|"Thriller" - Michael Jackson

"I Wanna Dance With Somebody" - Whitney Houston

|Hip-Hop
|70-100
|"Rapper's Delight" - The Sugar Hill Gang

"Fight the Power" - Public Enemy

|Country
|90-110
|"I Walk the Line" - Johnny Cash

"Jolene" - Dolly Parton

|House / EDM
|110-130
|"One More Time" - Daft Punk

"Good Vibrations" - Marky Mark

|Dubstep / Trap
|140-150
|"Scary Monsters and Nice Sprites" - Skrillex

"Turn Down for What" - Lil Jon
|===

.תרגלו
****
. בחרו אמן או אמנית שאתם מאוד אוהבים. בררו לאיזו סוגה (ז'אנר) הוא/היא שייכים.
. Search that genre (on https://soundcloud.com/[Soundcloud] or something similar) and listen to a few snippets of songs in that genre.
. נסו למצוא קווי דמיון בין השירים.
. אתם יכולים לחקור וללמוד על סוגה זו בעזרת וויקיפדיה ומקורות אחרים.
****

Sounds are automatically stretched to fit your song's tempo. This is why sounds previewed in the Sound Browser sometimes appear different from in your song. The effect can be extreme if the tempos are very different.

To find the original tempo of sound, hover over the sound constant Sound Browser.

[[comments]]
=== Adding comments to your code

*Comments* are lines of code ignored by the computer. People use comments to make notes within the code.

EarSketch scripts begin with comments that you can use to enter a description of your song. These details make it easier for other programmers to understand what your code is about.

[role="curriculum-python"]
In Python, comments are indicated by a line starting with a pound `#` symbol.

[role="curriculum-javascript"]
In JavaScript, comments are indicated by a line starting with two forward slashes, `//`.

.תרגלו
****
In your current script, write a comment with a description of your song on the first line.
****

אפשר להשתמש בהערות כדי לציין מה עושים חלקים שונים בקוד. הנה דוגמה. אתם יכולים להריץ את הקוד. שימו לב שההערות מתארות את החלקים השונים בקוד:

[role="curriculum-python"]
[source,python]
----
include::code-examples/your-first-song-comments.py.txt[]
----

[role="curriculum-javascript"]
[source,javascript]
----
include::code-examples/your-first-song-comments.js.txt[]
----

{nbsp} +

[[uploadingsounds]]
=== Uploading your own sounds

You can upload your own sounds through the Sound Browser on the left side of your screen. Under the "Sounds" tab, click on the "Add sound" button.

You must be logged in to upload sounds.

Let's explore the first three options.

. *Upload Sound* allows you to choose audio files already on your computer.
. *Quick Record* lets you record directly from your computer's microphone.
. *Freesound* allows you to import sounds from http://freesound.org[freesound.org^], an open-source audio database. In the search bar, you can look for a type of sound. Then select the toggle button in front of the file name to select.

[role="curriculum-mp4"]
[[video101rec]]
video::./videoMedia/010-01-Recording&UploadingSounds-PY-JS.mp4[]

.תרגלו
****
מוסיקה, ואמנות בכלל, היא, לעיתים קרובות, אמצעי להעברת מסר. המסר מועבר בעזרת המילים ו/או האופי של השיר. כתבו שיר קצר שמבטא משהו. It can be a feeling that you'd like to share, or a story.

. Think about what you'd like to express
. Then either:
.. Write some lyrics and record yourself singing or reading them or
.. Record or download some sounds that are related to your message
. Add these recordings to your song using `fitMedia()`
. Then add additional sounds using `fitMedia()`
. השמיעו את השיר לחבר/ה
. שוחחו על השיר ועל הדברים שניסיתם להביע בו
****

An active computer program is called a *process*.

When you start a process, the computer code is first stored in the computer's *memory* for quick access. The *CPU*, or Central Processing Unit, accesses each instruction from the memory and executes it. The CPU is often considered the "brain" of the computer.

A computer's memory is sometimes called primary storage or RAM. It is designed to be fast and temporary, for active processes only.

יש הבדל בין זיכרון (או אחסון קצר טווח) לבין אחסון ארוך טווח. אחסון ארוך טווח, כמו דיסק קשיח או ענן, נקרא גם אחסון משני. *Secondary storage* holds high volumes of data for long periods of time, even after a computer is shut down. ה-CPU לא מתקשר ישירות עם האחסון המשני. כשה-CPU מריץ תהליך, קודם כל, נטענים נתונים מהאחסון המשני אל הזיכרון כך שה-CPU יוכל לגשת אליהם במהירות.

לפעמים הנתונים בזיכרון, בהם משתמש ה-CPU, מגיעים מאמצעי קלט ולא מהאחסון המשני. *Inputs* are the signals or data received by the computer, like audio from a microphone. Likewise, *outputs* are the signals or data sent from it, like audio through a speaker. קלט/פלט או I/O, היא הדרך בה המחשב מתקשר עם העולם החיצוני, כולל בני אדם!

Let's examine recording a sound into EarSketch as an example process. ראשית, אנחנו מקליטים נתונים לתוך המחשב בעזרת אמצעי קלט - המיקרופון. ה-CPU מאחסן את נתוני השמע בזיכרון. כשנלחץ "play" כדי לשמוע את ההקלטה, ה-CPU ניגש לנתונים ושולח אותם לאמצעי פלט - אזניות או רמקול. כשנלחץ על upload, ה-CPU יריץ את התהליך שממיר את נתוני השמע לקובץ בפורמט שמע סטנדרטי (wav), וישלח את הקובץ לשרת EarSketch. השרת הוא מערכת חיצונית שמספקת שירותים לכל משתמשי EarSketch, כולל המחשב שלנו. The EarSketch server saves the sound file from memory to the server's secondary storage so that you can access it in the future.

צפו בווידאו הבא:

[role="curriculum-mp4"]
[[video11cpu]]
video::./videoMedia/010-02-ProcessesandMemory-PY-JS.mp4[]

////
END OF OPTIONAL
////

[[copyright]]
=== זכויות יוצרים

*Copyright* is the part of law that covers *intellectual property*, or ownership of creative work, like music. כשמשתמשים בסימפולים או עושים רמיקס למוסיקה קיימת, צריך לתת קרדיט למחברים. בסקריפט של EarSketch אפשר לעשות זאת בהערות בקוד. לפני שמשתמשים בצלילים של מוסיקאים אחרים וחולקים מוסיקה, יש ללמוד על זכויות יוצרים!

כשאתם יוצרים משהו מקורי וממשי, יש לכם זכויות יוצרים עליו באופן אוטומטי! זה אומר שאתם יכולים להכין ממנו עותקים, לשנות אותו ולחלוק אותו.

יש שתי זכויות יוצרים הקשורות לשיר: זכויות על השיר עצמו (של המחבר/ת) וזכויות על הביצוע, כלומר ההקלטה של השיר (בדרך כלל של חברת התקליטים). תמלוגים מביצועים פומביים של השיר משולמים למחבר/ת, ורוב התמלוגים ממכירת הקלטות של השיר משולמים לחברת התקליטים.

*Copyright infringement* is a violation of copyright, like illegally downloading music. In the United States, *fair use* allows for use of copyrighted content under certain conditions, like educational or critical purposes, reusing only small amounts of the work. Fair use disputes are determined by a judge on a case-by-case basis.

Besides fair use, there are other ways to use and share music openly. EarSketch works because artists have shared their work with you through *samples* (a small part of sound recording) in the Sound Browser.

Copyright is not all about getting people in trouble. If you upload a song to the internet, you might not mind if someone downloads it without asking; you want people to share your music! זכויות יוצרים אמורות להקל על יצירה ושיתוף, ולא להכביד עליהן. When you are creating songs in EarSketch, we want you to think less about _stealing_ and more about _sharing_. EarSketch works because artists have shared their work with you, resulting in the library of samples you use to make new music. שיתוף המוסיקה שיצרתם ולאפשר לאחרים להשתמש בקוד שלכם, היא הדרך שלכם להעביר את זה הלאה, ולתרום ליצירת עוד אמנות.

When using sounds in your EarSketch scripts, you'll need to be sure that you have permission from the copyright holder to use the sounds, or that you are using them in accordance with fair use.

For full details, refer to our https://earsketch.gatech.edu/landing/#/license[LICENSE^].

[[chapter2summary]]
=== סיכום פרק שני

[role="curriculum-python"]
* *Tempo* is the speed at which a piece of music is played, specified in beats per minute (bpm). טמפו קשור לסוגה (ז'אנר).
* The sounds in the EarSketch Sound Browser are organized into folders of related sounds. כדי לדעת מה הטמפו של קליפ, עברו בספריית הצלילים, עם העכבר, מעל שמו.
* Comments are lines of code that are ignored by the computer. They are useful for making notes within a script.
* `from earsketch import *` adds the EarSketch API to your project.
* `setTempo()` lets you specify the tempo of your song. שורה זו חייבת להיכלל בכל סקריפט.
* אתם יכולים להעלות צלילים משלכם ל-EarSketch בעזרת דפדפן הצלילים. פשוט הקליקו על "Add sound".
* A *process* is a program running on a computer. Processing is carried out by a computer's *CPU*, which is responsible for executing program instructions.
* *Memory* (a.k.a RAM or primary storage) holds data and processing instructions temporarily for the CPU to use.
* *Secondary storage* refers to long term storage of data, often in high volumes. נתונים מהאחסון המשני חייבים להטען לזיכרון לפני שה-CPU משתמש בהם.
* *Copyright* is a portion of law that covers ownership of creative works, like music. It is important to musicians because it defines how another person's work can be used and shared.
* אם יצרתם יצירה ממשית ומקורית, יש לכם, אוטומטית, זכויות יוצרים עליה. במילים אחריות, יש לכם בעלות על יצירות שיצרתם.
* *Licensing* a piece of music gives others permission to use it.

[role="curriculum-javascript"]
* *Tempo* is the speed at which a piece of music is played, specified in beats per minute (bpm). טמפו קשור לסוגה (ז'אנר).
* The sounds in the EarSketch Sound Browser are organized into folders of related sounds. כדי לדעת מה הטמפו של קליפ, עברו בספריית הצלילים, עם העכבר, מעל שמו.
* Comments are lines of code that are ignored by the computer. They are useful for making notes within a script.
* `setTempo();` lets you specify the tempo of your song. שורה זו חייבת להיכלל בכל סקריפט.
* אתם יכולים להעלות צלילים משלכם ל-EarSketch בעזרת דפדפן הצלילים. פשוט הקליקו על "Add sound".
* A *process* is a program running on a computer. Processing is carried out by a computer's *CPU*, which is responsible for executing program instructions.
* *Memory* (a.k.a RAM or primary storage) holds data and processing instructions temporarily for the CPU to use.
* *Secondary storage* refers to long term storage of data, often in high volumes. נתונים מהאחסון המשני חייבים להטען לזיכרון לפני שה-CPU משתמש בהם.
* *Copyright* is a portion of law that covers ownership of creative works, like music. It is important to musicians because it defines how another person's work can be used and shared.
* אם יצרתם יצירה ממשית ומקורית, יש לכם, אוטומטית, זכויות יוצרים עליה. במילים אחריות, יש לכם בעלות על יצירות שיצרתם.
* *Licensing* a piece of music gives others permission to use it.

[[chapter-questions]]
=== שאלות

[question]
--
What does `setTempo()` allow you to do in EarSketch?

[answers]
* לקבוע את הטמפו (מפעם) של השיר
* הוספת צליל לערוץ
* שינוי ביט תיפוף
* שינוי האיכויות של צליל בפרויקט
--

[question]
--
מה היחידה לטמפו?

[answers]
* פעימות לדקה (BPM)
* תיבות
* דציבלים (dB)
* שניות
--

[question]
--
למה משמשות הערות?

[answers]
* כל התשובות נכונות
* ארגון הקוד
* כתיבת תיאור של הסקריפט בתחילתו
* הפיכת הקוד לקריא יותר, עבור מתכנתים אחרים
--

[question]
--
מי מהטענות הבאות נכונה?

[answers]
* דיסק קשיח הוא דוגמה לאחסון משני
* נתוני שמע נשמרים ב-CPU
* ה-CPU מאחסן הוראות לתכניות
* אחסון משני מאחסן נתונים לזמן קצר
--

[question]
--
כיצד משיגים זכויות יוצרים?

[answers]
* על-ידי יצירה ופרסום של עבודה חדשה
* על-ידי קניית פטנט
* על-ידי הצטרפות לארגון חשאי
* על-ידי בחירת הרשאות ליצירה שלכם
--

[question]
--
What is a music license?

[answers]
* A license gives others permission to use a musical work
* תהליך הלחנה
* A musical genre
* A description of your song
--