version: 0.2

env:
  parameter-store:
    ES_HOST: /earsketch-webclient/BuildConfig/$ES_BUILD_ENVIRONMENT/client_host
  secrets-manager:
    GITHUB_USER: Github_EarSketch_CICD_Credentials:github_user
    GITHUB_TOKEN: Github_EarSketch_CICD_Credentials:github_token

phases:
  install:
    commands:
      - echo Entered the install phase...
      - yum install -y asciidoctor
      - pip install BeautifulSoup4
  pre_build:
    commands:
      - export ES_SCRIPT_HOME="$CODEBUILD_SRC_DIR/scripts"
      - export SRC_DIR="$CODEBUILD_SRC_DIR/src"
      - export ASCIIDOC_DIR="$CODEBUILD_SRC_DIR/src/locales"
      - export LOCAL_STAGING_DIR_NAME="${CODEBUILD_SOURCE_VERSION//\//-}/"
      - export LOCAL_STAGING_DIR="$CODEBUILD_SRC_DIR/$LOCAL_STAGING_DIR_NAME"
  build:
    commands:
      - du -sh $CODEBUILD_SRC_DIR
      - echo $ES_SCRIPT_HOME
      - echo $ASCIIDOC_DIR
      - echo $CODEBUILD_SOURCE_VERSION
      - echo $LOCAL_STAGING_DIR
      - echo Finished printing variables
      - echo "Entered the build phase..."
      - |
        declare -a locale_array=(en
                              es
                              ar
                              he
                              fr
                              iu
                              oj)
  
        declare -a locale_subdir_array=(v1
                                      v2)
        # render the table of contents template first
        TOC_TEMPLATE=$ASCIIDOC_DIR/toc_template.adoc
        TOC_TEMPLATE_HTML=$LOCAL_STAGING_DIR/toc_template.html
        asciidoctor \
          -a stylesheet="$ES_SCRIPT_HOME/curr_blank.css" \
          -D "$LOCAL_STAGING_DIR" "$TOC_TEMPLATE" || exit 1
        for locale_path in "${locale_array[@]}"
        do
          LOCALE_STAGE_DIR=$LOCAL_STAGING_DIR/$locale_path/
          mkdir $LOCALE_STAGE_DIR
          for locale_subdir in "${locale_subdir_array[@]}"
          do
            echo "Converting curriculum to html with asciidoctor in directory " $locale_path/$locale_subdir
            locale_full_path=$ASCIIDOC_DIR/$locale_path/$locale_subdir
            echo "Curriculum full path " $locale_full_path
            LOCALE_STAGE_SUB_DIR=$LOCAL_STAGING_DIR/$locale_path/$locale_subdir/
            [ ! -d "$locale_full_path" ] && continue
            asciidoctor \
              -a stylesheet="$ES_SCRIPT_HOME/curr_blank.css" \
              -D "$LOCALE_STAGE_SUB_DIR" "$locale_full_path/*.adoc" || exit 1
            python3 "$ES_SCRIPT_HOME/curr_add_html_features.py" "$SRC_DIR" "$LOCALE_STAGE_SUB_DIR" "$ES_HOST" || exit 1
          done
          echo "about to copy toc template"
          # outer loop, this is a root locale directory. process the table of contents
          cp $TOC_TEMPLATE_HTML $LOCALE_STAGE_DIR/toc.html
          python3 "$ES_SCRIPT_HOME/curr_toc.py" "$LOCALE_STAGE_DIR" || exit 1
          python3 "$ES_SCRIPT_HOME/curr_searchdoc.py" "$LOCALE_STAGE_DIR" || exit 1
        done
      - echo "Completed curriculum build"
      - cd "$SRC_DIR"
      - echo "Copying curriculum files to local distribution folder..."
      - cp -r audioMedia/ curriculum/ videoMedia/ theme/ "$LOCAL_STAGING_DIR"

artifacts:
  files:
    - '**/*'
  base-directory: $LOCAL_STAGING_DIR_NAME
