version: 0.2

env:
  parameter-store:
    ES_HOST: /earsketch-webclient/BuildConfig/$ES_BUILD_ENVIRONMENT/client_host
  secrets-manager:
    GITHUB_USER: Github_EarSketch_CICD_Credentials:github_user
    GITHUB_TOKEN: Github_EarSketch_CICD_Credentials:github_token

phases:
  install:
    commands:
      - echo Entered the install phase...
      - yum install -y asciidoctor
      - pip install BeautifulSoup4
  pre_build:
    commands:
      - export ES_SCRIPT_HOME="$CODEBUILD_SRC_DIR/scripts"
      - export ASCIIDOC_DIR="$CODEBUILD_SRC_DIR/src"
      - export LOCAL_STAGING_DIR_NAME="${CODEBUILD_SOURCE_VERSION//\//-}/"
      - export LOCAL_STAGING_DIR="$CODEBUILD_SRC_DIR/$LOCAL_STAGING_DIR_NAME"
  build:
    commands:
      - du -sh $CODEBUILD_SRC_DIR
      - echo $ES_SCRIPT_HOME
      - echo $ASCIIDOC_DIR
      - echo $CODEBUILD_SOURCE_VERSION
      - echo $LOCAL_STAGING_DIR
      - echo Finished printing variables
      - echo "Entered the build phase..."
      - echo "Converting curriculum to html with asciidoctor..."
      - asciidoctor -a stylesheet="$ES_SCRIPT_HOME/curr_blank.css" -D "$LOCAL_STAGING_DIR" "$ASCIIDOC_DIR/*.asc"
      - python "$ES_SCRIPT_HOME/curr_add_html_features.py" "$ASCIIDOC_DIR" "$LOCAL_STAGING_DIR" "$ES_HOST"
      - python "$ES_SCRIPT_HOME/curr_toc.py" "$LOCAL_STAGING_DIR"
      - python "$ES_SCRIPT_HOME/curr_searchdoc.py" "$LOCAL_STAGING_DIR"
      - echo "Moving JSON files from staging area to webclient..."
      # - mv -v curriculum-asciidoc/curr_toc.js webclient/scripts/src/data
      # - mv -v curriculum-asciidoc/curr_pages.js webclient/scripts/src/data
      # - mv -v curriculum-asciidoc/curr_searchdoc.js webclient/scripts/src/data
      - echo "Completed curriculum build"
      - cd src
      - echo "Copying curriculum files to local distribution folder..."
      - cp -r audioMedia/ curriculum/ videoMedia/ theme/ "$LOCAL_STAGING_DIR"
      # - python "$ES_SCRIPT_HOME/github_create_deployment.py" $GITHUB_USER $GITHUB_TOKEN $CODEBUILD_RESOLVED_SOURCE_VERSION $LOCAL_STAGING_DIR_NAME

artifacts:
  files:
    - '**/*'
  base-directory: $LOCAL_STAGING_DIR_NAME
