version: 0.2

env:
  parameter-store:
    ES_HOST: /earsketch-webclient/BuildConfig/$ES_BUILD_ENVIRONMENT/client_host
  secrets-manager:
    GITHUB_USER: Github_EarSketch_CICD_Credentials:github_user
    GITHUB_TOKEN: Github_EarSketch_CICD_Credentials:github_token

phases:
  install:
    commands:
      - echo Entered the install phase...
      - yum install -y asciidoctor
      - pip install BeautifulSoup4
  pre_build:
    commands:
      - export ES_SCRIPT_HOME="$CODEBUILD_SRC_DIR/scripts"
      - export SRC_DIR="$CODEBUILD_SRC_DIR/src"
      - export ASCIIDOC_DIR="$CODEBUILD_SRC_DIR/src/locales"
      - export LOCAL_STAGING_DIR_NAME="${CODEBUILD_SOURCE_VERSION//\//-}/"
      - export LOCAL_STAGING_DIR="$CODEBUILD_SRC_DIR/$LOCAL_STAGING_DIR_NAME"
  build:
    commands:
      - du -sh $CODEBUILD_SRC_DIR
      - echo $ES_SCRIPT_HOME
      - echo $ASCIIDOC_DIR
      - echo $CODEBUILD_SOURCE_VERSION
      - echo $LOCAL_STAGING_DIR
      - echo Finished printing variables
      - echo "Entered the build phase..."
      - |
        for locale_full_path in $ASCIIDOC_DIR/*/
        do
          echo "Converting curriculum to html with asciidoctor in directory " $locale_full_path
          LOCALE=$(basename $locale_full_path)
          LOCALE_STAGE_DIR=$LOCAL_STAGING_DIR/$LOCALE/
          asciidoctor \
            -a stylesheet="$ES_SCRIPT_HOME/curr_blank.css" \
            -D "$LOCALE_STAGE_DIR" "$locale_full_path/*.asc" || exit 1
          python "$ES_SCRIPT_HOME/curr_add_html_features.py" "$SRC_DIR" "$LOCALE_STAGE_DIR" "$ES_HOST" || exit 1
          python "$ES_SCRIPT_HOME/curr_toc.py" "$LOCALE_STAGE_DIR" || exit 1
          python "$ES_SCRIPT_HOME/curr_searchdoc.py" "$LOCALE_STAGE_DIR" || exit 1
        done
      - echo "Completed curriculum build"
      - cd "$SRC_DIR"
      - echo "Copying curriculum files to local distribution folder..."
      - cp -r audioMedia/ curriculum/ videoMedia/ theme/ "$LOCAL_STAGING_DIR"

artifacts:
  files:
    - '**/*'
  base-directory: $LOCAL_STAGING_DIR_NAME
