[[welcome]]
== اهلا وسهلا بالطلاب والمعلمين!

:nofooter:

Welcome to EarSketch!

* المعلمون *: شاهد https://earsketch.gatech.edu/teachermaterials/EarSketch_Alignment_Guide.pdf دليل المناهج الجديدة ^] ، وقم بزيارة https://www.teachers.earsketch.org [موقع EarSketch للمعلمين ^] للحصول على معلومات إضافية مصادر.

* الطلاب *: تابع أدناه لمعرفة المزيد حول EarSketch

Here you will learn computer science and music technology side by side. You will use either Python or JavaScript to create your own music.

Musicians and programmers write computer code to create new sounds, effects, and songs.

[role="curriculum-mp4"]
[[video0]]
video::../landing/media/homepagevid.a1cf3d01.mp4[poster=../landing/img/homepagevid-poster.8993a985.png]

Learning to write computer code is a skill that will be useful to you in a variety of career paths.

ربما ستصبح منتجًا موسيقيًا أسطوريًا أو مهندس التسجيل الأكثر رواجًا في الصناعة! We wish you good luck on your EarSketch journey.

Click on the right arrow at the top of this text to get started.

يمكن للمعلمين الوصول إلى مواد المعلم المجانية و المجتمع https://www.teachers.earsketch.org/[هنا ^]!