[[welcome]]
== اهلا وسهلا بالطلاب والمعلمين!

:nofooter:

مرحبا بكم في EarSketch!

* المعلمون *: شاهد https://earsketch.gatech.edu/teachermaterials/EarSketch_Alignment_Guide.pdf دليل المناهج الجديدة ^] ، وقم بزيارة https://www.teachers.earsketch.org [موقع EarSketch للمعلمين ^] للحصول على معلومات إضافية مصادر.

* الطلاب *: تابع أدناه لمعرفة المزيد حول EarSketch

هنا سوف تتعلم علوم الكمبيوتر وتكنولوجيا الموسيقى جنبا إلى جنب. سوف تستخدم إما Python أو JavaScript لإنشاء الموسيقى الخاصة بك.

يكتب الموسيقيون والمبرمجون أكواد الكمبيوتر لإنشاء أصوات وتأثيرات وأغاني جديدة.

[role="curriculum-mp4"]
[[video0]]
video::../landing/media/homepagevid.a1cf3d01.mp4[poster=../landing/img/homepagevid-poster.8993a985.png]

تعلم كتابة كود الكمبيوتر "البرمجة" هو مهارة ستكون مفيدة لك في مسارات مهنية متنوعة.

ربما ستصبح منتجًا موسيقيًا أسطوريًا أو مهندس التسجيل الأكثر رواجًا في الصناعة! نتمنى لك حظًا سعيدًا في رحلة ب EarSketch.

انقر فوق السهم الأيمن أعلى هذا النص للبدء.

يمكن للمعلمين الوصول إلى مواد المعلم المجانية و المجتمع https://www.teachers.earsketch.org/[هنا ^]!