[[customizeyourfirstsong]]
== تخصيص أغنيتك الأولى

:nofooter:

في هذا الفصل ستتعلم كيفية تغيير إيقاع أغنيتك وإضافة التعليقات إلى الكود الخاص بك وتحميل الأصوات الخاصة بك لتحسين رسالة أغنيتك.

[[settempo]]
=== ()setTempo

[role="curriculum-python"]
--
By now you've noticed that when you create a new script, there are preexisting elements added for your benefit:

. هناك ملاحظات التي تبدأ بـ `#` باللون الرمادي: سوف نغطي شرح ذلك في القسم التالي.
. السطر
from Earsketch import*
الذي يضيف دوال Earsketch  مثل
  ()fitMedia
للمشروع
. الدالة `setTempo(120)` التي سنشرحها بالتفصيل أدناه
--

[role="curriculum-javascript"]
--
By now you've noticed that when you create a new script, there are preexisting elements added for your benefit:

. هناك ملاحظات التي تبدأ بـ`//` باللون الرمادي: سوف نغطي شرح ذلك في القسم التالي.
. الدالة `setTempo(120)` التي سنشرحها بالتفصيل أدناه
--

ستحدد دالة ()setTempo سرعة أغنيتك. tempo (إيقاع بالعربية) في الموسيقى الغربية. في EarSketch ، يتم تعيين الإيقاع الافتراضي (أي القيمة الأولية لtempo) إلى 120 جزء من المليون، وهو ما يقابل للمشي السريع في حياتنا. لتغيير الايقاع tempo، فقط قم بتغيير الرقم بين قوسين لوظيفة `setTempo()`. The higher the tempo, the faster your music. يمكنك تحديد الإيقاع بين    45 bpm  و  220 bpm.

.تدريب
****
. إنشاء سكريبت جديد.
. ضع الأصوات على مسارين مختلفين،
. قم بتعديل الإيقاع الخاص بك والاستماع إلى الأغنية،
. شغل أغنيتك في 3 ايقاعات مختلفة لصديق. ثم اطلب منهم ترتيب الايقاعات من الأبطأ إلى الأسرع.
****

القالب الموسيقي هو فئة من الانتاجات الفنية مثل (الموسيقى) والتي تتشابه بصفاتها وشكلها او محتواها. Different genres have different tempo ranges. قوالب مختلفة لها ايقاعات مختلفة على سبيل المثال:

[cols="^3*"]
|===
|GENRE |BPM |مثال

|البوب Pop
|110-130
|"Thriller" - Michael Jackson

"I Wanna Dance With Somebody" - Whitney Houston

|Hip Hop
|100-130
|"Rapper's Delight" - The Sugar Hill Gang

"Fight the Power" - Public Enemy

|Country
|115-130
|"I Walk the Line" - Johnny Cash

"Jolene" - Dolly Parton

|House / EDM
|110-130
|"One More Time" - Daft Punk

"Good Vibrations" - Marky Mark

|دب ستيب & تراب Dubstep and Trap
|140-150
|"Scary Monsters and Nice Sprites" - Skrillex

"Turn Down for What" - Lil Jon
|===

.تدريب
****
. اختر فنانًا واحداً تحبه حقًا و اكتشف نوع القالب الفني الذي ينتمي إليه.
. ابحث عن هذا النوع من القالب الفني (على ساوندكلود أو ما شابه ذلك) واستمع إلى بضعة من الأغاني هذا النوع.
. اصغي لأوجه التشابه بين الأغاني.
. بإمكانك أيضاً أن تبحث عن نوع القالب في ويكيبيديا للحصول على مزيد من المعلومات عنه.
****

Sounds are automatically stretched to fit your song's tempo. لاحظ أن مقطع صوت واحد سيبدو في بعض الأحيان مختلفا جدا عند معاينته وعند تشغيله في أغنيتك. قد يكون ذلك لأن سرعة ايقاع مقطع الصوت مختلفة عن سرعة ايقاع أغنيتك temp. لمعرفة الإيقاع الدقيق للمقطع، مرر الماوس (الفأره) فوق اسم المقطع في متصفح (Browser) الصوت. The effect can be extreme if the tempos are very different.

للعثور على الصوت الذي قمت برفعه أو تسجيله للتو، اكتب اسمه في شريط البحث في متصفح الصوت.

[[comments]]
=== أضف الملاحظات إلى تعليماتك البرمجية (الكود)

*الملاحظات في JavaScript* هي أسطر من التعليمات البرمجية التي لا يتم تنفيذها بواسطة الكمبيوتر. People use comments to make notes within the code.

EarSketch scripts begin with comments that you can use to enter a description of your song. هذا يجعل من الأسهل على المبرمجين الآخرين فهم ما هو الكود الخاص بك.

[role="curriculum-python"]
في Python، يشار إلى الملاحظات بواسطة سطر يبدأ بالرمز `#`

[role="curriculum-javascript"]
في JavaScript، يشار إلى التعليقات بواسطة سطر يبدأ بخطين أمامين، `//`.

.تدريب
****
In your current script, write a comment with a description of your song on the first line.
****

يمكنك أيضًا استخدام الملاحظات لوصف ما تفعله الأقسام المختلفة من الكود. Here is an example below. فيما يلي مثال: يمكنك لصق الكود وتشغيله. لاحظ كيف تصف الملاحظات الفروع المختلفة:

[role="curriculum-python"]
[source,python]
----
include::code-examples/your-first-song-comments.py.txt[]
----

[role="curriculum-javascript"]
[source,javascript]
----
include::code-examples/your-first-song-comments.js.txt[]
----

{nbsp} +

[[uploadingsounds]]
=== تحميل الأصوات الخاصة بك

يمكنك تحميل الصوت الخاص بك من خلال متصفح الصوت. افتح متصفح الصوت الخاص بك وانقر على زر "إضافة صوت" أسفل الفلاتر (إذا لم يظهر الزر، تأكد من أنك مسجل الدخول)-- ستفتح نافذة، لنستكشف الخيارات الثلاثة الأولى:

You must be logged in to upload sounds.

Let's explore the first three options.

. *تحميل صوت جديد* يسمح لك باختيار ملفات صوتية (.mp3, .aiff, وما إلى ذلك) من جهاز الكمبيوتر الخاص بك.
. *Quick Record* lets you record directly from your computer's microphone.
. *Freesound* تسمح لك باستيراد الأصوات مباشرة من Freesound.org، قاعدة بيانات صوتية مفتوحة المصدر. في شريط البحث، يمكنك البحث عن نوع من الصوت المطلوب (على سبيل المثال: أغاني الطيور، الأمطار، الشارع المزدحم..). Then select the toggle button in front of the file name to select.

[role="curriculum-mp4"]
[[video101rec]]
video::./videoMedia/010-01-Recording&UploadingSounds-PY-JS.mp4[]

.تدريب
****
الموسيقى، والفن بشكل عام، غالباً ما تكون طريقة لنقل رسالة. ويمكن أن يكون إما من خلال كلمات الأغنية، و/أو من خلال نوع الأغنية. نود أن نصنع أغنية قصيرة تعبر عن شيء ما. يمكن أن يكون الشعور الذي ترغب'في مشاركته، أو قصة.

. فكر في ما ترغب'في التعبير عنه
. Then either:
.. ثم 1- إما أن تكتب بعض كلمات الأغنية وتسجل نفسك تغنيها أو تقرأها أو 2- تسجيل أو تحميل بعض الأصوات الموسيقية المرتبطة برسالتك
.. Record or download some sounds that are related to your message
. أضف هذه التسجيلات إلى أغنيتك باستخدام دالة fitMedia()
. ثم أضف بعض المقاطع الإضافية من EarSketch باستخدام دالة fitMedia()
. اعرض اغنيتك لصديق
. يمكنك مناقشة أغنيتك والأشياء التي كنت تحاول التعبير عنها
****

تقوم وحدة المعالجة' المركزية للحاسوب ، أو * وحدة المعالجة المركزية * بتنفيذها.

When you start a process, the computer code is first stored in the computer's *memory* for quick access. تحتفظ ذاكرة الحاسوب' * * بالبيانات وتعليمات المعالجة لاستخدام وحدة المعالجة المركزية. The CPU is often considered the "brain" of the computer.

الذاكرة ، وتسمى أيضًا التخزين الأساسي أو ذاكرة الوصول العشوائي (ذاكرة الوصول العشوائي) ، تخزن بياناتها مؤقتًا. It is designed to be fast and temporary, for active processes only.

هناك فرق بين الذاكرة (أو التخزين قصير المدى) والتخزين طويل المدى. يشار إلى التخزين طويل المدى ، مثل محرك الأقراص الثابتة أو السحابة(cloud) ، على أنه تخزين ثانوي. * التخزين الثانوي * يحتوي على كميات كبيرة من البيانات لفترات طويلة من الوقت ، حتى بعد إيقاف تشغيل الحاسوب. لا تتفاعل وحدة المعالجة المركزية-CPU-بشكل مباشر مع وحدات التخزين الثانوية. عندما تنفذ وحدة المعالجة المركزية CPU عملية ما ، يجب أولاً وضع البيانات من التخزين الثانوي في الذاكرة حتى تتمكن وحدة المعالجة المركزيةCPU من الوصول إليها بسرعة.

في بعض الأحيان ، تأتي البيانات الموجودة في الذاكرة لاستخدام وحدة المعالجة المركزيةCPU من جهاز إدخال بدلاً من التخزين الثانوي. * المدخلات * هي الإشارات أو البيانات التي يتلقاها الكمبيوتر ، مثل الصوت من الميكروفون. وبالمثل ، فإن مخرجات * * هي الإشارات أو البيانات المرسلة منه ، مثل الصوت عبر مكبر الصوت. الإدخال / الإخراج ، أو I / O ، هو كيفية تواصل الحاسوب مع العالم الخارجي ، بما في ذلك البشر!

دعونا 'نفحص تسجيل الصوت في EarSketch كمثال للعملية. أولاً ، نقوم بتسجيل البيانات في الحاسوب باستخدام جهاز الإدخال ، الميكروفون. تقوم وحدة المعالجة المركزيةCPU بتخزين تلك البيانات الصوتية في ذاكرتها. إذا قمت بالضغط على زر التشغيل لسماع التسجيل الخاص بك ، فإن وحدة المعالجة المركزيةCPU تصل إلى البيانات وترسلها إلى أحد المخرجات أو مكبرات الصوت أو سماعات الرأس. عندما تضغط على زر التحميل ، تقوم وحدة المعالجة المركزيةCPU بتشغيل عملية تقوم بتحويل البيانات الصوتية إلى تنسيق ملف صوتي قياسي (ملف WAV أو .wav) وترسله إلى خادم EarSketch. الخادم (The server) هو نظام خارجي يوفر خدمات لجميع مستخدمي EarSketch ، بما في ذلك جهاز الكمبيوتر الخاص بك. يحفظ خادم EarSketch ملف الصوت من الذاكرة إلى التخزين الثانوي للخوادم 'بحيث يمكنك الوصول إليه في المستقبل.

شاهد الشرح بالفيديو التالي:

[role="curriculum-mp4"]
[[video11cpu]]
video::./videoMedia/010-02-ProcessesandMemory-PY-JS.mp4[]

////
END OF OPTIONAL
////

[[copyright]]
=== استخدم حقوق النشر بحكمة

حقوق الطبع والنشر * هي جزء من القانون يغطي * الملكية الفكرية * ، أو ملكية العمل الإبداعي ، مثل الموسيقى. عند استخدام عينات (مقطوعات صغيرة من الموسيقى) أو إعادة مزج الموسيقى الموجودة ، فأنت بحاجة إلى منح الفضل للمؤلفين ، ويمكنك القيام بذلك في تعليقات التعليمات البرمجية الخاصة بك. قبل استخدام أصوات الموسيقيين الآخرين ومشاركة الموسيقى الخاصة بك ، تعرف على المزيد حول حقوق النشر!

عندما تنشئ شيئًا أصليًا وكبيرًا بدرجة كافية ، تحصل على حقوق الطبع والنشر تلقائيًا! في الولايات المتحدة ، هذا يعني أنه يمكنك: عمل نسخ وإجراء تعديلات ومشاركة ما تقوم بإنشائه.

هناك نوعان من حقوق الطبع والنشر للأغنية: حقوق الأغنية (للكاتب أو الملحن) وحقوق التسجيل الصوتي (غالبًا بواسطة شركة التسجيل). تذهب عائدات العروض العامة إلى كاتب الأغاني وتذهب معظم الارباح من مبيعات التسجيلات إلى شركة التسجيلات.

يعد * انتهاك حقوق الطبع والنشر * انتهاكًا لحقوق الطبع والنشر ، مثل تنزيل الموسيقى بشكل غير قانوني. في الولايات المتحدة ، يسمح * الاستخدام العادل * باستخدام المحتوى المحمي بحقوق الطبع والنشر في ظل ظروف معينة ، مثل الأغراض التعليمية أو الحرجة ، وإعادة استخدام كميات صغيرة فقط من العمل. يتم تحديد الاستخدام العادل لكل حالة من قبل الحكم على أساس كل حالة على حدة.

إلى جانب الاستخدام العادل ، هناك طريقة لاستخدام الموسيقى ومشاركتها بشكل مفتوح. يعمل EarSketch لأن الفنانين شاركوا أعمالهم معك من خلال * امثلة لعينات * (جزء صغير من التسجيل الصوتي) في مكتبة الأصوات.

Copyright is not all about getting people in trouble. If you upload a song to the internet, you might not mind if someone downloads it without asking; you want people to share your music! يجب أن تساعدنا حقوق الطبع والنشر في صنع ومشاركة المزيد من الفن ، وليس أقل. When you are creating songs in EarSketch, we want you to think less about _stealing_ and more about _sharing_. في EarSketch ، لديك إذن وصول مفتوح إلى هذه العينات ، وكل الموسيقى التي تنشئها في EarSketch قابلة للمشاركة ، على الرغم من أنه لا يمكنك بيعها. تعد مشاركة الموسيقى الخاصة بك أو السماح للطلاب الآخرين بإعادة مزج التعليمات البرمجية الخاصة بك طريقة لدفع هذا الأمر إلى الأمام والمساعدة في وضع فن جديد في العالم.

When using sounds in your EarSketch scripts, you'll need to be sure that you have permission from the copyright holder to use the sounds, or that you are using them in accordance with fair use.

For full details, refer to our https://earsketch.gatech.edu/landing/#/license[LICENSE^].

[[chapter2summary]]
=== ملخص الفصل 2

[role="curriculum-python"]
* * الإيقاع * هو السرعة التي يتم بها تشغيل مقطوعة موسيقية ، محددة بعدد الدقات في الدقيقة (دقة في الدقيقة). Tempo is tied to genre.
* يتم تنظيم المقاطع الموجودة في مكتبة اصوات EarSketch في مجلدات من الأصوات ذات الصلة. لمعرفة الإيقاع الدقيق للمقطع ، مرر مؤشر الماوس فوق الاسم في متصفح الصوت.
* التعليقات هي أسطر من التعليمات البرمجية لا يتم تنفيذها بواسطة الحاسوب. ومع ذلك ، فهي مفيدة لتدوين الملاحظات داخل البرنامج النصي.
* `من مستورد earsketch*` يضيف EarSketch API إلى مشروعك.
* `setTempo()`يتيح لك تحديد إيقاع أغنيتك. يجب تضمينه في كل برنامج نصي من EarSketch.
* يمكنك تحميل الأصوات الخاصة بك إلى EarSketch من خلال متصفح الصوت. فقط انقر فوق "إضافة صوت".
* العمليات * ، أو المهام ، هي برامج تعمل على جهاز الحاسوب الخاص بك. تتم المعالجة بواسطة جهاز الحاسوب' * وحدة المعالجة المركزية CPU * ، وهو المسؤول عن تنفيذ تعليمات البرنامج.
* * الذاكرة * (المعروفة أيضًا باسم ذاكرة الوصول العشوائي أو التخزين الأساسي) تحتفظ بالبيانات وتعليمات المعالجة مؤقتًا لاستخدام وحدة المعالجة المركزية.
* * التخزين الثانوي * يشير إلى التخزين طويل المدى للبيانات ، غالبًا بكميات كبيرة. يجب وضع البيانات من التخزين الثانوي في الذاكرة قبل أن تتمكن وحدة المعالجة المركزية CPU من الوصول إليها.
* * حقوق الطبع والنشر * هي جزء من القانون يغطي ملكية العمل الإبداعي ، مثل الموسيقى. إنه مهم للموسيقيين لأنه يحدد كيف يمكن استخدام عمل شخص آخر 'ومشاركته.
* إذا أنشأت عملاً موسيقيًا ملموسًا وجديدًا ، فلديك حقوق نشر تلقائية. بمعنى آخر ، لديك حقوق على العمل الذي قمت بإنشائه.
* * ترخيص * يمنح للآخرين الإذن باستخدام مقطوعة موسيقية.

[role="curriculum-javascript"]
* * الإيقاع * هو السرعة التي يتم بها تشغيل مقطوعة موسيقية ، محددة بعدد الدقات في الدقيقة (دقة في الدقيقة). Tempo is tied to genre.
* يتم تنظيم المقاطع الموجودة في مكتبة اصوات EarSketch في مجلدات من الأصوات ذات الصلة. لمعرفة الإيقاع الدقيق للمقطع ، مرر مؤشر الماوس فوق الاسم في متصفح الصوت.
* التعليقات هي أسطر من التعليمات البرمجية لا يتم تنفيذها بواسطة الحاسوب. ومع ذلك ، فهي مفيدة لتدوين الملاحظات داخل البرنامج النصي.
* `setTempo();`يتيح لك تحديد إيقاع أغنيتك. يجب تضمينه في كل برنامج نصي من EarSketch.
* يمكنك تحميل الأصوات الخاصة بك إلى EarSketch من خلال متصفح الصوت. فقط انقر فوق "إضافة صوت".
* العمليات * ، أو المهام ، هي برامج تعمل على جهاز الحاسوب الخاص بك. تتم المعالجة بواسطة جهاز الحاسوب' * وحدة المعالجة المركزية CPU * ، وهو المسؤول عن تنفيذ تعليمات البرنامج.
* * الذاكرة * (المعروفة أيضًا باسم ذاكرة الوصول العشوائي أو التخزين الأساسي) تحتفظ بالبيانات وتعليمات المعالجة مؤقتًا لاستخدام وحدة المعالجة المركزية.
* * التخزين الثانوي * يشير إلى التخزين طويل المدى للبيانات ، غالبًا بكميات كبيرة. يجب وضع البيانات من التخزين الثانوي في الذاكرة قبل أن تتمكن وحدة المعالجة المركزية CPU من الوصول إليها.
* * حقوق الطبع والنشر * هي جزء من القانون يغطي ملكية العمل الإبداعي ، مثل الموسيقى. إنه مهم للموسيقيين لأنه يحدد كيف يمكن استخدام عمل شخص آخر 'ومشاركته.
* إذا أنشأت عملاً موسيقيًا ملموسًا وجديدًا ، فلديك حقوق نشر تلقائية. بمعنى آخر ، لديك حقوق على العمل الذي قمت بإنشائه.
* * ترخيص * يمنح للآخرين الإذن باستخدام مقطوعة موسيقية.

[[chapter-questions]]
=== الأسئلة

[question]
--
ماذا تسمح لك `()setTempo` بفعله في EarSketch؟

[answers]
* Specify the tempo of a song
* أضف صوت إلى المسار
* Create a drum beat
* غيّر نوعية الصوت داخل المشروع
--

[question]
--
ما هي الوحدة للتمبو؟

[answers]
* بيتات لكل دقيقة (BPM)
* قياس
* Decibels(dB)
* ثوانٍ
--

[question]
--
What can you use comments for?

[answers]
* كل ما ورد اعلاه
* تنظيم التعليمات البرمجية/الكود الخاصة بك
* كتابة وصف للسكريبت في بداية السكريبت الخاص بك
* جعل التعليمات البرمجية (الكود) الخاصة بك سهلة القراءة للمبرمجين الآخرين
--

[question]
--
أي من التصريحات التالية صحيحة؟

[answers]
* القرص الصلب هو مثال للتخزين الثانوي
* يتم حفظ بيانات الصوت في وحدة المعالجة المركزية للكمبيوتر
* تحتوي وحدة المعالجة المركزية على بيانات تعليمية للبرامج
* بيانات المخازن الثانوية لفترات قصيرة
--

[question]
--
كيف تحصل على حقوق التأليف والنشر؟

[answers]
* عن طريق إنشاء ونشر أي عمل جديد
* عن طريق شراء براءة اختراع
* بالانضمام إلى منظمة سرية
* عن طريق اختيار ترخيص لعملك
--

[question]
--
What is a music license?

[answers]
* شارك هؤلاء الفنانون عيناتهم بموجب ترخيص * المشاع الإبداعي * ، والذي يمنح الإذن للآخرين لاستخدام أعمالهم.
* عملية التأليف
* A musical genre
* A description of your song
--