[[mixingwithconditionnals]]
== Mix with Conditionals!

:nofooter:

Il est possible d'automatiser beaucoup d'opérations grâce au codage. Un exemple d’automatisation consisterait à programmer un robot pour qu’il s’arrête à la détection d'un obstacle : le robot n’aura donc pas besoin d’un être humain pour le faire arrêter manuellement. Voyez ci-dessous un exemple d'instruction conditionnelle. Au lieu de cela, le robot aura un capteur pour détecter les obstacles, et s'il y en rencontre, il s'arrêtera. Il est possible de faire des automatisations musicales dans EarSketch, en utilisant des instructions conditionnelles (« if »). Nous allons maintenant voir comment automatiser le mixage des pistes. Le mixage signifie que si une piste est trop forte, nous réduirons son volume et si elle est trop faible, nous augmenterons son volume.

[[analyzetrack]]
=== Utilisation de la fonction `analyzeTrack()`

Nous allons maintenant voir comment détecter l'intensité sonore ou le volume d'une piste. Rappelez-vous la différence entre la hauteur (aiguë ou grave) et le volume (fort ou faible) d'un son. Nous utiliserons une fonction EarSketch nommée `analyzeTrack()`. Copiez et exécutez le code suivant :

[role="curriculum-python"]
[source,python]
----
include::code-examples/mixing-with-conditionals-analyzetrack.py.txt[]
----

[role="curriculum-javascript"]
[source,javascript]
----
include::code-examples/mixing-with-conditionals-analyzetrack.js.txt[]
----

Vous pouvez lire dans votre console que l'intensité sonore affichée est de 0.0967737948641.

* L'intensité sonore peut aller de 0 (silence) à 1 (intensité sonore maximale).
* Parfois, vous verrez un nombre comme ceci : 1.74630733714e-05. C'est ce qu'on appelle la notation scientifique. It means move the decimal to the left 5 places (replacing with 0 if needed). Ceci correspond à 0,0000174630733714.
* La plupart des sons auront une intensité sonore inférieure à 0.4.

La fonction `analyzeTrack()` prend 2 arguments :

. *track*: Track number
. *feature*: Analysis constant, like `RMS_AMPLITUDE`

.ENTRAÎNEZ-VOUS
****
. Vous pouvez essayer ce code avec différents sons (changez la variable "sound") pour découvrir ce que donnera la sortie.
. Ajoutez une seconde piste et utilisez la fonction `analyzeTrack()` pour afficher son volume dans la console. Lorsque vous exécutez le code, avant de regarder votre console, écoutez votre musique et essayez de deviner quelle piste est la plus forte.
****

Le paramètre de `analyzeTrack()` peut être soit `RMS_AMPLITUDE`, afin d'évaluer le volume, soit `SPECTRAL_CENTROID` pour analyser la hauteur du son. Nous allons nous concentrer sur l'analyse du volume dans ce chapitre.

[[booleansandcomparisons]]
=== Booléens et comparaisons

Nous allons maintenant voir comment fonctionne la *logique booléenne*. Cela nous aidera à automatiser certaines tâches.

[role="curriculum-python"]
Les *booléens* sont un type de données. Le type de données booléen peut prendre deux valeurs : `True` ou `False`. `True` et `False` commencent par une lettre majuscule et n'ont pas de guillemets.

[role="curriculum-javascript"]
Les *booléens* sont un type de données. Le type de données booléen peut prendre deux valeurs : `true` ou `false`. `true` et `false` commencent par une lettre minuscule et n'ont pas de guillemets.

[role="curriculum-python"]
--
Pour créer un booléen, vous pouvez soit initialiser une variable (`variable1 = True`), soit utiliser une comparaison. Pour faire une comparaison, nous utilisons un *opérateur de comparaison*. Voici les opérateurs de comparaison :

[cols="^h,1"]
|===
|==
|est identique à

|!=
|n'est pas identique à

|>
|supérieur à

|>=
|supérieur ou égal à

|<
|inférieur à

|\<=
|inférieur ou égal à
|===

Notez la différence entre :

1. comparer deux valeurs pour voir si elles sont identiques : `==`
1. l'affectation d'une valeur à une variable `=`
--

[role="curriculum-javascript"]
--
Pour créer un booléen, vous pouvez soit initialiser une variable (`variable1 = true;`), soit utiliser une comparaison. Pour faire une comparaison, nous utilisons un *opérateur de comparaison*. Voici les opérateurs de comparaison :

[cols="^h,1"]
|===
|===
|est identique à

|!==
|n'est pas identique à

|>
|supérieur à

|>=
|supérieur ou égal à

|<
|inférieur à

|\<=
|inférieur ou égal à
|===

Notez la différence entre :

1. comparer deux valeurs pour voir si elles sont identiques : `===`
1. l'affectation d'une valeur à une variable `=`
--

[role="curriculum-python curriculum-mp4"]
[[video17apy]]
video::./videoMedia/6_2_1_boolean_py.mp4[]

[role="curriculum-javascript curriculum-mp4"]
[[video17ajs]]
video::./videoMedia/6_2_1_boolean_js.mp4[]

// this video will be cut at 2' to delete the section about boolean operators//

[role="curriculum-python"]
.ENTRAÎNEZ-VOUS
****
* Créez un nouveau script et ajouter des sons sur deux pistes.
* Imprimez dans la console `True` si la première piste est plus forte que la seconde piste et `False` sinon.
* Utilisez une boucle « for » avec le compteur `track` pour vérifier si l'intensité sonore est strictement supérieure à 0.01 pour chaque piste. Si c'est le cas, affichez `True`, sinon, imprimez dans la console `False` pour chaque piste.
* Vous pouvez utiliser des instructions d'affichage supplémentaires avant d'afficher `True` ou `False`, afin que vous puissiez savoir ce qui est `True` ou `False` lorsque vous lirez la console. For example, you can first print the track number and then 'True' or 'False'.
****

[role="curriculum-javascript"]
.ENTRAÎNEZ-VOUS
****
* Créez un nouveau script et ajouter des sons sur deux pistes.
* Imprimez dans la console `true` si la première piste est plus forte que la seconde piste et `false` sinon.
* Utilisez une boucle « for » avec le compteur `track` pour vérifier si l'intensité sonore est strictement supérieure à 0.01 pour chaque piste. Si c'est le cas, affichez `true`, sinon, imprimez `false` dans la console pour chaque piste.
* Vous pouvez utiliser des instructions d'affichage supplémentaires avant d'afficher `true` ou `false`, afin que vous puissiez savoir ce qui est `true` ou `false` lorsque vous lirez la console. For example, you can first print the track number and then 'true' or 'false'.
****

Voici un exemple :

[role="curriculum-python"]
[source,python]
----
include::code-examples/mixing-with-conditionals-boolean-example.py.txt[]
----

[role="curriculum-javascript"]
[source,javascript]
----
include::code-examples/mixing-with-conditionals-boolean-example.js.txt[]
----

[role="curriculum-python"]
Remarque : dans cet exemple, nous avons utilisé des instructions d'affichage avec des chaînes de caractères pour aider à lire le contenu de la console. Nous avons utilisé l'opérateur `+` pour *concaténer* (coller ensemble) des chaînes et la fonction str() pour convertir des nombres en chaînes de caractères.

[role="curriculum-javascript"]
Remarque : dans cet exemple, nous avons utilisé des instructions d'affichage avec des chaînes de caractères pour aider à lire le contenu de la console. Nous avons utilisé l'opérateur `+` pour *concaténer* (coller ensemble) des chaînes de caractères.

[[conditionalstatements]]
=== Instructions conditionnelles

Qu'est-ce qu'une instruction conditionnelle ? Une *instruction* correspond à une commande pour l'ordinateur. Une *instruction conditionnelle* est une instruction qui ne doit être exécutée que si une certaine *condition* est remplie (vraie). Par exemple, si vous programmez un robot pour qu'il s'arrête devant un obstacle, la condition sera "Y a-t-il un obstacle ?". Si oui, il doit s'arrêter. Si non, ne faites rien (continuez).

Notez la similitude avec une boucle « for » :

[role="curriculum-python"]
[source,python]
----
include::code-examples/mixing-with-conditionals-untitled1.py.txt[]
----

[role="curriculum-javascript"]
[source,javascript]
----
include::code-examples/mixing-with-conditionals-untitled1.js.txt[]
----

.ENTRAÎNEZ-VOUS
****
* Créez un nouveau script avec deux pistes.
* Si la première piste est plus forte que la deuxième, réduisez alors son volume. Vous aurez besoin des fonctions `analyzeTrack()` et `setEffect()`, en plus d'une instruction « if ».
* Vous aurez besoin d'un gain négatif (entre -1 et -60dB) pour réduire le volume.
****

Voici un exemple :

[role="curriculum-python"]
[source,python]
----
include::code-examples/mixing-with-conditionals-automatic-mixing-1.py.txt[]
----

[role="curriculum-javascript"]
[source,javascript]
----
include::code-examples/mixing-with-conditionals-automatic-mixing-1.js.txt[]
----

Il est possible de vérifier plusieurs conditions et d'exécuter des instructions différente selon chaque condition. You can chain multiple conditions together. Nous utiliserons la syntaxe suivante :

[role="curriculum-python"]
[source,python]
----
include::code-examples/mixing-with-conditionals-untitled2.py.txt[]
----

[role="curriculum-javascript"]
[source,javascript]
----
include::code-examples/mixing-with-conditionals-untitled2.js.txt[]
----

[[mixingyourtracks]]
=== Mixer vos pistes

Utilisons maintenant tous ces outils pour mixer votre chanson. Le mixage modifie le volume des pistes pour qu'elles soient bien équilibrées.

[role="curriculum-python"]
.ENTRAÎNEZ-VOUS
****
* Créez un nouveau script.
* Ajoutez des sons, au moins trois pistes, pour un minimum de 16 mesures.
* Vous pouvez utiliser la fonction `makeBeat()` et une boucle « for » pour ajouter des percussions.
* Choisissez votre piste « principale ». Il peut s'agir de votre mélodie ou d'une piste que vous souhaitez mettre en évidence.
* Si votre piste principale n'est pas plus forte que les autres pistes, assurez-vous d'augmenter son volume à l'aide de la fonction `setEffect()`. Ne prenez pas en compte la piste percussive, car la fonction `analyzeTrack()` n'est pas pertinente pour les percussions. Pour le volume, il s'agit de : `RMS_AMPLITUDE`.
* Utilisez des impressions dans la console pour montrer votre processus dans la console. Voici un exemple d'instruction d'impression : `print('Est-ce que le numéro de piste' + str(track) + 'est plus élevé que 0.01 ?')`, si le compteur `track` est égal à `1`, cela affichera 'Est-ce que le numéro de piste 1 est plus élevé que 0.01 ?". La fonction `str()` permet de convertir un nombre (p. ex.
****

[role="curriculum-javascript"]
.ENTRAÎNEZ-VOUS
****
* Créez un nouveau script.
* Ajoutez des sons, au moins trois pistes, pour un minimum de 16 mesures.
* Vous pouvez utiliser la fonction `makeBeat()` et une boucle « for » pour ajouter des percussions.
* Choisissez votre piste « principale ». Il peut s'agir de votre mélodie ou de la piste que vous souhaitez mettre en évidence.
* Si votre piste principale n'est pas plus forte que les autres pistes, assurez-vous d'augmenter son volume à l'aide de la fonction `setEffect()`. Ne prenez pas en compte la piste percussive, car la fonction `analyzeTrack()` n'est pas pertinente pour les percussions. Pour le volume, il s'agit de : `RMS_AMPLITUDE`.
* Utilisez des impressions dans la console pour montrer votre processus dans la console. Voici un exemple d'instruction d'impression : `println('Est-ce que le numéro de piste' + track + 'est plus élevé que 0.01 ?')`, si le compteur `track` est égal à `1`, cela affichera 'Est-ce que le numéro de piste 1 est plus élevé que 0.01 ?".
****

Revoyons un peu de vocabulaire :
1.

1. *Opérateur*: un caractère qui représente une action. Nous avons vu des caractctères aritmétiques (`+`, `-`, `\*`, `=`) and des caractères de comparaison (`>`, `>=`, `<`, `\<=`, `==`, `!=`).
1. *Expression*: une combinaison de valeurs, constantes, variables, opérateurs et fonctions. L'ordinateure évalue les expressions pour en créer un résultat, souvent un nombre ou un booléen.  Par exemple : `1+2` (qui sera évalué à 3) ou `1<2` (qui sera évalué à True) ou `analyzeTrack(1,RMS_AMPLITUDE)` (qui sera évalué au volume de la piste 1, un nombre entre 0 et 1).
1. *Instructions*: instructions que l'ordinateur doit exécuter.

Ci-dessous vous verrez un exemple de mix automatisé. Dans ce cas, le mix est automatisé, car si vous changez un ou plusieurs sons, vous n'aurez pas besoin de vérifier leur volume ni de modifier le volume de la piste, car cela est déjà prévu par le code.

[role="curriculum-python"]
[source,python]
----
include::code-examples/mixing-with-conditionals-automatic-mixing-2.py.txt[]
----

[role="curriculum-javascript"]
[source,javascript]
----
include::code-examples/mixing-with-conditionals-automatic-mixing-2.js.txt[]
----

{nbsp} +

[[chapter6summary]]
=== Résumé du chapitre 6

[role="curriculum-python"]
* La fonction `analyzeTrack()` prend deux arguments :
le numéro de piste et un paramètre. Lorsque le paramètre est `RMS_AMPLITUDE`, la fonction renvoie l'intensité sonore de la piste (un nombre compris entre 0 et 1). Lorsque le paramètre est `SPECTRAL_CENTROID`, la fonction renvoie la hauteur ou brillance de la piste.
* Le type de données *booléen* peut seulement prendre deux valeurs : `True` ou `False`.
* Les booléens sont générés soit directement en créant une variable égale à `True` ou `False`, soit par des opérateurs de comparaison : `==`, `!=`, `>`, `>=`, `<`, `\<=`.
* `==` évalue si deux valeurs sont égales, alors que `=` affecte une valeur à une variable.
* Un *opérateur * est un caractère qui représente une action.
* Les *expressions* sont évaluées par l'ordinateur pour produire une valeur.
* Une *instruction* correspond à une commande pour l'ordinateur.
* Une *condition* est une expression qui peut être évaluée `True` (vraie) ou `False` (fausse).
* L'instruction _if_ n'exécute son bloc de code que lorsque sa condition est `True` (vraie).
* Dans le cas où une condition _if_ est `False`, une instruction facultative _else_ permet l'exécution d'un bloc de code alternatif.

[role="curriculum-javascript"]
* La fonction `analyzeTrack()` prend deux arguments :
le numéro de piste et un paramètre. Lorsque le paramètre est `RMS_AMPLITUDE`, la fonction renvoie l'intensité sonore de la piste (un nombre compris entre 0 et 1). Lorsque le paramètre est `SPECTRAL_CENTROID`, la fonction renvoie la hauteur ou brillance de la piste.
* Le type de données *booléen* peut valoir seulement deux valeurs : `true` ou `false`.
* Les booléens sont générés soit directement en créant une variable égale à `true` ou `false`, soit par des opérateurs de comparaison : `===`, `!==`, `>`, `>=`, `<`, `\<=`.
* `===` évalue si deux valeurs sont égales, alors que `=` affecte une valeur à une variable.
* Un *opérateur * est un caractère qui représente une action.
* Les *expressions* sont évaluées par l'ordinateur pour produire une valeur.
* Une *instruction* correspond à une commande pour l'ordinateur.
* Une *condition* est une expression qui peut être évaluée `true` (vraie) ou `false` (fausse).
* L'instruction _if_ n'exécute son bloc de code que lorsque sa condition est `true` (vraie).
* Dans le cas où une condition _if_ est `false`, une instruction facultative _else_ permet l'exécution d'un bloc de code alternatif.

[[chapter-questions]]
=== Questions

[question]
--
Parmi les éléments suivants, lesquels sont des booléens ?

[answers]
* `5+4 == 5`
* `measure = 1`
* `2<3<4`
* `False()`
--

[role="curriculum-python"]
[question]
--
Quelle serait la valeur de retour du bloc de code suivant (qu'est-ce qui s'afficherait dans la console) ?

[source,python]
----
include::code-examples/mixing-with-conditionals-untitled3.py.txt[]
----

[answers]
* 10
* 5
* True
* False
--

[role="curriculum-javascript"]
[question]
--
Quelle serait la valeur de retour du bloc de code suivant (qu'est-ce qui s'afficherait dans la console) ?

[source,javascript]
----
include::code-examples/mixing-with-conditionals-untitled3.js.txt[]
----

[answers]
* 10
* 5
* True
* False
--

[question]
--
Qu'est-ce que le mixage ?

[answers]
* Adapter le volume de chaque piste pour qu'elles paraissent bien équilibrées
* Adapter la hauteur de chaque piste pour qu'elles paraissent bien équilibrées
* L'ajout d'un fondu d'ouverture
* L'ajout d'un fondu de fermeture
--

[question]
--
Combien de conditions pouvez-vous vérifier avec une instruction conditionnelle ?

[answers]
* n'importe quel nombre
* 1 condition
* 2 conditions
* 3 conditions
--