[[mixingwithconditionnals]]
== Mixer à l'aide d'instructions conditionnelles
:nofooter:

Il est possible d'automatiser beaucoup d'opérations grâce au codage. Un exemple d’automatisation consisterait à programmer un robot pour qu’il s’arrête à la détection d'un obstacle : le robot n’aura donc pas besoin d’un être humain pour le faire arrêter manuellement. Au lieu de cela, le robot aura un capteur pour détecter les obstacles, et s'il y en rencontre, il s'arrêtera. Il est possible de faire des automatisations musicales dans EarSketch, en utilisant des instructions conditionnelles (« if »). Nous allons maintenant voir comment automatiser le mixage des pistes. Le mixage signifie que si une piste est trop forte, nous réduirons son volume et si elle est trop faible, nous augmenterons son volume.


[[analyzetrack]]
=== Utilisation de la fonction `analyzeTrack()`

Nous allons maintenant voir comment détecter l'intensité sonore ou le volume d'une piste. Assurez-vous de bien comprendre la différence entre la hauteur (aiguë ou grave) et le volume (fort ou faible) d'un son. Nous utiliserons une fonction EarSketch nommée `analyzeTrack()`. Copiez et exécutez le code suivant :

[role="curriculum-python"]
[source,python]
----
# python code
#
# script_name: the analyzeTrack() function
#
# author: The EarSketch Team
#
# description: using the analyzeTrack() function to print the loudness of a track
#
# Setup
from earsketch import *
init()
setTempo(120)
 
# Placing a sound on track 1
sound = COMMON_LOVE_VOX_COMMON_1
fitMedia(sound,1,1,9)
 
# Creating a variable to store the loudness of track 1
loudness1 = analyzeTrack(1,RMS_AMPLITUDE)
 
# Showing the loudness in the console
print(loudness1)
 
# Finish
finish()
----

[role="curriculum-javascript"]
[source,javascript]
----
// javascript code
//
// script_name: the analyzeTrack() function
//
// author: The EarSketch Team
//
// description: using the analyzeTrack() function to print the loudness of a track
//
// Setup
init();
setTempo(120);
 
// Placing a sound on track 1
sound = COMMON_LOVE_VOX_COMMON_1;
fitMedia(sound,1,1,9);
 
// Creating a variable to store the loudness of track 1
loudness1 = analyzeTrack(1,RMS_AMPLITUDE);
 
// Showing the loudness in the console
println(loudness1);
 
// Finish
finish();
----


Vous pouvez lire dans votre console que l'intensité sonore affichée est de 0.0967737948641.

* L'intensité sonore peut aller de 0 (silence) à 1 (intensité sonore maximale). 
* Parfois, vous verrez un nombre comme ceci : 1.74630733714e-05. C'est ce qu'on appelle la notation scientifique. Vous voyez le e-05 à la fin ? Cela signifie écrire cinq zéros avant le nombre 17... Ceci correspond à 0,0000174630733714. 
* La plupart des sons auront une intensité sonore inférieure à 0.4. 

The `analyzeTrack()` function takes 2 arguments:
* the track number,
* the parameter we want to analyze. Pour le volume, il s'agit de : `RMS_AMPLITUDE`.

.ENTRAÎNEZ-VOUS
****
. Vous pouvez essayer ce code avec différents sons (changez la variable "sound") pour découvrir ce que donnera la sortie.
. Ajoutez une seconde piste et utilisez la fonction `analyzeTrack()` pour afficher son intensité sonore dans la console. Lorsque vous exécutez le code, avant de regarder votre console, écoutez votre musique et essayez de deviner quelle piste est la plus forte.
****

Le paramètre de `analyzeTrack()` peut être soit `RMS_AMPLITUDE`, afin d'évaluer l'intensité sonore, soit `SPECTRAL_CENTROID` pour analyser la hauteur du son. Nous allons nous concentrer sur l'analyse de l'intensité sonore dans ce chapitre.

[[booleansandcomparisons]]
=== Booléens et comparaisons

Nous allons maintenant voir comment fonctionne la *logique booléenne*. Cela nous aidera à automatiser certaines tâches.

[role="curriculum-python"]
Les *booléens* sont un type de données. Le type de données booléen peut prendre deux valeurs : `True` ou `False`. `True` et `False` commencent par une lettre majuscule et n'ont pas de guillemets.

[role="curriculum-javascript"]
Les *booléens* sont un type de données. Le type de données booléen peut prendre deux valeurs : `true` ou `false`. `true` et `false` commencent par une lettre minuscule et n'ont pas de guillemets.

[role="curriculum-python"]
--
Pour créer un booléen, vous pouvez soit initialiser une variable (`variable1 = True`), soit utiliser une comparaison. Pour faire une comparaison, nous utilisons un *opérateur de comparaison*. Voici les opérateurs de comparaison :
[cols="^h,1"]
|===
|==
| est identique à
|!=
|n'est pas identique à
|>
|est supérieur à
|>=
|est supérieur ou égal à
|<
|est inférieur à
|\<=
|est inférieur ou égal à
|===
--

[role="curriculum-javascript"]
--
Pour créer un booléen, vous pouvez soit initialiser une variable (`variable1 = true;`), soit utiliser une comparaison. Pour faire une comparaison, nous utilisons un *opérateur de comparaison*. Voici les opérateurs de comparaison :
[cols="^h,1"]
|===
| ==
| est identique à
|!=
|n'est pas identique à
|>
|supérieur à
|>=
|supérieur ou égal à
|<
|inférieur à
|\<=
|inférieur ou égal à
|===
--

Notez la différence entre :
1. Comparer deux valeurs pour vérifier si elles sont identiques avec `==`
2. Affecter une valeur à une variable grâce à `=`

[role="curriculum-python curriculum-mp4"]
[[video17apy]]
video::./videoMedia/Screencast-Ch17-2-PY.mp4[]

[role="curriculum-javascript curriculum-mp4"]
[[video17ajs]]
video::./videoMedia/Screencast-Ch17-2-JS.mp4[]

// this video will be cut at 2' to delete the section about boolean operators//


[role="curriculum-python"]
.ENTRAÎNEZ-VOUS
****
* Créez un nouveau script et ajouter des sons sur deux pistes.
* Imprimez dans la console `True` si la première piste est plus forte que la seconde piste et `False` sinon.
* Utilisez une boucle « for » avec le compteur `track` pour vérifier si l'intensité sonore est strictement supérieure à 0.01 pour chaque piste. Si c'est le cas, affichez `True`, sinon, imprimez dans la console `False`.
* Vous pouvez utiliser des instructions d'affichage supplémentaires avant d'afficher `True` ou `False`, afin que vous puissiez savoir ce qui est `True` ou `False` lorsque vous lirez la console.
****

[role="curriculum-javascript"]
.ENTRAÎNEZ-VOUS
****
* Créez un nouveau script et ajouter des sons sur deux pistes.
* Imprimez dans la console `true` si la première piste est plus forte que la seconde piste et `false` sinon.
* Utilisez une boucle « for » avec le compteur `track` pour vérifier si l'intensité sonore est strictement supérieure à 0.01 pour chaque piste. Si c'est le cas, affichez `true`, sinon, imprimez `false` dans la console.
* Vous pouvez utiliser des instructions d'affichage supplémentaires avant d'afficher `true` ou `false`, afin que vous puissiez savoir ce qui est `true` ou `false` lorsque vous lirez la console.
****

Voici un exemple :

[role="curriculum-python"]
[source, python]
----
#        python code
#        script_name: Boolean Example
#
#        author: The EarSketch Team
#        description: We analyze the loudness of our tracks
#

# Setup
from earsketch import *
init()
setTempo(120)

# Creating 2 tracks
melody1 = RD_CINEMATIC_SCORE_STRINGS_14
melody2 = RD_UK_HOUSE__5THCHORD_1
fitMedia(melody1,1,1,9)
fitMedia(melody2,2,1,9)

# Evaluating the loudness of the tracks
loudnessTrack1 = analyzeTrack(1,RMS_AMPLITUDE)
loudnessTrack2 = analyzeTrack(2,RMS_AMPLITUDE)

# Checking if track 1 is louder than track 2
# We create the boolean comparison1
comparison1 = (loudnessTrack1 > loudnessTrack2)
print('Is Track 1 louder than track 2?')
print(comparison1)

# Creating a for loop to compare each track's loudness to 0.5
for track in range(1,3) :
  loudness = analyzeTrack(track,RMS_AMPLITUDE)
  print('Is track number ' + str(track) + ' greater than 0.01?')
  print(loudness > 0.01)

# Finish
finish()
----

[role="curriculum-javascript"]
[source, javascript]
----
// javascript code
//
// script_name: Simple Boolean Example
//
// author: The EarSketch Team
//
// description: We analyze the loudness of our tracks
//
//
// Setup
init();
setTempo(120);

// Creating 2 tracks
var melody1 = RD_CINEMATIC_SCORE_STRINGS_14;
var melody2 = RD_UK_HOUSE__5THCHORD_1;
fitMedia(melody1,1,1,9);
fitMedia(melody2,2,1,9);

// Evaluating the loudness of the tracks
var loudnessTrack1 = analyzeTrack(1,RMS_AMPLITUDE);
var loudnessTrack2 = analyzeTrack(2,RMS_AMPLITUDE);

// Checking if track 1 is louder than track 2
// We create the boolean comparison1
var comparison1 = (loudnessTrack1 > loudnessTrack2);
println('Is Track 1 louder than track 2?');
println(comparison1);

// Creating a for loop to compare each track's loudness to 0.5
for (var track = 1; track < 3; track++) {
  var loudness = analyzeTrack(track,RMS_AMPLITUDE);
  println ('Is track number ' + track + ' greater than 0.01?');
  println (loudness > 0.01);
}

//Finish
finish();

----

[role="curriculum-python"]
Remarque : dans cet exemple, nous avons utilisé des instructions d'affichage avec des chaînes de caractères pour aider à lire le contenu de la console. Nous avons utilisé l'opérateur `+` pour *concaténer* ou ajouter des chaînes et la fonction str() pour convertir des nombres en chaînes de caractères.

[role="curriculum-javascript"]
Remarque : dans cet exemple, nous avons utilisé des instructions d'affichage avec des chaînes de caractères pour aider à lire le contenu de la console. Nous avons utilisé l'opérateur `+` pour *concaténer* (coller ensemble) des chaînes de caractères.

[[conditionalstatements]]
=== Instructions conditionnelles

Qu'est-ce qu'une instruction conditionnelle ? Une *instruction* correspond à une commande pour l'ordinateur. Une *instruction conditionnelle* est une instruction qui ne doit être exécutée que si une certaine *condition* est remplie (vraie). Par exemple, si vous programmez un robot pour qu'il s'arrête devant un obstacle, la condition sera "Y a-t-il un obstacle ?". Si oui, il doit s'arrêter. Si non, ne faites rien (continuez).

Voyez ci-dessous un exemple d'instruction conditionnelle. Notez la similitude avec une boucle « for » :

[role="curriculum-python"]
[source, python]
----
if (condition):
    # Here write the instructions the computer needs to execute if the condition evaluates to True
    # Note that the instructions are indented, just like in for loops
----

[role="curriculum-javascript"]
[source, javascript]
----
if (condition){
    // Here write the instructions the computer needs to execute if the condition evaluates to true
    // Note that the instructions are indented, just like in for loops
}
----

.ENTRAÎNEZ-VOUS
****
* Créez un nouveau script avec deux pistes.
* Si la première piste est plus forte que la deuxième, réduisez alors son volume. Vous aurez besoin des fonctions `analyzeTrack()` et `setEffect()`, en plus d'une instruction « if ».
* Vous aurez besoin d'un gain négatif (entre -1 et -60dB) pour réduire le volume. 
****

Voici un exemple :
[role="curriculum-python"]
[source, python]
----
# python code
#
# script_name: Remixing 1
#
# author: The EarSketch Team
#
# description: If track 1 is louder than track 2, we'll reduce its volume
#
# Setup
from earsketch import *
init()
setTempo(120)

# Creating 2 tracks
melody1 = RD_CINEMATIC_SCORE_STRINGS_14
melody2 = RD_UK_HOUSE__5THCHORD_1
fitMedia(melody1,1,1,9)
fitMedia(melody2,2,1,9)

# Evaluating the loudness of the tracks
loudnessTrack1 = analyzeTrack(1,RMS_AMPLITUDE)
loudnessTrack2 = analyzeTrack(2,RMS_AMPLITUDE)

# If track 1 is louder than track 2, we reduce its volume
if (loudnessTrack1 > loudnessTrack2):
	setEffect(1,VOLUME,GAIN,-10)

# Finish
finish()
----

[role="curriculum-javascript"]
[source, javascript]
----
// javascript code
//
// script_name: Remixing 1
//
// author: The EarSketch Team
//
// description: If track 1 is louder than track 2, we'll reduce its volume

// Setup
init();
setTempo(120);

// Creating 2 tracks
var melody1 = RD_CINEMATIC_SCORE_STRINGS_14;
var melody2 = RD_UK_HOUSE__5THCHORD_1;
fitMedia(melody1,1,1,9);
fitMedia(melody2,2,1,9);

// Evaluating the loudness of the tracks
var loudnessTrack1 = analyzeTrack(1,RMS_AMPLITUDE);
var loudnessTrack2 = analyzeTrack(2,RMS_AMPLITUDE);

// If track 1 is louder than track 2, we reduce its volume
if (loudnessTrack1 > loudnessTrack2){
	setEffect(1,VOLUME,GAIN,-10);
}

//Finish
finish();
----
Il est possible de vérifier plusieurs conditions et d'exécuter des instructions différente selon chaque condition. Vous pouvez ajouter autant de conditions que vous le souhaitez. Nous utiliserons la syntaxe suivante :

[role="curriculum-python"]
[source, python]
----
if (condition1):
    # Here write the instructions the computer needs to execute if the condition1 evaluates to True. If it's False, move to the next line
elif (condition2):
	# Here write the instructions if condition2 is True. If condition2 is False, move to the next line
elif (condition3):
	# Here write the instructions if condition3 is True. If condition3 is False, move to the next line
else:
	# Here write the instructions in case all 3 conditions are False
----

[role="curriculum-javascript"]
[source, javascript]
----
if (condition1) {
    // Here write the instructions the computer needs to execute if the condition1 evaluates to true
} else if (condition2) {
	// Here write the instructions if condition2 is True. If condition2 is False, move to the next line
	// elif is short for else if
} else if (condition3) {
	// Here write the instructions if condition3 is True. If condition3 is False, move to the next line  
} else {
	// Here write the instructions in case all 3 conditions are False
}
----

[[mixingyourtracks]]
=== Mixer vos pistes

Utilisons maintenant tous ces outils pour mixer votre chanson. Le mixage modifie le volume des pistes pour qu'elles soient bien équilibrées. 

[role="curriculum-python"]
.ENTRAÎNEZ-VOUS
****
* Créez un nouveau script.
* Ajoutez des sons, au moins trois pistes, pour un minimum de 16 mesures.
* Vous pouvez utiliser la fonction `makeBeat()` et une boucle « for » pour ajouter des percussions.
* Choisissez votre piste « principale ». Il peut s'agir de votre mélodie ou d'une piste que vous souhaitez mettre en évidence.
* Si votre piste principale n'est pas plus forte que les autres pistes, assurez-vous d'augmenter son volume à l'aide de la fonction `setEffect()`. Ne prenez pas en compte la piste percussive, car la fonction `analyzeTrack()` n'est pas pertinente pour les percussions. `analyzeTrack()` renvoie une moyenne alors que les percussions sont des rafales de son, donc une moyenne n'évalue pas vraiment l'intensité sonore.
* Utilisez des impressions dans la console pour montrer votre processus dans la console. Voici un exemple d'instruction d'impression : `print('Est-ce que le numéro de piste' + str(track) + 'est plus élevé que 0.01 ?')`, si le compteur `track` est égal à `1`, cela affichera 'Est-ce que le numéro de piste 1 est plus élevé que 0.01 ?". La fonction `str()` permet de convertir un nombre (p. ex. : 1) en une chaîne de caractères (p. ex. : '1').
****

[role="curriculum-javascript"]
.ENTRAÎNEZ-VOUS
****
* Créez un nouveau script.
* Ajoutez des sons, au moins trois pistes, pour un minimum de 16 mesures.
* Vous pouvez utiliser la fonction `makeBeat()` et une boucle « for » pour ajouter des percussions.
* Choisissez votre piste « principale ». Il peut s'agir de votre mélodie ou de la piste que vous souhaitez mettre en évidence.
* Si votre piste principale n'est pas plus forte que les autres pistes, assurez-vous d'augmenter son volume à l'aide de la fonction `setEffect()`. Ne prenez pas en compte la piste percussive, car la fonction `analyzeTrack()` n'est pas pertinente pour les percussions.
* Utilisez des impressions dans la console pour montrer votre processus dans la console. Voici un exemple d'instruction d'impression : `println('Est-ce que le numéro de piste' + track + 'est plus élevé que 0.01 ?')`, si le compteur `track` est égal à `1`, cela affichera 'Est-ce que le numéro de piste 1 est plus élevé que 0.01 ?".
****

Voyons un peu de vocabulaire :
1.  Un *opérateur* est un caractère qui représente une action. Nous avons vu des opérateurs arithmétiques (`+`, `-`, `\*`, `=`) et des opérateurs de comparaison (`>`, `>=`, `<`, `\<=`, `==`, `!=`).
* Une *expression* est une combinaison de valeurs, constantes, variables, opérateurs et fonctions. L'ordinateur évalue les expressions pour produire une autre valeur, généralement une valeur numérique ou booléenne unique. Par exemple : `1+2` (évaluée à 3) ou `1<2` (évaluée à True) ou `analyzeTrack(1,RMS_AMPLITUDE)` (évaluée au volume de la piste 1, un nombre décimal entre 0 et 1).
* *Instructions* : des commandes que l'ordinateur exécute.


Voici un exemple de mixage automatisé. Nous dirons que c'est automatisé, car si vous modifiez un ou plusieurs sons, vous n'aurez pas à vérifier l'intensité sonore et à modifier le volume en conséquence vous-même, puisque ce sera déjà inclus dans le code.

[role="curriculum-python"]
[source, python]
----
#		python code
#		script_name: Mixing
#
#		author: the EarSketch team
#		description: Creating a short song and using conditional statements to mix the tracks
#
# Setup
from earsketch import *
init()
setTempo(120)

# Adding a melody and bass
melody1 = YG_ALT_POP_GUITAR_3
melody2 = YG_ALT_POP_GUITAR_1
bass1 = YG_ALT_POP_BASS_1
bass2 = DUBSTEP_SUBBASS_008
strings = YG_HIP_HOP_STRINGS_4
fitMedia(melody1,1,1,9)
fitMedia(melody2,1,9,17)
fitMedia(bass1,2,1,9)
fitMedia(bass2,2,9,17)
fitMedia(strings,3,9,17)

# Adding percussions using makeBeat()
beatKick = '0---0-----0-0---'
beatSnare = '--0-0------000-'
soundKick = OS_KICK02
soundSnare = OS_SNARE06
for measure in range(5,17):
  makeBeat(soundKick,4,measure,beatKick)
  makeBeat(soundSnare,5,measure,beatSnare)

# Mixing my tracks
# First, we analyze the tracks for loudness
loudnessTrack1 = analyzeTrack(1,RMS_AMPLITUDE)
print('The loudness of track 1 is'+str(loudnessTrack1))
loudnessTrack2 = analyzeTrack(2,RMS_AMPLITUDE)
print('The loudness of track 2 is'+str(loudnessTrack2))
loudnessTrack3 = analyzeTrack(3,RMS_AMPLITUDE)
print('The loudness of track 3 is'+str(loudnessTrack3))

if (loudnessTrack1 < loudnessTrack2):
  #if track 1 is quieter than track 2 then we increase the volume of track 1
  setEffect(1,VOLUME,GAIN,+5)
  print ('track 1 was quieter than track 2')
elif (loudnessTrack1 < loudnessTrack3):
  #if track 1 is louder than track 2 but quieter than track 3, we increase the volume of track 1
  setEffect(1,VOLUME,GAIN,+5)
  print ('track 1 was quieter than track 3')
else: 
  #if track 1 is louder than tracks 2 and 3, then we change nothing
  print('track 1 was the loudest track already')


# Finish
finish()
----

[role="curriculum-javascript"]
[source, javascript]
----
"use strict";

//		javascript code
//		script_name: Mixing
//
//		author: Te EarSketch team
//		description: Creating a short song and using conditional statements to mix the tracks
//

// Setup
init();
setTempo(120);

// Adding a melody and bass
var melody1 = YG_ALT_POP_GUITAR_3;
var melody2 = YG_ALT_POP_GUITAR_1;
var bass1 = YG_ALT_POP_BASS_1;
var bass2 = DUBSTEP_SUBBASS_008;
var strings = YG_HIP_HOP_STRINGS_4;
fitMedia(melody1,1,1,9);
fitMedia(melody2,1,9,17);
fitMedia(bass1,2,1,9);
fitMedia(bass2,2,9,17);
fitMedia(strings,3,9,17);

// Adding percussions using makeBeat()
var beatKick = '0---0-----0-0---';
var beatSnare = '--0-0------000-';
var soundKick = OS_KICK02;
var soundSnare = OS_SNARE06;
for (var measure=5; measure>17; measure ++){
  makeBeat(soundKick,4,measure,beatKick);
  makeBeat(soundSnare,5,measure,beatSnare);
}


// Mixing my tracks
// First, we analyze the tracks for loudness
var loudnessTrack1 = analyzeTrack(1,RMS_AMPLITUDE)
println('The loudness of track 1 is'+loudnessTrack1)
var loudnessTrack2 = analyzeTrack(2,RMS_AMPLITUDE)
println('The loudness of track 2 is'+loudnessTrack2)
var loudnessTrack3 = analyzeTrack(3,RMS_AMPLITUDE)
println('The loudness of track 3 is'+loudnessTrack3)

if (loudnessTrack1 < loudnessTrack2){
  //if track 1 is quieter than track 2 then we increase the volume of track 1
  setEffect(1,VOLUME,GAIN,+5);
  println ('track 1 was quieter than track 2');
} else if (loudnessTrack1 < loudnessTrack3){
  //if track 1 is louder than track 2 but quieter than track 3, we increase the volume of track 1
  setEffect(1,VOLUME,GAIN,+5);
  println ('track 1 was quieter than track 3');
} else { 
  //if track 1 is louder than tracks 2 and 3, then we change nothing
  println('track 1 was the loudest track already');
}

// Finish
finish();
----


[[chapter6summary]]
=== Résumé du chapitre 6

[role="curriculum-python"]
* La fonction `analyzeTrack()` nécessite deux arguments :
le numéro de piste et un paramètre. Lorsque le paramètre est `RMS_AMPLITUDE`, la fonction renvoie le volume de la piste (un nombre compris entre 0 et 1). Lorsque le paramètre est `SPECTRAL_CENTROID`, la fonction renvoie la brillance de la piste.
* Le type de données *booléen* peut seulement prendre deux valeurs : `True` ou `False`.
* Boolean values are generated by comparison operators: `==`, `!=`, `>`, `>=`, `<`, `\<=`.
* `==` évalue si deux valeurs sont égales, alors que `=` affecte une valeur à une variable.
* Un *opérateur * est un caractère qui représente une action.
* Les *expressions* sont évaluées par l'ordinateur pour produire une valeur.
* Une *instruction* correspond à une commande pour l'ordinateur.
* Une *condition* est une expression qui peut être évaluée `True` (vraie) ou `False` (fausse). 
* L'instruction _if_ n'exécute son bloc de code que lorsque sa condition est `True` (vraie). 
* Dans le cas où une condition _if_ est `False`, une instruction facultative _else_ permet l'exécution d'un bloc de code alternatif.

[role="curriculum-javascript"]
* La fonction `analyzeTrack()` prend deux arguments :
le numéro de piste et un paramètre. Lorsque le paramètre est `RMS_AMPLITUDE`, la fonction renvoie l'intensité sonore de la piste (un nombre compris entre 0 et 1). Lorsque le paramètre est `SPECTRAL_CENTROID`, la fonction renvoie la hauteur de la piste.
* Le type de données *booléen* peut valoir seulement deux valeurs : `true` ou `false`.
* Boolean values are generated by comparison operators: `==`, `!=`, `>`, `>=`, `<`, `\<=`.
* `==` évalue si deux valeurs sont égales, alors que `=` affecte une valeur à une variable.
* Un *opérateur * est un caractère qui représente une action.
* Les *expressions* sont évaluées par l'ordinateur pour produire une valeur.
* Une *instruction* correspond à une commande pour l'ordinateur.
* Une *condition* est une expression qui peut être évaluée `true` (vraie) ou `false` (fausse).
* L'instruction _if_ n'exécute son bloc de code que lorsque sa condition est `true` (vraie).
* Dans le cas où une condition _if_ est `false`, une instruction facultative _else_ permet l'exécution d'un bloc de code alternatif.


[[chapter-questions]]
=== Questions

[question]
--
Parmi les éléments suivants, lesquels sont des booléens ?
[answers]
* `5+4 == 5`
* `measure = 1`
* `2<3<4`
* `False()`
--

[role="curriculum-python"]
[question]
--
Quelle serait la valeur de retour du bloc de code suivant (qu'est-ce qui s'afficherait dans la console) ?
[source,python]
----
n = 5
if (n * 3 == 15):
    print(n + 5)
else:
    print(n)
----
[answers]
* 10
* 5
* True
* False
--

[role="curriculum-javascript"]
[question]
--
Quelle serait la valeur de retour du bloc de code suivant (qu'est-ce qui s'afficherait dans la console) ?
[source,javascript]
----
var n = 5;
if (n * 3 == 15) {
    println(5 + n);
} else {
    print(n);
}
----
[answers]
* 10
* 5
* True
* False
--

[question]
--
Qu'est-ce que le mixage ?
[answers]
* Adapter le volume de chaque piste pour qu'elles paraissent bien équilibrées
* Adapter la hauteur de chaque piste pour qu'elles paraissent bien équilibrées
* L'ajout d'un fondu d'ouverture
* L'ajout d'un fondu de fermeture
--

[question]
--
Combien de conditions pouvez-vous vérifier avec une instruction conditionnelle ?
[answers]
* n'importe quel nombre
* 1 condition
* 2 conditions
* 3 conditions
--
