[[customizeyourfirstsong]]
== Personnaliser votre première chanson

:nofooter:

Dans ce chapitre, vous apprendrez à modifier le tempo de votre chanson, à ajouter des commentaires à votre code et à charger vos propres sons pour appuyer le message de votre chanson.

[[settempo]]
=== La fonction `setTempo()`

[role="curriculum-python"]
--
Vous avez certainement remarqué que lorsque vous créez un nouveau script, il y a des éléments prédéfinis que vous devez absolument garder pour que votre code puisse s'exécuter :

. Quelques commentaires commençant par le symbole `#` en gris : nous couvrirons cela plus largement à la prochaine section.
. La ligne `from earsketch import*` qui permet d'ajouter les fonctions de EarSketch (comme `fitMedia()`) au projet.
. La fonction `setTempo(120)` que nous allons voir plus en détail ci-dessous.
--

[role="curriculum-javascript"]
--
Vous avez certainement remarqué que lorsque vous créez un nouveau script, il y a des éléments prédéfinis que vous devez absolument garder pour que votre code puisse s'exécuter :

. Quelques commentaires commençant par le symbole `//` en gris : nous couvrirons cela plus largement à la prochaine section.
. La fonction `setTempo(120)` que nous allons voir plus en détail ci-dessous.
--

La fonction `setTempo()` déterminera la vitesse de votre chanson. Le *tempo* correspond à un certain nombre de battements ou beats par minute (bpm) pour la musique occidentale. Dans EarSketch, le tempo par défaut (c'est-à-dire la valeur initiale du tempo) est fixé à 120 bpm, ce qui correspond à une vitesse de marche ou de marche rapide. Pour modifier le tempo, il suffit de changer le nombre entre les parenthèses de la fonction `setTempo()`. Plus le tempo est élevé, plus votre musique sera rapide. Vous pouvez choisir un tempo entre 45 bpm et 220 bpm.

.ENTRAÎNEZ-VOUS
****
. Créez un nouveau script.
. Placez des sons sur deux pistes différentes.
. Modifiez votre tempo et écoutez la chanson.
. Jouez votre chanson selon trois tempos différents pour un.e ami.e. Demandez-lui ensuite de classer les morceaux du tempo le plus lent au plus rapide. Demandez-lui ensuite de classer les morceaux du tempo le plus lent au plus rapide.
****

Un genre musical est un type de composition artistique (par exemple, la musique ou la peinture), caractérisée par des similitudes dans la forme, le style ou le thème. Chaque genre possède des gammes de tempo différentes. Par exemple :

[cols="^3*"]
|===
|GENRE |BPM |EXEMPLE

|Pop
|120-125
|"Thriller" - Michael Jackson

"I Wanna Dance With Somebody" - Whitney Houston

|Hip Hop
|100-130
|"Rapper's Delight" - The Sugar Hill Gang

"Fight the Power" - Public Enemy

|Country
|110-330
|"I Walk the Line" - Johnny Cash

"Jolene" - Dolly Parton

|House / EDM
|120-125
|"One More Time" - Daft Punk

"Good Vibrations" - Marky Mark

|Dubstep et trap
|140-150
|"Scary Monsters and Nice Sprites" - Skrillex

"Turn Down for What" - Lil Jon
|===

.ENTRAÎNEZ-VOUS
****
. Sélectionnez un.e artiste que vous aimez beaucoup et découvrez à quel genre il/elle appartient.
. Sur Soundcloud ou une plateforme similaire, écoutez quelques extraits de chansons correspondants à ce genre.
. Tentez de trouver des similitudes entre les chansons.
. Vous pouvez également faire une recherche par genre sur Wikipedia afin d'obtenir plus d'informations sur le sujet.
****

Sounds are automatically stretched to fit your song's tempo. Notez qu'un clip de son peut parfois sonner très différemment lorsque vous le pré-écoutez et lorsqu'il est joué dans votre chanson. The effect can be extreme if the tempos are very different.

To find the original tempo of sound, hover over the sound constant Sound Browser.

[[comments]]
=== Ajouter des commentaires à votre code

Les *commentaires* sont des lignes de code qui ne sont pas exécutées par l'ordinateur. Nous les utilisons uniquement pour rendre le code plus facile à comprendre ou pour mieux l'organiser. Les *commentaires* sont des lignes de code qui ne sont pas exécutées par l'ordinateur. Nous les utilisons uniquement pour rendre le code plus facile à comprendre, pour mieux l'organiser ou afin d'inscrire des notes pour un usage ultérieur.

EarSketch scripts begin with comments that you can use to enter a description of your song. Cela permet aux autres programmeur.se.s de comprendre plus facilement en quoi consiste votre code.

[role="curriculum-python"]
En Python, les commentaires sont indiqués par une ligne commençant par le symbole `#`.

[role="curriculum-javascript"]
En JavaScript, les commentaires sont indiqués par une ligne commençant par deux barres obliques `//`.

.ENTRAÎNEZ-VOUS
****
Notez que les premières lignes de chaque script sont des commentaires qui décrivent votre script.
****

Vous pouvez également utiliser des commentaires pour décrire ce que différentes sections de votre code feront. Voyez l'exemple ci-dessous. Vous pouvez coller le code, puis l'exécuter. Notez comment les commentaires offrent une description pour chaque section :

[role="curriculum-python"]
[source,python]
----
include::code-examples/your-first-song-comments.py.txt[]
----

[role="curriculum-javascript"]
[source,javascript]
----
include::code-examples/your-first-song-comments.js.txt[]
----

{nbsp} +

[[uploadingsounds]]
=== Charger vos propres sons

You can upload your own sounds through the Sound Browser on the left side of your screen. Ouvrez votre navigateur de sons et cliquez sur le bouton « ajouter un son » sous les filtres.

You must be logged in to upload sounds.

Explorons les trois premières options :

. *Charger un nouveau son* vous permet de choisir parmi des fichiers audio (.mp3, .aiff, etc.)
. *Enregistrement rapide* vous permet d'enregistrer de courts clips directement dans la bibliothèque EarSketch.
. *Freesound* vous permet d'importer directement des sons à partir de Freesound.org, une base de données audio open-source. Dans la barre de recherche, vous pouvez rechercher un type de son (p. ex. Then select the toggle button in front of the file name to select.

[role="curriculum-mp4"]
[[video101rec]]
video::./videoMedia/010-01-Recording&UploadingSounds-PY-JS.mp4[]

.ENTRAÎNEZ-VOUS
****
La plupart du temps, la musique, et l'art en général, est une manière de transmettre un message. Cela peut se faire par le biais des paroles ou du style de la chanson. Nous aimerions que vous créiez une chanson courte qui exprime quelque chose. Il peut s'agir d'un sentiment que vous souhaitez partager ou d'une histoire.

. Pensez à ce que vous souhaitez exprimer.
. Then either:
.. Ensuite, vous pouvez soit a) écrire quelques paroles et vous enregistrer en train de les chanter ou de les lire, soit b) enregistrer ou télécharger quelques sons qui se rapportent au message que vous voulez communiquer.
.. Record or download some sounds that are related to your message
. Ajoutez ces enregistrements à votre chanson à l'aide de la fonction `fitMedia()`.
. Ajoutez ensuite quelques clips de EarSketch supplémentaires à l'aide de la fonction `fitMedia()`.
. Faites écouter votre chanson à un.e ami.e.
. Vous pouvez discuter de vos chansons et des éléments que vous essayez d'exprimer.
****

Les *processus* ou tâches sont des programmes qui s'exécutent sur votre ordinateur.

When you start a process, the computer code is first stored in the computer's *memory* for quick access. La *mémoire* d'un ordinateur contient des données et des instructions de traitement que l'unité centrale doit utiliser. The CPU is often considered the "brain" of the computer.

La mémoire, également appelée mémoire de stockage primaire ou RAM (mémoire à accès aléatoire), stocke temporairement ses données. It is designed to be fast and temporary, for active processes only.

Il y a une différence entre la mémoire (ou stockage à court terme) et le stockage à long terme. Le stockage à long terme, comme un disque dur ou un cloud, est appelé stockage secondaire. Le *stockage secondaire* stocke de grands volumes de données pour de longues périodes de temps, même après l'arrêt de l'ordinateur. Le CPU n'interagit pas directement avec le stockage secondaire. Lorsque le CPU exécute un processus, les données du stockage secondaire doivent d'abord être mises en mémoire pour que le CPU puisse y accéder rapidement.

Parfois, les données en mémoire que le CPU utilise proviennent d'un périphérique d'entrée plutôt que d'un stockage secondaire. Les *entrées* sont les signaux ou les données reçus par l'ordinateur, comme l'audio d'un microphone, ou la position de la souris. De même, les *sorties* sont les signaux ou les données qui y sont envoyés, comme l'audio à travers un hautparleur. L'entrée/sortie ou I/O, est la façon dont l'ordinateur communique avec le monde extérieur, y compris les êtres humains !

Examinons maintenant l'enregistrement d'un son dans EarSketch comme exemple de processus. Tout d'abord, nous enregistrons des données dans l'ordinateur avec le périphérique d'entrée, le microphone. Le CPU stocke ces données audio dans sa mémoire. Si vous appuyez sur le bouton de lecture pour entendre votre enregistrement, le CPU accède aux données et les envoie à une sortie, des hautparleurs ou des écouteurs. Lorsque vous appuyez sur le bouton de chargement, le CPU exécute un processus qui convertit les données audio en un format de fichier audio standard (un fichier WAV ou .wav) et l'envoie au serveur EarSketch. Le serveur est un système externe qui fournit des services à tous les utilisateurs de EarSketch, y compris votre propre ordinateur. Le serveur EarSketch enregistre le fichier son de la mémoire vers le stockage secondaire du serveur afin que vous puissiez y accéder dans le futur.

Jetez un coup d'œil à la vidéo complémentaire suivante :

[role="curriculum-mp4"]
[[video11cpu]]
video::./videoMedia/010-02-ProcessesandMemory-PY-JS.mp4[]

////
END OF OPTIONAL
////

[[copyright]]
=== Les droits d'auteur.ice

Le *droit d'auteur ou Copyright* est la partie de la loi qui couvre la *propriété intellectuelle* ou la propriété de l'œuvre créative, comme la musique. Lorsque vous utilisez des échantillons (petits extraits musicaux, samples en anglais) ou remixez de la musique existante, vous devez absolument créditer les auteurs. Avant d’utiliser les sons créés par d’autres musiciens et de partager votre propre musique, apprenez-en davantage sur le droit d’auteur !

Lorsque vous créez une nouvelle œuvre assez substantielle, vous obtenez automatiquement un droit d'auteur.ice ! Aux États-Unis, cela signifie que vous pouvez les reproduire, apporter des modifications et partager ce que vous créez.

Il y a deux droits d'auteur liés à une chanson : les droits de la chanson (par l'auteur.ice ou le.a compositeur.ice) et les droits d'enregistrement sonore (souvent par la maison de disques). Les redevances provenant des représentations publiques vont à l’auteur-compositeur tandis que la plupart des redevances provenant des ventes de disques vont à la maison de disques.

La *violation du droit d'auteur.ice* est une appropriation illégale des avantages liés au droit d'auteur, comme le téléchargement illégal de la musique. Aux États-Unis, *l'utilisation équitable ou « fair use » * permet l'utilisation de contenu protégé par un droit d'auteur sous certaines conditions, comme des fins éducatives ou ne réutilisant que de petits extraits de l'œuvre. L'utilisation équitable est déterminée par un juge au cas par cas.

Outre l'utilisation équitable, il y a un moyen d'utiliser et de partager de la musique de manière ouverte. Ces artistes ont partagé leurs échantillons sous une licence *Creative Commons* qui donne la permission aux autres personnes d'utiliser leur travail.

Copyright is not all about getting people in trouble. If you upload a song to the internet, you might not mind if someone downloads it without asking; you want people to share your music! Le droit d'auteur devrait nous aider à créer et à partager davantage d'art, et non à restreindre son utilisation. When you are creating songs in EarSketch, we want you to think less about _stealing_ and more about _sharing_. En effet, EarSketch fonctionne parce que les artistes ont partagé leurs œuvres ou travail avec vous par le biais d'*échantillons* dans la bibliothèque de sons. Le fait de partager votre musique ou de permettre à d'autres étudiants de remixer votre code est une façon de redonner à la communauté et d'aider à diffuser de nouvelles œuvres dans le monde.

Lorsque vous partagez un script dans EarSketch, il vous sera demandé de choisir une licence pour votre chanson.

For full details, refer to our https://earsketch.gatech.edu/landing/#/license[LICENSE^].

[[chapter2summary]]
=== Résumé du chapitre 2

[role="curriculum-python"]
* Le *tempo* est la vitesse à laquelle un morceau de musique est joué, exprimé en battements ou beats par minute (bpm). Le tempo est lié au genre musical.
* Les clips de la bibliothèque de sons EarSketch sont regroupés dans des dossiers de sons apparentés. Pour connaître le tempo exact de l'extrait, survolez le nom du clip dans la bibliothèque de sons.
* Les commentaires sont des lignes de code qui ne sont pas exécutées par l'ordinateur. Elles sont cependant utiles pour créer des notes dans un script.
* La fonction `from earsketch import *` permet d'ajouter l'API de EarSketch à votre projet.
* La fonction `setTempo()` vous permet de spécifier le tempo de votre chanson. Elle doit être incluse dans chaque script EarSketch.
* Vous pouvez charger vos propres clips audio dans EarSketch à travers la bibliothèque de sons. Cliquez simplement sur « Ajouter un son ».
* Un *processus* est une tâche exécutée sur un ordinateur. Le traitement est effectué par le *CPU* d'un ordinateur, qui est responsable de l'exécution des instructions du programme.
* La *mémoire* (mémoire de stockage primaire ou RAM) contient temporairement des instructions de traitement et de données afin que le CPU puisse les utiliser.
* Le *stockage secondaire* fait référence à un stockage de données à long terme, souvent en grands volumes. Les données du stockage secondaire doivent être mises en mémoire avant que le CPU puisse y accéder.
* Le *droit d’auteur.ice* est une partie de la loi qui couvre la propriété d'une œuvre créative, comme la musique. C'est très important pour les musiciens, car cela définit comment l'œuvre d'une autre personne peut être utilisée et partagée.
* Si vous créez une nouvelle œuvre musicale, vous disposez automatiquement d’un droit d’auteur.ice. En d'autres termes, vous avez des droits sur le travail que vous avez créé.
* La *concession de licence* pour un morceau de musique accorde la permission à d'autres personnes de l'utiliser.

[role="curriculum-javascript"]
* Le *tempo* est la vitesse à laquelle un morceau de musique est joué, exprimé en battements ou beats par minute (bpm). Le tempo est lié au genre musical.
* Les clips de la bibliothèque de sons EarSketch sont regroupés dans des dossiers de sons apparentés. Pour connaître le tempo exact de l'extrait, survolez le nom du clip dans la bibliothèque de sons.
* Les commentaires sont des lignes de code qui ne sont pas exécutées par l'ordinateur. Elles sont cependant utiles pour créer des notes dans un script.
* La fonction `setTempo();` vous permet de spécifier le tempo de votre chanson. Elle doit être incluse dans chaque script EarSketch.
* Vous pouvez charger vos propres clips audio dans EarSketch à travers la bibliothèque de sons. Cliquez simplement sur « Ajouter un son ».
* Un *processus* est une tâche exécutée sur un ordinateur. Le traitement est effectué par le *CPU* d'un ordinateur, qui est responsable de l'exécution des instructions du programme.
* La *mémoire* (mémoire de stockage primaire ou RAM) contient temporairement des instructions de traitement et de données afin que le CPU puisse les utiliser.
* Le *stockage secondaire* fait référence à un stockage de données à long terme, souvent en grands volumes. Les données du stockage secondaire doivent être mises en mémoire avant que le CPU puisse y accéder.
* Le *droit d’auteur.ice* est une partie de la loi qui couvre la propriété d'une œuvre créative, comme la musique. C'est très important pour les musiciens, car cela définit comment l'œuvre d'une autre personne peut être utilisée et partagée.
* Si vous créez une nouvelle œuvre musicale, vous disposez automatiquement d’un droit d’auteur.ice. En d'autres termes, vous avez des droits sur le travail que vous avez créé.
* La *concession de licence* pour un morceau de musique accorde la permission à d'autres personnes de l'utiliser.

[[chapter-questions]]
=== Questions

[question]
--
Qu'est-ce que la fonction `setTempo()` vous permet de faire dans EarSketch ?

[answers]
* Préciser la vitesse d'une chanson
* Ajouter un son à une piste
* Créer un rythme percussif
* Modifier les qualités sonores d'un projet
--

[question]
--
Quelle est l'unité du tempo ?

[answers]
* Beats par minute (BPM)
* Mesures
* Décibels (dB)
* Secondes
--

[question]
--
À quoi servent les commentaires ?

[answers]
* Toutes ces réponses
* Organiser votre code
* Écrire une description de votre script au début du script
* Rendre votre code facile à lire pour les autres programmeur.ses
--

[question]
--
Parmi les affirmations suivantes, laquelle est vraie ?

[answers]
* Un disque dur est un exemple de stockage secondaire
* Les données audio sont enregistrées dans le CPU d'un ordinateur
* Le CPU contient des données instructionnelles pour les programmes
* Le stockage secondaire stocke les données pour de courtes périodes de temps
--

[question]
--
Que faut-il faire pour obtenir un droit d'auteur.ice ?

[answers]
* Créer et publier toute nouvelle œuvre
* Acheter un brevet
* Rejoindre une organisation secrète
* Choisir une licence pour votre œuvre ou travail
--

[question]
--
What is a music license?

[answers]
* Le droit de poursuivre toute personne qui utilise votre musique
* Un processus de composition
* Techno
* Cela est dû au fait que le tempo du clip est différent de celui de votre chanson.
--