[[ch_28]]
== Tous les effets expliqués en détail

:nofooter:

[[bandpass]]
=== BANDPASS

++++
<div class="effect-examples">
    <div class="audio-label">Avec effet :</div>
    <div class="curriculum-mp3">audioMedia/bandpass_wet.mp3</div>
    <div class="audio-label">Sans effet :</div>
    <div class="curriculum-mp3">audioMedia/bandpass_dry.mp3</div>
</div>
++++

[role="curriculum-python"]
[source,python]
----
from earsketch import *
fitMedia(RD_UK_HOUSE_ACOUSTICGUITAR_1, 1, 1, 3)
setEffect(1, BANDPASS, BANDPASS_FREQ, 1000)
setEffect(1, BANDPASS, BANDPASS_RESONANCE, 0.9)
setEffect(1, BANDPASS, MIX, 1)
----

[role="curriculum-javascript"]
[source,javascript]
----
fitMedia(RD_UK_HOUSE_ACOUSTICGUITAR_1, 1, 1, 3);
setEffect(1, BANDPASS, BANDPASS_FREQ, 1000);
setEffect(1, BANDPASS, BANDPASS_RESONANCE, 0.9);
setEffect(1, BANDPASS, MIX, 1);
----

`BANDPASS` est un filtre qui ne fait passer qu'une bande de fréquences de taille réglable. Toutes les autres fréquences sont supprimées. By creating a narrower band of frequencies (setting `BANDPASS_RESONANCE` closer to 1), you can make a telephone or megaphone-like sound. En utilisant une gamme de fréquences plus large (donc en réglant BANDPASS_WIDTH sur une valeur plus élevée), les sons qui semblent « trop gros » pour un mixage peuvent être atténués afin de mieux s'intégrer aux autres sons du mixage.

|===
|Paramètre |Description |Valeur par défaut |minValue |maxValue

|BANDPASS_FREQ |La fréquence centrale (en Hz) de la fenêtre des fréquences à passer. |800.0 |20.0 |20000.0

|BANDPASS_WIDTH |Le degré d'amplification d'une bande étroite de fréquences autour du niveau actuel de `FILTER_FREQ`. Higher values of resonance strongly boost a small window (band)of frequencies, while lower values of resonance subtly boost a larger window (band). |0.5 |0.0 |1.0

|MIX |Le pourcentage de son produit (avec effet) qui est mixé au son original (sans effet). À sa valeur minimale (0.0), aucun effet ne peut être entendu. À sa valeur maximale (1.0), aucun son original n'est entendu, il s'agit uniquement d'effets. |0.1 |0.0 |1.0

|BYPASS |When you bypass an effect, the effect turns off. Notez que contrairement aux autres paires de nom/paramètre, les seules valeurs valides pour BYPASS sont 0.0 et 1.0. |0.0 |0.0 |1.0
|===

[[chorus]]
=== CHORUS

++++
<div class="effect-examples">
    <div class="audio-label">Avec effet :</div>
    <div class="curriculum-mp3">audioMedia/chorus_wet.mp3</div>
    <div class="audio-label">Sans effet :</div>
    <div class="curriculum-mp3">audioMedia/chorus_dry.mp3</div>
</div>
++++

[role="curriculum-python"]
[source,python]
----
from earsketch import *
fitMedia(YG_TECHNO_VOX_2, 1, 1, 2)
setEffect(1, CHORUS, CHORUS_LENGTH, 15)
setEffect(1, CHORUS, CHORUS_NUMVOICES, 1)
setEffect(1, CHORUS, CHORUS_RATE, 10)
setEffect(1, CHORUS, MIX, 0.5)
----

[role="curriculum-javascript"]
[source,javascript]
----
fitMedia(YG_TECHNO_VOX_2, 1, 1, 2);
setEffect(1, CHORUS, CHORUS_LENGTH, 15);
setEffect(1, CHORUS, CHORUS_NUMVOICES, 1);
setEffect(1, CHORUS, CHORUS_RATE, 10);
setEffect(1, CHORUS, MIX, 0.5);
----

`CHORUS` crée diverses copies du son original qui sont légèrement modifiées sur le plan de la hauteur et du temps et mixées à nouveau dans le son, créant ainsi un effet d'ensemble de plusieurs voix jouant ensemble.

|===
|Paramètre |Description |Valeur par défaut |minValue |maxValue

|CHORUS_LENGTH |La durée (en ms) du son original pendant laquelle l'effet Chorus est activé. |15.0 |1.0 |250.0

|CHORUS_NUMVOICES |Le nombre de copies du son original utilisé. Des valeurs plus élevées créent un effet d'ensemble plus important. |1.0 |1.0 |8.0

|CHORUS_RATE |La fréquence (en Hz) à laquelle la hauteur du son se déplace ou « oscille ». Les valeurs faibles créent des sons réguliers, tandis que les valeurs élevées créent des effets plus ondulatoires. |0.5 |0.1 |16.0

|CHORUS_MOD |La profondeur de l'oscillation de la hauteur (c'est-à-dire la quantité de cycles de hauteur utilisés). Les réglages bas créent un son plus naturel, tandis que les paramètres plus élevés créent un son plus artificiel. |0.7 |0.0 |1.0

|MIX |Le pourcentage de son produit (avec effet) qui est mixé au son original (sans effet). À sa valeur minimale (0.0), aucun effet ne peut être entendu. À sa valeur maximale (1.0), aucun son original n'est entendu, il s'agit uniquement d'effets. |1.0 |0.0 |1.0

|BYPASS |When you bypass an effect, the effect turns off. Notez que contrairement aux autres paires de nom/paramètre, les seules valeurs valides pour BYPASS sont 0.0 et 1.0. |0.0 |0.0 |1.0
|===

[[compressor]]
=== COMPRESSOR

++++
<div class="effect-examples">
    <div class="audio-label">Avec effet :</div>
    <div class="curriculum-mp3">audioMedia/compressor_wet.mp3</div>
    <div class="audio-label">Sans effet :</div>
    <div class="curriculum-mp3">audioMedia/compressor_dry.mp3</div>
</div>
++++

[role="curriculum-python"]
[source,python]
----
from earsketch import *
fitMedia(EIGHT_BIT_ANALOG_DRUM_LOOP_001, 1, 1, 3)
setEffect(1, COMPRESSOR, COMPRESSOR_THRESHOLD, -30)
setEffect(1, COMPRESSOR, COMPRESSOR_RATIO, 100)
----

[role="curriculum-javascript"]
[source,javascript]
----
fitMedia(EIGHT_BIT_ANALOG_DRUM_LOOP_001, 1, 1, 3);
setEffect(1, COMPRESSOR, COMPRESSOR_THRESHOLD, -30);
setEffect(1, COMPRESSOR, COMPRESSOR_RATIO, 100);
----

`COMPRESSOR` reduces the volume of the loudest sections of a sound and amplifies the quietest sections. This creates a smaller dynamic range, which means that the volume of the track stays more constant throughout. Music producers often use compressors to fine-tune and add “punch” to drums.

|===
|Paramètre |Description |Valeur par défaut |minValue |maxValue

|COMPRESSOR_THRESHOLD |Le niveau d'amplitude (volume) (en dB) au-dessus duquel le compresseur commence à réduire le volume. |-18.0 |-30.0 |0.0

|COMPRESSOR_RATIO |Le taux de réduction de gain spécifié. Un ratio de 3:1 signifie que si le son d'origine est de 3 dB au-dessus du seuil, alors le son avec effet sera de 1 dB au-dessus du seuil. |10.0 |1.0 |100.0

|BYPASS |When you bypass an effect, the effect turns off. Notez que contrairement aux autres paires de nom/paramètre, les seules valeurs valides pour BYPASS sont 0.0 et 1.0. |0.0 |0.0 |1.0
|===

[[delay]]
=== DELAY

++++
<div class="effect-examples">
    <div class="audio-label">Avec effet :</div>
    <div class="curriculum-mp3">audioMedia/delay_wet.mp3</div>
    <div class="audio-label">Sans effet :</div>
    <div class="curriculum-mp3">audioMedia/delay_dry.mp3</div>
</div>
++++

[role="curriculum-python"]
[source,python]
----
from earsketch import *
fitMedia(YG_TECHNO_VOX_2, 1, 1, 3)
setEffect(1, DELAY, DELAY_TIME, 370)
setEffect(1, DELAY, DELAY_FEEDBACK, -3.5)
setEffect(1, DELAY, MIX, 1)
----

[role="curriculum-javascript"]
[source,javascript]
----
fitMedia(YG_TECHNO_VOX_2, 1, 1, 3);
setEffect(1, DELAY, DELAY_TIME, 370);
setEffect(1, DELAY, DELAY_FEEDBACK, -3.5);
setEffect(1, DELAY, MIX, 1);
----

`DELAY` crée un délai ressemblant à un écho répété du son d'origine. Un effet de délai permet de lire l'audio d'origine ainsi qu'une version avec délai plus silencieuse de l'original qui sonne comme un écho. Après le premier écho, il joue un écho de l'écho (encore plus silencieux), puis un écho de l'écho de l'écho (encore plus silencieux) et ainsi de suite jusqu'à ce que l'écho disparaisse. Si nous réglons le délai de manière à ce qu'il corresponde à la durée d'un beat, nous pouvons créer des effets rythmiques avec délai.

|===
|Paramètre |Description |Valeur par défaut |minValue |maxValue

|DELAY_TIME |La durée en millisecondes (en ms) pendant laquelle la piste d'origine subit l'effet de délai et le temps entre les répétitions successives du délai. |300.0 |0.0 |4000.0

|DELAY_FEEDBACK |La quantité relative de répétitions que le délai génère. Des valeurs plus élevées créent plus d'« échos ». Cependant, faites attention à appliquer trop de « feedback » ! |-3.0 |-120.0 |-1.0

|MIX |Le pourcentage de son produit (avec effet) qui est mixé au son original (sans effet). À sa valeur minimale (0.0), aucun effet ne peut être entendu. À sa valeur maximale (1.0), aucun son original n'est entendu, il s'agit uniquement d'effets. |0.5 |0.0 |1.0

|BYPASS |When you bypass an effect, the effect turns off. Notez que contrairement aux autres paires de nom/paramètre, les seules valeurs valides pour BYPASS sont 0.0 et 1.0. |0.0 |0.0 |1.0
|===

[[distortion]]
=== DISTORTION

++++
<div class="effect-examples">
    <div class="audio-label">Avec effet :</div>
    <div class="curriculum-mp3">audioMedia/distortion_wet.mp3</div>
    <div class="audio-label">Sans effet :</div>
    <div class="curriculum-mp3">audioMedia/distortion_dry.mp3</div>
</div>
++++

[role="curriculum-python"]
[source,python]
----
from earsketch import *
fitMedia(RD_UK_HOUSE_ACOUSTICGUITAR_1, 1, 1, 3)
setEffect(1, DISTORTION, DISTO_GAIN, 27)
setEffect(1, DISTORTION, MIX, 1)
----

[role="curriculum-javascript"]
[source,javascript]
----
fitMedia(RD_UK_HOUSE_ACOUSTICGUITAR_1, 1, 1, 3);
setEffect(1, DISTORTION, DISTO_GAIN, 27);
setEffect(1, DISTORTION, MIX, 1);
----

Cela comprime ou écrête l'onde sonore, ajoutant des harmoniques (des fréquences plus élevées liées au son d'origine). `DISTORTION` is commonly used on electric guitars in rock and grunge music, but you can use it for many different sounds.

|===
|Paramètre |Description |Valeur par défaut |minValue |maxValue

|DISTO_GAIN |Le taux de surcharge du son original. |20.0 |0.0 |50.0

|MIX |Le pourcentage de son produit (avec effet) qui est mixé au son original (sans effet). À sa valeur minimale (0.0), aucun effet ne peut être entendu. À sa valeur maximale (1.0), aucun son original n'est entendu, il s'agit uniquement d'effets. |1.0 |0.0 |1.0

|BYPASS |When you bypass an effect, the effect turns off. Notez que contrairement aux autres paires de nom/paramètre, les seules valeurs valides pour BYPASS sont 0.0 et 1.0. |0.0 |0.0 |1.0
|===

[[eq3band]]
=== EQ3BAND

++++
<div class="effect-examples">
    <div class="audio-label">Avec effet :</div>
    <div class="curriculum-mp3">audioMedia/eq3band_wet.mp3</div>
    <div class="audio-label">Sans effet :</div>
    <div class="curriculum-mp3">audioMedia/eq3band_dry.mp3</div>
</div>
++++

[role="curriculum-python"]
[source,python]
----
from earsketch import *
fitMedia(EIGHT_BIT_ANALOG_DRUM_LOOP_001, 1, 1, 3)
setEffect(1, EQ3BAND, EQ3BAND_LOWGAIN, -15)
setEffect(1, EQ3BAND, EQ3BAND_MIDGAIN, -5)
setEffect(1, EQ3BAND, EQ3BAND_HIGHGAIN, 15)
setEffect(1, EQ3BAND, EQ3BAND_HIGHFREQ, 2000)
setEffect(1, EQ3BAND, MIX, 1)
----

[role="curriculum-javascript"]
[source,javascript]
----
fitMedia(EIGHT_BIT_ANALOG_DRUM_LOOP_001, 1, 1, 3);
setEffect(1, EQ3BAND, EQ3BAND_LOWGAIN, -15);
setEffect(1, EQ3BAND, EQ3BAND_MIDGAIN, -5);
setEffect(1, EQ3BAND, EQ3BAND_HIGHGAIN, 15);
setEffect(1, EQ3BAND, EQ3BAND_HIGHFREQ, 2000);
setEffect(1, EQ3BAND, MIX, 1);
----

`EQ3BAND` est un égaliseur à trois bandes utilisé pour des tâches d'égalisation simples. EQ is used in music production to get rid of unwanted frequencies, create balance between tracks to get a radio-ready mix, or simply change the "vibe" of a sound.

|===
|Paramètre |Description |Valeur par défaut |minValue |maxValue

|EQ3BAND_LOWGAIN |Le gain (en dB) de la gamme de basses fréquences de l'EQ. Les valeurs négatives réduisent le volume des basses fréquences, tandis que les valeurs positives les augmentent. |0.0 |-24.0 |18.0

|EQ3BAND_LOWFREQ |Indique la fréquence la plus élevée (en Hz) de la gamme de basses fréquences. |200.0 |20.0 |20000.0

|EQ3BAND_MIDGAIN |Le gain (en dB) de la gamme de moyennes fréquences de l'EQ. Les valeurs négatives réduisent le volume des moyennes fréquences, tandis que les valeurs positives les augmentent. |0.0 |-24.0 |18.0

|EQ3BAND_MIDFREQ |Indique la fréquence centrale (en Hz) de la gamme de moyennes fréquences. |2000.0 |20.0 |20000.0

|EQ3BAND_HIGHGAIN |Le gain (en dB) de la gamme de hautes fréquences de l'EQ. Les valeurs négatives réduisent le volume des hautes fréquences, tandis que les valeurs positives les augmentent. |0.0 |-24.0 |18.0

|EQ3BAND_HIGHFREQ |Indique la fréquence de coupure (en Hz) de la gamme de hautes fréquences. |2000.0 |20.0 |20000.0

|MIX |Le pourcentage de son produit (avec effet) qui est mixé au son original (sans effet). À sa valeur minimale (0.0), aucun effet ne peut être entendu. À sa valeur maximale (1.0), aucun son original n'est entendu, il s'agit uniquement d'effets. |1.0 |0.0 |1.0

|BYPASS |When you bypass an effect, the effect turns off. Notez que contrairement aux autres paires de nom/paramètre, les seules valeurs valides pour BYPASS sont 0.0 et 1.0. |0.0 |0.0 |1.0
|===

[[filter]]
=== FILTER

++++
<div class="effect-examples">
    <div class="audio-label">Avec effet :</div>
    <div class="curriculum-mp3">audioMedia/filter_wet.mp3</div>
    <div class="audio-label">Sans effet :</div>
    <div class="curriculum-mp3">audioMedia/filter_dry.mp3</div>
</div>
++++

[role="curriculum-python"]
[source,python]
----
from earsketch import *
fitMedia(EIGHT_BIT_ANALOG_DRUM_LOOP_001, 1, 1, 3)
setEffect(1, FILTER, FILTER_FREQ, 20, 1, 4000, 3)
setEffect(1, FILTER, FILTER_RESONANCE, 0.9)
setEffect(1, FILTER, MIX, 1)
----

[role="curriculum-javascript"]
[source,javascript]
----
fitMedia(EIGHT_BIT_ANALOG_DRUM_LOOP_001, 1, 1, 3);
setEffect(1, FILTER, FILTER_FREQ, 20, 1, 4000, 3);
setEffect(1, FILTER, FILTER_RESONANCE, 0.9);
setEffect(1, FILTER, MIX, 1);
----

`FILTER` can soften, darken, or add depth to sound. Un effet filtre passe-bas permet à l'audio de basse fréquence de passer inchangé, tout en abaissant le volume des fréquences supérieures à une fréquence de coupure (le paramètre `FILTER_FREQ`).

|===
|Paramètre |Description |Valeur par défaut |minValue |maxValue

|FILTER_FREQ |La fréquence de coupure (Hz), ce qui signifie que toutes les fréquences supérieures à cette valeur sont atténuées (leur volume devient de plus en plus faible à mesure qu'elles sont plus élevées que cette valeur). |1000.0 |20.0 |20000.0

|FILTER_RESONANCE |Cela permet aux fréquences situées autour du niveau actuel de `FILTER_FREQ` de résonner davantage, d'être plus « résonantes ». Lorsque les valeurs de résonance sont élevées, le filtre devient plus « accentué » autour de la fréquence `FILTER_FREQ`, ce qui accentue les fréquences les plus proches de la fréquence de coupure. |0.8 |0.0 |1.0

|MIX |Le pourcentage de son produit (avec effet) qui est mixé au son original (sans effet). À sa valeur minimale (0.0), aucun effet ne peut être entendu. À sa valeur maximale (1.0), aucun son original n'est entendu, il s'agit uniquement d'effets. |1.0 |0.0 |1.0

|BYPASS |When you bypass an effect, the effect turns off. Notez que contrairement aux autres paires de nom/paramètre, les seules valeurs valides pour BYPASS sont 0.0 et 1.0. |0.0 |0.0 |1.0
|===

[[flanger]]
=== FLANGER

++++
<div class="effect-examples">
    <div class="audio-label">Avec effet :</div>
    <div class="curriculum-mp3">audioMedia/flanger_wet.mp3</div>
    <div class="audio-label">Sans effet :</div>
    <div class="curriculum-mp3">audioMedia/flanger_dry.mp3</div>
</div>
++++

[role="curriculum-python"]
[source,python]
----
from earsketch import *
fitMedia(YG_TECHNO_VOX_2, 1, 1, 2)
setEffect(1, FLANGER, FLANGER_LENGTH, 10)
setEffect(1, FLANGER, FLANGER_FEEDBACK, -5)
setEffect(1, FLANGER, FLANGER_RATE, 20)
setEffect(1, FLANGER, MIX, 1)
----

[role="curriculum-javascript"]
[source,javascript]
----
fitMedia(YG_TECHNO_VOX_2, 1, 1, 2);
setEffect(1, FLANGER, FLANGER_LENGTH, 10);
setEffect(1, FLANGER, FLANGER_FEEDBACK, -5);
setEffect(1, FLANGER, FLANGER_RATE, 20);
setEffect(1, FLANGER, MIX, 1);
----

`FLANGER` est similaire à un effet Chorus, qui consiste à créer plusieurs copies du son original, à les faire varier légèrement en hauteur et en temps, puis à les remixer dans le son. À des valeurs extrêmes de réglage des paramètres, on peut entendre des sons plus artificiels ressemblant à ceux d'un robot.

|===
|Paramètre |Description |Valeur par défaut |minValue |maxValue

|FLANGER_LENGTH |La durée du délai (en ms) par rapport au son original pendant laquelle l'effet Flanger est activé. |6.0 |0.0 |200.0

|FLANGER_FEEDBACK |La quantité (en dB) du son produit qui est « réinjecté » dans l'effet. Des valeurs plus élevées créent plus de sons artificiels. |-50.0 |-80.0 |-1.0

|FLANGER_RATE |The rate (in Hz) which the pitch cycles or "whooshes" at. Les valeurs faibles créent des sons plus réguliers, tandis que les valeurs élevées créent des effets plus sonores et des artefacts sonores. |0.6 |0.001 |100.0

|MIX |Le pourcentage de son produit (avec effet) qui est mixé au son original (sans effet). À sa valeur minimale (0.0), aucun effet ne peut être entendu. À sa valeur maximale (1.0), aucun son original n'est entendu, il s'agit uniquement d'effets. |1.0 |0.0 |1.0

|BYPASS |When you bypass an effect, the effect turns off. Notez que contrairement aux autres paires de nom/paramètre, les seules valeurs valides pour BYPASS sont 0.0 et 1.0. |0.0 |0.0 |1.0
|===

[[pan]]
=== PAN

++++
<div class="effect-examples">
    <div class="audio-label">Avec effet :</div>
    <div class="curriculum-mp3">audioMedia/pan_wet.mp3</div>
    <div class="audio-label">Sans effet :</div>
    <div class="curriculum-mp3">audioMedia/pan_dry.mp3</div>
</div>
++++

[role="curriculum-python"]
[source,python]
----
from earsketch import *
fitMedia(RD_UK_HOUSE_ACOUSTICGUITAR_1, 1, 1, 3)
setEffect(1, PAN, LEFT_RIGHT, -100, 1.5, 100, 2.5)
----

[role="curriculum-javascript"]
[source,javascript]
----
fitMedia(RD_UK_HOUSE_ACOUSTICGUITAR_1, 1, 1, 3);
setEffect(1, PAN, LEFT_RIGHT, -100, 1.5, 100, 2.5);
----

`PAN` affecte le mixage audio entre les canaux gauche et droit. Par exemple, si vous portez des écouteurs, le fait de modifier le panoramique déterminera si vous entendez quelque chose dans l'oreille gauche ou dans l'oreille droite.

|===
|Paramètre |Description |Valeur par défaut |minValue |maxValue

|LEFT_RIGHT |Précise l'emplacement gauche ou droit du son original dans le champ stéréo (0.0 correspond au centre, -100.0 correspond à une position entièrement gauche, 100.0 correspond à une position entièrement droite). |0.0 |-100.0 |100.0

|BYPASS |When you bypass an effect, the effect turns off. Notez que contrairement aux autres paires de nom/paramètre, les seules valeurs valides pour BYPASS sont 0.0 et 1.0. |0.0 |0.0 |1.0
|===

[[phaser]]
=== PHASER

++++
<div class="effect-examples">
    <div class="audio-label">Avec effet :</div>
    <div class="curriculum-mp3">audioMedia/phaser_wet.mp3</div>
    <div class="audio-label">Sans effet :</div>
    <div class="curriculum-mp3">audioMedia/phaser_dry.mp3</div>
</div>
++++

[role="curriculum-python"]
[source,python]
----
from earsketch import *
fitMedia(RD_UK_HOUSE_ACOUSTICGUITAR_1, 1, 1, 3)
setEffect(1, PHASER, PHASER_RATE, 0.7)
setEffect(1, PHASER, PHASER_RANGEMIN, 440)
setEffect(1, PHASER, PHASER_RANGEMIN, 1600)
setEffect(1, PHASER, PHASER_FEEDBACK, -2)
setEffect(1, PHASER, MIX, 1)
----

[role="curriculum-javascript"]
[source,javascript]
----
fitMedia(RD_UK_HOUSE_ACOUSTICGUITAR_1, 1, 1, 3);
setEffect(1, PHASER, PHASER_RATE, 0.7);
setEffect(1, PHASER, PHASER_RANGEMIN, 440);
setEffect(1, PHASER, PHASER_RANGEMIN, 1600);
setEffect(1, PHASER, PHASER_FEEDBACK, -2);
setEffect(1, PHASER, MIX, 1);
----

`PHASER` est un effet de balayage qui crée une copie du son original sur une gamme de fréquences spécifiée. Ainsi, certaines des fréquences copiées s'annulent temporairement en étant « en phase et hors phase » les unes avec les autres, créant ainsi un effet de balayage.

|===
|Paramètre |Description |Valeur par défaut |minValue |maxValue

|PHASER_RATE |La fréquence (en Hz) à laquelle le léger délai varie dans les deux sens. Les valeurs faibles créent des sons plus réguliers, tandis que les valeurs élevées créent des effets plus robotiques et des artefacts sonores. |0.5 |0.0 |10.0

|PHASER_RANGEMIN |La faible valeur (en Hz) de la gamme de fréquences affectée. |440.0 |40.0 |20000.0

|PHASER_RANGEMAX |La valeur élevée (en Hz) de la gamme de fréquences affectée. |1600.0 |40.0 |20000.0

|PHASER_FEEDBACK |La quantité du son produit qui est « réinjecté » dans l'effet. Des valeurs plus élevées créent plus de sons artificiels. |-3.0 |-120.0 |-1.0

|MIX |Le pourcentage de son produit (avec effet) qui est mixé au son original (sans effet). À sa valeur minimale (0.0), aucun effet ne peut être entendu. À sa valeur maximale (1.0), aucun son original n'est entendu, il s'agit uniquement d'effets. |1.0 |0.0 |1.0

|BYPASS |When you bypass an effect, the effect turns off. Notez que contrairement aux autres paires de nom/paramètre, les seules valeurs valides pour BYPASS sont 0.0 et 1.0. |0.0 |0.0 |1.0
|===

[[pitchshift]]
=== PITCHSHIFT

++++
<div class="effect-examples">
    <div class="audio-label">Avec effet :</div>
    <div class="curriculum-mp3">audioMedia/pitchshift_wet.mp3</div>
    <div class="audio-label">Sans effet :</div>
    <div class="curriculum-mp3">audioMedia/pitchshift_dry.mp3</div>
</div>
++++

[role="curriculum-python"]
[source,python]
----
from earsketch import *
fitMedia(YG_TECHNO_VOX_2, 1, 1, 2)
setEffect(1, PITCHSHIFT, PITCHSHIFT_SHIFT, -10)
----

[role="curriculum-javascript"]
[source,javascript]
----
fitMedia(YG_TECHNO_VOX_2, 1, 1, 2);
setEffect(1, PITCHSHIFT, PITCHSHIFT_SHIFT, -10);
----

`PITCHSHIFT` permet simplement de diminuer ou d'augmenter le son d'un intervalle de hauteur spécifique (`PITCHSHIFT_SHIFT`). Cela peut être utile pour que plusieurs fichiers sonores sonnent mieux ensemble ou, au contraire, pour ajouter un peu de dissonance, si vous le souhaitez.

|===
|Paramètre |Description |Valeur par défaut |minValue |maxValue

|PITCHSHIFT_SHIFT |Indique le niveau d'ajustement de la hauteur du son d'origine en demi-tons (et fractions de demi-ton, exprimées par des valeurs après la virgule). 12 demi-tons correspondent à une octave. |0.0 |-12.0 |12.0

|BYPASS |When you bypass an effect, the effect turns off. Notez que contrairement aux autres paires de nom/paramètre, les seules valeurs valides pour BYPASS sont 0.0 et 1.0. |0.0 |0.0 |1.0
|===

[[reverb]]
=== REVERB

++++
<div class="effect-examples">
    <div class="audio-label">Avec effet :</div>
    <div class="curriculum-mp3">audioMedia/reverb_wet.mp3</div>
    <div class="audio-label">Sans effet :</div>
    <div class="curriculum-mp3">audioMedia/reverb_dry.mp3</div>
</div>
++++

[role="curriculum-python"]
[source,python]
----
from earsketch import *
fitMedia(EIGHT_BIT_ANALOG_DRUM_LOOP_001, 1, 1, 3)
setEffect(1, REVERB, REVERB_TIME, 2000)
setEffect(1, REVERB, REVERB_DAMPFREQ, 18000)
setEffect(1, REVERB, MIX, 0.5)
----

[role="curriculum-javascript"]
[source,javascript]
----
fitMedia(EIGHT_BIT_ANALOG_DRUM_LOOP_001, 1, 1, 3);
setEffect(1, REVERB, REVERB_TIME, 2000);
setEffect(1, REVERB, REVERB_DAMPFREQ, 18000);
setEffect(1, REVERB, MIX, 0.5);
----

`REVERB` adds a slowly decaying ambience to a sound, making it sound denser, dreamier, or as if it was recorded in a smaller or larger room than it actually was.

|===
|Paramètre |Description |Valeur par défaut |minValue |maxValue

|REVERB_TIME |Le temps de décroissance de l'ambiance en millisecondes (ms). Lors de la modulation de REVERB_TIME au fil du temps à l'aide de la courbe d'automation, en raison de la nature de la réverbération à convolution, la valeur n'est mise à jour que toutes les noires (time=0.25) à la manière d'un escalier à partir du point de départ de l'automation (cependant, ceci est à peine remarquable). (You will, however, hardly notice that.) |1500.0 |100.0 |4000.0

|REVERB_DAMPFREQ |La fréquence de coupure (en Hz) du filtre passe-bas appliqué à l'ambiance. Plus la valeur est basse, plus la réverbération donnera un effet sombre. |10000.0 |200.0 |18000.0

|MIX |Le pourcentage de son produit (avec effet) qui est mixé au son original (sans effet). À sa valeur minimale (0.0), aucun effet ne peut être entendu. À sa valeur maximale (1.0), aucun son original n'est entendu, il s'agit uniquement d'effets. |0.3 |0.0 |1.0

|BYPASS |When you bypass an effect, the effect turns off. Notez que contrairement aux autres paires de nom/paramètre, les seules valeurs valides pour BYPASS sont 0.0 et 1.0. |0.0 |0.0 |1.0
|===

[[ringmod]]
=== RINGMOD

++++
<div class="effect-examples">
    <div class="audio-label">Avec effet :</div>
    <div class="curriculum-mp3">audioMedia/ringmod_wet.mp3</div>
    <div class="audio-label">Sans effet :</div>
    <div class="curriculum-mp3">audioMedia/ringmod_dry.mp3</div>
</div>
++++

[role="curriculum-python"]
[source,python]
----
from earsketch import *
ffitMedia(YG_TECHNO_VOX_2, 1, 1, 2)
setEffect(1, RINGMOD, RINGMOD_MODFREQ, 100)
setEffect(1, RINGMOD, RINGMOD_FEEDBACK, 80)
setEffect(1, RINGMOD, MIX, 1)
----

[role="curriculum-javascript"]
[source,javascript]
----
fitMedia(YG_TECHNO_VOX_2, 1, 1, 2);
setEffect(1, RINGMOD, RINGMOD_MODFREQ, 100);
setEffect(1, RINGMOD, RINGMOD_FEEDBACK, 80);
setEffect(1, RINGMOD, MIX, 1);
----

`RINGMOD` multiplie les signaux provenant de deux sons en même temps : votre son original et une onde sinusoïdale pure (qui ressemble à un diapason). Certains réglages de paramètres pour cet effet produiront probablement des effets sonores reconnaissables, semblables à ceux utilisés dans les vieux films de science-fiction.

|===
|Paramètre |Description |Valeur par défaut |minValue |maxValue

|RINGMOD_MODFREQ |La fréquence (en Hz) de l'oscillateur sinusoïdal qui est multipliée dans votre son original. |40.0 |0.0 |100.0

|RINGMOD_FEEDBACK |La quantité du son produit qui est « réinjecté » dans l'effet. Des valeurs élevées créent plus de sons robotiques et d'artefacts sonores. |0.0 |0.0 |100.0

|MIX |Le pourcentage de son produit (avec effet) qui est mixé au son original (sans effet). À sa valeur minimale (0.0), aucun effet ne peut être entendu. À sa valeur maximale (1.0), aucun son original n'est entendu, il s'agit uniquement d'effets. |1.0 |0.0 |1.0

|BYPASS |When you bypass an effect, the effect turns off. Notez que contrairement aux autres paires de nom/paramètre, les seules valeurs valides pour BYPASS sont 0.0 et 1.0. |0.0 |0.0 |1.0
|===

[[tremolo]]
=== TREMOLO

++++
<div class="effect-examples">
    <div class="audio-label">Avec effet :</div>
    <div class="curriculum-mp3">audioMedia/tremolo_wet.mp3</div>
    <div class="audio-label">Sans effet :</div>
    <div class="curriculum-mp3">audioMedia/tremolo_dry.mp3</div>
</div>
++++

[role="curriculum-python"]
[source,python]
----
from earsketch import *
fitMedia(RD_UK_HOUSE_ACOUSTICGUITAR_1, 1, 1, 3)
setEffect(1, TREMOLO, TREMOLO_FREQ, 7.5)
setEffect(1, TREMOLO, TREMOLO_AMOUNT, -10)
setEffect(1, TREMOLO, MIX, 1)
----

[role="curriculum-javascript"]
[source,javascript]
----
fitMedia(RD_UK_HOUSE_ACOUSTICGUITAR_1, 1, 1, 3);
setEffect(1, TREMOLO, TREMOLO_FREQ, 7.5);
setEffect(1, TREMOLO, TREMOLO_AMOUNT, -10);
setEffect(1, TREMOLO, MIX, 1);
----

`TREMOLO` modifie rapidement le volume du son original alternativement de sa valeur initiale au silence, ce qui entraîne un effet de sonorité vacillante.

|===
|Paramètre |Description |Valeur par défaut |minValue |maxValue

|TREMOLO_FREQ |La fréquence (en Hz) à laquelle le volume est modifié dans les deux sens. |4.0 |0.0 |100.0

|TREMOLO_AMOUNT |Le niveau (en dB) pour lequel le volume change alternativement au cours de chaque cycle. |-6.0 |-60.0 |0.0

|MIX |Le pourcentage de son produit (avec effet) qui est mixé au son original (sans effet). À sa valeur minimale (0.0), aucun effet ne peut être entendu. À sa valeur maximale (1.0), aucun son original n'est entendu, il s'agit uniquement d'effets. |1.0 |0.0 |1.0

|BYPASS |When you bypass an effect, the effect turns off. Notez que contrairement aux autres paires de nom/paramètre, les seules valeurs valides pour BYPASS sont 0.0 et 1.0. |0.0 |0.0 |1.0
|===

[[volume]]
=== VOLUME

++++
<div class="effect-examples">
    <div class="audio-label">Avec effet :</div>
    <div class="curriculum-mp3">audioMedia/volume_wet.mp3</div>
    <div class="audio-label">Sans effet :</div>
    <div class="curriculum-mp3">audioMedia/volume_dry.mp3</div>
</div>
++++

[role="curriculum-python"]
[source,python]
----
from earsketch import *
fitMedia(EIGHT_BIT_ANALOG_DRUM_LOOP_001, 1, 1, 3)
setEffect(1, VOLUME, GAIN, -55, 1, 0, 3)
----

[role="curriculum-javascript"]
[source,javascript]
----
fitMedia(EIGHT_BIT_ANALOG_DRUM_LOOP_001, 1, 1, 3);
setEffect(1, VOLUME, GAIN, -55, 1, 0, 3);
----

`VOLUME` vous permet de modifier le volume d'un clip audio.

|===
|Paramètre |Description |Valeur par défaut |minValue |maxValue

|GAIN |Indique le niveau de volume de sortie du son original. |0.0 |-60.0 |12.0

|BYPASS |When you bypass an effect, the effect turns off. Notez que contrairement aux autres paires de nom/paramètre, les seules valeurs valides pour BYPASS sont 0.0 et 1.0. |0.0 |0.0 |1.0
|===

[[wah]]
=== WAH

++++
<div class="effect-examples">
    <div class="audio-label">Avec effet :</div>
    <div class="curriculum-mp3">audioMedia/wah_wet.mp3</div>
    <div class="audio-label">Sans effet :</div>
    <div class="curriculum-mp3">audioMedia/wah_dry.mp3</div>
</div>
++++

[role="curriculum-python"]
[source,python]
----
from earsketch import *
fitMedia(RD_UK_HOUSE_ACOUSTICGUITAR_1, 1, 1, 3)
setEffect(1, WAH, WAH_POSITION, 0, 1, 0.5, 2)
setEffect(1, WAH, WAH_POSITION, 0, 2, 0.5, 3)
setEffect(1, WAH, MIX, 1)
----

[role="curriculum-javascript"]
[source,javascript]
----
fitMedia(RD_UK_HOUSE_ACOUSTICGUITAR_1, 1, 1, 3);
setEffect(1, WAH, WAH_POSITION, 0, 1, 0.5, 2);
setEffect(1, WAH, WAH_POSITION, 0, 2, 0.5, 3);
setEffect(1, WAH, MIX, 1);
----

`WAH` est un filtre passe-bande résonant (voir l'effet `BANDPASS`) qui crée un son de pédale de type « wah-wah » lorsque modifié au fil du temps à l'aide d'enveloppes dans la fonction setEffect(). It is a resonant bandpass filter, which means it lowers the volume of high and low frequencies while boosting a narrow window of frequencies in the middle.

|===
|Paramètre |Description |Valeur par défaut |minValue |maxValue

|WAH_POSITION |La fréquence centrale de la gamme de fréquences à largeur fixe amplifiée. |0.0 |0.0 |1.0

|MIX |Le pourcentage de son produit (avec effet) qui est mixé au son original (sans effet). À sa valeur minimale (0.0), aucun effet ne peut être entendu. À sa valeur maximale (1.0), aucun son original n'est entendu, il s'agit uniquement d'effets. |1.0 |0.0 |1.0

|BYPASS |When you bypass an effect, the effect turns off. Notez que contrairement aux autres paires de nom/paramètre, les seules valeurs valides pour BYPASS sont 0.0 et 1.0. |0.0 |0.0 |1.0
|===