[[ch_29]]
== Har Bir Xatoning Batafsil Tavsifi

:nofooter:

[[othererrors]]
=== Umumiy Ma'lumot

Ba'zida dasturchilar kodning noto'g'ri ishlashiga yoki umuman ishlamasligiga olib keladigan xatolarga yo'l qo'yishadi. Dasturlashda kodlash xatoliklari *xatolar* yoki *nosozliklar* deb ataladi.

Xatolarni topish va tuzatish jarayoni *Nosozliklarni tuzatish* deb ataladi.

Konsolda xato haqidagi izohni va satr nomerini ko'rib chiqing. Ba'zan, nosozlikni tuzatish uchun belgilangan satrdan oldingi satrni o'zgartirish kerak boladi. Konsol dagi ma'lumotni va satr raqamini koring. Ba'zan nosozlikni tuzatish uchun ko'rsatilgan satrdan oldingi satrni tuzatish kerak bo'ladi.

Quyidagi bo'limda, eng ko'p tarqalgan nosozliklarni tuzatish xaqida ma'lumot berilgan.

[role="curriculum-python"]
Rasmiy https://docs.python.org/3/library/exceptions.html#concrete-exceptions[Python documentation^] saxifasida, barcha xatolar ro'yxati va tavsifini ko'rishingiz mumkin.

[role="curriculum-javascript"]
Mozilla'ning https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors[JavaScript documentation^] saxifasida, barcha xatolar ro'yxati va tavsifini korishingiz mumkin.

[[modulenotfounderror]]
=== Modul Topilmadi Xatosi

//Python only

[role="curriculum-python"]
*Konsol xabari:* ModuleNotFoundError: 'mavjud_bolmagan_modul_nomi' moduli mavjud emas

[role="curriculum-python"]
*Izoh:" Modul topilmaganligi xatosi (ya'ni ModuleNotFoundError) bayonotida keltirilgan dastur modulni yuklay olmaganida import xatosi yuzaga keladi. Masalan, `from module import`. Buning sababi imlo xatosi bo'lishi mumkin yoki import qilinadigan modul mavjud emas.

[role="curriculum-python"]
*Misol:* Quyidagi parcha "EarSketch" so'zini odatdagi uslub bilan ko'rsatsa-da, Python modullaribing barchasi kichik harflarda ko'rsatilgan.

////
Can't turn off pasted without this appearing in JS mode.
////

[role="curriculum-python"]
[source,python]
----
include::code-examples/every-error-explained-in-detail-import-error.py.txt[]
----

[role="curriculum-python"]
Buning o'rniga bizning bayonotimiz quyidagicha o'qilishi kerak:

[role="curriculum-python"]
[source,python]
----
include::code-examples/every-error-explained-in-detail-import-error-correction.py.txt[]
----

[role="curriculum-python"]
*Yechim:* Skriptingizning yuqori qismidagi 'from...import'-da imlo va katta-kichik harf xatolari mavjudligini tekshiring.

[role="curriculum-javascript"]
Import xatoliklari JavaScript-da uchramaydi. Bu turdagi xatoning izohini korish uchun Python skriptini oching yoki bo yerga o'ting <<every-error-explained-in-detail#othererrors>>.

[[indentationerror]]
=== Chekinish Xatosi

//Python only

[role="curriculum-python"]
*Konsol xabari:* IndentationError: kodda chekinish xatosi mavjud (bo'shliq qoldirilmagan yoki ortiqcha bo'shliq mavjud).

[role="curriculum-python"]
*Izoh:* Yodda tutingki, Python-da halqalar, funktsiyalar va ikki nuqta (':') bilan tugaydigan har qanday bayonot kabi shartli bayonotlardan foydalanganda to'g'ri chekinishga ehtiyoj tug'iladi. Chekinish miqdoridan noto'g'ri foydalanilganda, ya'ni yetarli emas yoki keragidan ortiq bo'lsa, chekinish xatosi yuzaga keladi.

[role="curriculum-python"]
`Misol:` EarSketch Kod Muharriri avtomatik ravishda ikki nuqtadan keyin kod satrlarini cheklaydi, lekin dasturchi kod qismiga o'zgartirishlar kiritishda tasodifan cheklovni qo'lda o'zgartirishi mumkin. Quyidagi parchada foydalanuvchiga ham, tahlil qiluvchiga ham qaysi qatorlar halqaga tushishi aniq emas.

////
Can't turn off pasting without this appearing in JS mode
////

[role="curriculum-python"]
[source,python]
----
include::code-examples/every-error-explained-in-detail-indentation-error.py.txt[]
----

[role="curriculum-python"]
To'g'ri chekintirilgan tana (ya'ni kodning asosiy qismi) quyidagi parcha ko'rinishida bo'lishi kerak. For-halqasi tanasi bitta tab bilan chekintirilgan va oxirgi `fitMedia()` chaqiruvi halqadan tashqarida ekanligi aniq.

[role="curriculum-python"]
[source,python]
----
include::code-examples/every-error-explained-in-detail-indentation-error-correction.py.txt[]
----

[role="curriculum-python"]
`Yechim:` Har bir satr kod muharririning chap chetiga suyangan boʻlishi uchun kod tanasidagi barcha boʻshliqlarni oʻchirib koʻring. So'ngra, tanani satr bo'ylab ichkariga chekintiring va barcha chekinishlar sobit bo'lishiga ishonch hosil qiling.

[role="curriculum-javascript"]
JavaScript-da chekinish xatolari yuzaga kelmaydi, ammo o'qish qulayligi uchun to'g'ri chekinishdan foydalanish kerak. Bu turdagi xatoning izohini korish uchun Python skriptini oching yoki bo yerga o'ting <<every-error-explained-in-detail#indexerror,index errors>>.

[[indexerror]]
=== Indeks Xatosi

[role="curriculum-python"]
*Konsol xabari:* IndexError: Diapazondan tashqari indeksni ishlatishda xatolik yuz berdi.

[role="curriculum-javascript"]
*Konsol xabari:* TypeError: Diapazondan tashqari indeksni ishlatishda xatolik yuz berdi.

[role="curriculum-python"]
*Izoh:* Ro'yxat yoki satrda mavjud bo'lmagan yoki diapazondan tashqarida bo'lgan indeksga kirishga urinayotganda indeks xatosi yuzaga keladi.

[role="curriculum-javascript"]
*Izoh:* Massiv yoki satrda mavjud bo'lmagan yoki diapazondan tashqarida bo'lgan indeksga kirishga urinayotganda indeks xatosi yuzaga keladi. Bu JavaScript-da tur xatosi sifatida paydo bo'ladi. For an explanation of more general type errors, see the section on <<every-error-explained-in-detail#typeerror,type errors>>.

[role="curriculum-python"]
*Example:* In the following code, we attempt to create an additive structure using clips from a list.

[role="curriculum-javascript"]
*Example:* In the following code, we attempt to create an additive structure using clips from an array.

[role="curriculum-python"]
[source,python]
----
include::code-examples/every-error-explained-in-detail-index-error.py.txt[]
----

[role="curriculum-javascript"]
[source,javascript]
----
include::code-examples/every-error-explained-in-detail-index-error.js.txt[]
----

[role="curriculum-python"]
An Index Error is thrown and the console points us to line 19, stating the index is out of range. We have three sound clips, but we forgot that list indices start at 0, so the last index we should be accessing is index 2:

[role="curriculum-javascript"]
A Type Error is thrown and the console states that a different data type was expected on line 17. An out of range value was provided to the last `fitMedia()` call. We have three sound clips, but we forgot that array indices start at 0, so the last index we should be accessing is index 2:

[role="curriculum-python"]
[source,python]
----
include::code-examples/every-error-explained-in-detail-index-error-correction.py.txt[]
----

[role="curriculum-javascript"]
[source,javascript]
----
include::code-examples/every-error-explained-in-detail-index-error-correction.js.txt[]
----

[role="curriculum-python"]
*Solution:* Write down the name of each clip in your list and label each with its associated index, starting at 0. This helps you understand the structure of the list and what may be causing an index error.

[role="curriculum-javascript"]
*Solution:* Write down the name of each clip in your array and label each with its associated index, starting at 0. This helps you understand the structure of the array and what may be causing an index error.

[[nameerror]]
=== Nom Xatosi

[role="curriculum-python"]
*Konsol xabari:* Oʻzgaruvchi yoki funktsiya nomi bilan bogʻliq aniqlanmagan xatolik mavjud.

[role="curriculum-javascript"]
*Konsol xabari:* Oʻzgaruvchi yoki funktsiya nomi bilan bogʻliq aniqlanmagan xatolik mavjud.

[role="curriculum-python"]
*Izoh:* Nom xatosi dastur o'zgaruvchidan foydalanishga yoki hech qachon aniqlanmagan funktsiyani chaqirishga harakat qilganda, ko'pincha imlo xatosi tufayli yuzaga keladi.

Ko'pincha, skriptning eng tepasida `from earsketch import *` degan ifoda yozilmagan boladi va bu xatolikga keltiradi.

[role="curriculum-javascript"]
*Izoh:* Nom xatosi dastur o'zgaruvchidan foydalanishga yoki hech qachon aniqlanmagan funktsiyani chaqirishga harakat qilganda, ko'pincha imlo xatosi tufayli yuzaga keladi. JavaScript bu turdagi xatoliklarni ishora xatosi deb ko'rsatadi.

[role="curriculum-python"]
*Misol:* Quyida `bugun` o'zgaruvchisiga tayinlangan satrni chop etish uchun oddiy skript keltirilgan. Biroq, chop etish bayonotidagi xato skriptning ishlashiga to'sqinlik qiladi.

[role="curriculum-javascript"]
*Misol:* Quyida `bugun` o'zgaruvchisiga tayinlangan satrni chop etish uchun oddiy skript keltirilgan. Biroq, `println()` funktsiyasidagi xatolik skriptning ishlashiga xalaqit beradi.

[role="curriculum-python"]
[source,python]
----
include::code-examples/every-error-explained-in-detail-name-error.py.txt[]
----

[role="curriculum-javascript"]
[source,javascript]
----
include::code-examples/every-error-explained-in-detail-reference-error.js.txt[]
----

Bunday holda, yopishtirilgan satrni o'z ichiga olgan o'zgaruvchi to'g'ri nom bilan atalmagan; kichik “t” harfi ishlatilishi kerak edi.

[role="curriculum-python"]
[source,python]
----
include::code-examples/every-error-explained-in-detail-name-error-correction.py.txt[]
----

[role="curriculum-javascript"]
[source,javascript]
----
include::code-examples/every-error-explained-in-detail-reference-error-correction.js.txt[]
----

*Yechim:* Oʻzgaruvchilar va funktsiyalaringizning imlosi va katta-kichik harflarini tekshiring. O'zgaruvchidan foydalanganda yoki funktsiyani chaqirganda, har birining avval aniqlanganligiga ishonch hosil qiling. Funktsiyani chaqirishdan oldin uni aniqlaganingizga ishonch hosil qiling. Nomlarni to'g'ridan-to'g'ri joylashtirishingiz mumkin bo'lsa-da, tovush konstantasi nomlari Tovush Brauzeridagi klip nomlari bilan mos kelishiga ishonch hosil qiling.

[[parseerror]]
=== Tahlil Xatosi

[role="curriculum-python"]
*Konsol xabari:* ParseError: kodni o'qishda xatolik yuz berdi.

[role="curriculum-python"]
*Izoh:* *Tahrirlash* axborotning bir shaklini boshqasiga aylantirishni bildiradi. Shuning uchun, interpretator sizning kodingizni kompyuter musiqa yaratishi uchun foydalanishi mumkin bo'lgan ma'lumotga aylantira olmaydi va tahlil qilish xatosi paydo bo'ladi. Burchakli qavslar va oddiy qavslar kabi kodni formatlash ko'pincha tahlil xatosiga sabab bo'ladi.

[role="curriculum-python"]
*Masalan:* Quyidagi misolda biz musiqa ustida ijro etish uchun tasodifiy zarbalarni tanlash orqali biroz zavqlanishga harakat qilamiz, lekin kodning ishlashiga nimadir xalaqit bermoqda.

[role="curriculum-python"]
[source,python]
----
include::code-examples/every-error-explained-in-detail-parse-error.py.txt[]
----

////
The parse error included in the example above breaks AsciiDoc syntax highlighting here for some reason. Same happens in Ch. 3. If removed while editing, the closing parentheses of selectRandomFile() should be omitted.
////

[role="curriculum-python"]
Kodni ishga tushirgandan so'ng, konsol bizni 26-qatorga ishora qiladi. Bu qator yaxshi ko'rinadi, lekin avvalgi qatordagi `selectRandomFile()` funktsiyasida yopish qavslari yo'q. Ko'p hollarda tahlil xatolari tezda tuzatilishi mumkin.

[role="curriculum-python"]
[source,python]
----
include::code-examples/every-error-explained-in-detail-parse-error-correction.py.txt[]
----

[role="curriculum-python"]
*Yechim:* Konsolni buzuvchi chiziq qayerda bo'lishi mumkinligini tekshiring. Barcha funktsiya taʼriflari, funktsiya chaqiruvlari va boshqa ifodalarda ochish va yopish qavslari borligiga ishonch hosil qiling. Skriptingizning boshqa joylarida yetishmayotgan yoki ortiqcha tinish belgilarini tekshiring. Bundan tashqari, yetishmayotgan funktsiya ta'riflari va argumentlarini tekshiring. Va nihoyat, funktsiyalarga o'tadigan argumentlarning imlosini tekshiring.

[role="curriculum-javascript"]
JavaScript'da tahlil xatolari umuman olganda sintaksis xatolari deb talqin qilinadi. Bular keyingi qismda korib chiqiladi <<every-error-explained-in-detail#syntaxerror,next>>.

[[syntaxerror]]
=== Sintaksis Xatosi

*Konsol xabari:* Sintaksis xatosi: kod sintaksisi (yoki tartibga solish) bilan bog'liq xatolik bor.

*Izoh:* Sintaksis xatosi dastur skript sintaksisida, ma'lum bir til qoidalarida xatolikka duch kelganida yuzaga keladi.

*Misol:* Quyidagi skript dinamik ravishda o'zgaruvchan futuristik signallarni yaratishi kerak. Biroq, unda sintaksis xatolariga olib keladigan ikkita keng tarqalgan nosozlik mavjud.

[role="curriculum-python"]
[source,python]
----
include::code-examples/every-error-explained-in-detail-syntax-error.py.txt[]
----

[role="curriculum-javascript"]
[source,javascript]
----
include::code-examples/every-error-explained-in-detail-syntax-error.js.txt[]
----

[role="curriculum-python"]
Ushbu skript uchun kod muharriri bizga noto'g'ri satrni belgilaydi. E'tibor bering, biz _if_ bayonotimizni ikki nuqta bilan tugatishni unutib qo'ydik. Xuddi shu qatorda biz bekor yaroqsiz shartni ham berdik; Biz tayinlash operatori `=` o'rniga tenglik operatoridan `==` foydalanishimiz kerak.

[role="curriculum-javascript"]
Ushbu skript uchun kod muharriri bizga noto'g'ri satrni belgilaydi. E'tibor bering, biz _if_ bayonotining asosiy qismini jingalak qavs bilan ochishni unutganmiz. Xuddi shu qatorda biz bekor yaroqsiz shartni ham berdik; Biz tayinlash operatori `=` o'rniga tenglik operatoridan `===` foydalanishimiz kerak.

[role="curriculum-python"]
[source,python]
----
include::code-examples/every-error-explained-in-detail-syntax-error-correction.py.txt[]
----

[role="curriculum-javascript"]
[source,javascript]
----
include::code-examples/every-error-explained-in-detail-syntax-error-correction.js.txt[]
----

[role="curriculum-python"]
*Yechim:* Har doim konsol va kod muharririda ishoralar yordamidan foydalaning. Yuqorida keltirilgan keng tarqalgan xatolardan tashqari, qo'shtirnoqlarni ochish va yopishni tekshiring va Python kalit so'zlarini o'zgaruvchi nomlar sifatida ishlatmaganingizga ishonch hosil qiling.

////
Added solution from parse error to JS version below.
////

[role="curriculum-javascript"]
*Yechim:* Har doim konsol va kod muharririda ishoralar yordamidan foydalaning.
Yuqorida keltirilgan keng tarqalgan xatolardan tashqari, qo'shtirnoqlarni ochish va yopishni tekshiring va barcha funktsiya ta'riflari, funktsiya chaqiruvlari va boshqa iboralarda ochilish va yopish qavslari mavjudligiga ishonch hosil qiling. Shuningdek, skriptingizning boshqa joylarida yetishmayotgan yoki ortiqcha tinish belgilarini tekshiring. Bundan tashqari, yetishmayotgan funktsiya ta'riflari va argumentlarini tekshiring. JavaScript-ning zahiraga olgan soʻzlaridan oʻzgaruvchi nomlari sifatida foydalana olmaysiz. Va nihoyat, funktsiyalarga o'tadigan argumentlarning imlosini tekshiring.

[[typeerror]]
=== Tur Xatosi

*Konsol xabari:* TypeError: Kutilayotgan maʼlumotlar turida xatolik yuz berdi.

*Izoh:* Ma'lum bir operatsiya yoki funktsiya bitta ma'lumot turini kutayotgan vaqtda boshqa ma'lumot turini qabul qilsa, tur xatosi yuzaga keladi.

[role="curriculum-python"]
*Misol:* Faraz qilaylik, siz yangilanayotgan oʻzgaruvchi bilan foydalanilgan umumiy oʻlchovlarni kuzatib boruvchi skript yozdingiz. Quyidagi parchada biz qo'shiqning uzunligi ko'rsatilgan xabarni chop etishga harakat qilamiz.

[role="curriculum-javascript"]
*Misol:* Siz qo'shiq uzunligini aniqlash uchun foydalanuvchi ma'lumotlarini talab qiladigan skript yozdingiz deylik. Foydalanuvchi qiymati `fitMedia()` ga uzatiladi.

[role="curriculum-python"]
[source,python]
----
include::code-examples/every-error-explained-in-detail-type-error.py.txt[]
----

[role="curriculum-javascript"]
[source,javascript]
----
include::code-examples/every-error-explained-in-detail-type-error.js.txt[]
----

[role="curriculum-python"]
Raqam turini satrga yopishtirib bo'lmagani uchun tur xatosi yuzaga kelgan. Buning o'rniga, avval `measureTotal` qiymatini satrga aylantirish uchun ma'lumotlar turini o'zgartirishdan foydalanishimiz mumkin:

[role="curriculum-javascript"]
Biz tasodifan satrni oxirgi `fitMedia()` argumenti sifatida o'tkazib yuborganimiz uchun tur xatosi yuzaga keldi. Buning o'rniga, avval `measureTotal` satrini raqamga aylantirish uchun ma'lumotlar turini o'zgartirishdan foydalanishimiz mumkin:

[role="curriculum-python"]
[source,python]
----
include::code-examples/every-error-explained-in-detail-type-error-correction.py.txt[]
----

[role="curriculum-javascript"]
[source,javascript]
----
include::code-examples/every-error-explained-in-detail-type-error-correction.js.txt[]
----

`Yechim:` EarSketch konsoli qoidabuzar ma'lumot turlarini beradi va ma'lum bir qator raqamiga ishora qiladi. Arifmetik ifodalar, ma'lumotlar tuzilmasi operatsiyalari va funktsiya argumentlari ichida izchil ma'lumot turlarini tekshiring. Bundan tashqari, funktsiya chaqiruvlaringiz to'g'ri argumentlar soniga ega ekanligiga ishonch hosil qiling.

////
(ex. trying to concatenate something into string that isn't string, modifying a string value instead of concatenating something in, function call with too few arguments)
////

[[valueerror]]
=== Qiymat Xatosi

[role="curriculum-python"]
*Konsol xabari:* ValueError: Berilgan argument funktsiya uchun qabul qilinadigan qiymatlar to‘plami yoki oralig‘ida emas.

[role="curriculum-javascript"]
*Konsol xabari:* RangeError: Berilgan argument funktsiya uchun qabul qilinadigan qiymatlar to‘plami yoki oralig‘ida emas.

[role="curriculum-python"]
*Izoh:* Qiymat xatosi funktsiya to'g'ri turdagi, lekin nomaqbul qiymatdagi argumentni qabul qilganda yuzaga keladi.

[role="curriculum-javascript"]
*Izoh:* Qiymat xatosi funktsiya to'g'ri turdagi, lekin nomaqbul qiymatdagi argumentni qabul qilganda yuzaga keladi. JavaScript bu turdagi xatoliklarni diapazon xatosi deb ataydi.

[role="curriculum-python"]
*Misol:* Quyidagi parcha `makeBeat()` yordamida roʻyxatlar bilan qiziqarli zarba yaratishga harakat qiladi.

[role="curriculum-javascript"]
*Misol:* Quyidagi parcha `MakeBeat()` yordamida massivlar bilan qiziqarli zarba yaratishga harakat qiladi.

[role="curriculum-python"]
[source,python]
----
include::code-examples/every-error-explained-in-detail-value-error.py.txt[]
----

[role="curriculum-javascript"]
[source,javascript]
----
include::code-examples/every-error-explained-in-detail-range-error.js.txt[]
----

[role="curriculum-python"]
`makeBeat()` ning toʻrtinchi argumenti mos turga ega, lekin u kirishi kerak boʻlgan indeks qiymatlaridan biri yaroqsiz. Ushbu stsenariyda dasturchi ro'yxat indekslari noldan boshlanishini unutgan bo'lishi mumkin.

[role="curriculum-javascript"]
`makeBeat()` ning toʻrtinchi argumenti mos turga ega, lekin u kirishi kerak boʻlgan indeks qiymatlaridan biri yaroqsiz. Ushbu stsenariyda dasturchi massiv indekslari noldan boshlanishini unutgan bo'lishi mumkin.

[role="curriculum-python"]
[source,python]
----
include::code-examples/every-error-explained-in-detail-value-error-correction.py.txt[]
----

[role="curriculum-javascript"]
[source,javascript]
----
include::code-examples/every-error-explained-in-detail-range-error-correction.js.txt[]
----

*Yechim:* Qiymatlar to'g'ri diapazonga tushishiga ishonch hosil qilish uchun zarba satrlarini tekshiring. Shuningdek, `setEffect()` ga taqdim etilgan har qanday argumentlar effektning talab qilinadigan diapazonida ekanligini tasdiqlang.