[[ch_28]]
== הסבר מפורט לכל אפקט

:nofooter:

[[bandpass]]
=== BANDPASS

++++
<div class="effect-examples">
    <div class="audio-label">With Effect:</div>
    <div class="curriculum-mp3">audioMedia/bandpass_wet.mp3</div>
    <div class="audio-label">Without Effect:</div>
    <div class="curriculum-mp3">audioMedia/bandpass_dry.mp3</div>
</div>
++++

[role="curriculum-python"]
[source,python]
----
from earsketch import *
fitMedia(RD_UK_HOUSE_ACOUSTICGUITAR_1, 1, 1, 3)
setEffect(1, BANDPASS, BANDPASS_FREQ, 1000)
setEffect(1, BANDPASS, BANDPASS_RESONANCE, 0.9)
setEffect(1, BANDPASS, MIX, 1)
----

[role="curriculum-javascript"]
[source,javascript]
----
fitMedia(RD_UK_HOUSE_ACOUSTICGUITAR_1, 1, 1, 3);
setEffect(1, BANDPASS, BANDPASS_FREQ, 1000);
setEffect(1, BANDPASS, BANDPASS_RESONANCE, 0.9);
setEffect(1, BANDPASS, MIX, 1);
----

`BANDPASS` is a filter that only lets through (passes) an adjustable window (band) of frequencies. שאר התדרים מונחתים. By creating a narrower band of frequencies (setting `BANDPASS_RESONANCE` closer to 1), you can make a telephone or megaphone-like sound. By creating a wider band of frequencies (setting `BANDPASS_RESONANCE` closer to 0), you can make sounds that seem overpowering blend better with other sounds in the mix.

|===
|פרמטר |תיאור |ערך ברירת-מחדל |minValue |maxValue

|BANDPASS_FREQ |התדר המרכזי (בהרץ) של חלון התדרים המועברים. |800.0 |20.0 |20000.0

|BANDPASS_RESONANCE |The boost of frequncies around the BANDPASS_FREQ level. Higher values of resonance strongly boost a small window (band)of frequencies, while lower values of resonance subtly boost a larger window (band). |0.5 |0.0 |1.0

|MIX |The amount of the sound effect that is mixed into the original sound. At the minimum value 0.0, it only plays the original ("dry") audio. At the maximum value 1.0, it only plays the affected ("wet") audio. |0.1 |0.0 |1.0

|BYPASS |When you bypass an effect, the effect turns off. The only valid values for `BYPASS` are 1.0 (to turn the effect off) and 0.0 (to keep the effect on). |0.0 |0.0 |1.0
|===

[[chorus]]
=== CHORUS

++++
<div class="effect-examples">
    <div class="audio-label">With Effect:</div>
    <div class="curriculum-mp3">audioMedia/chorus_wet.mp3</div>
    <div class="audio-label">Without Effect:</div>
    <div class="curriculum-mp3">audioMedia/chorus_dry.mp3</div>
</div>
++++

[role="curriculum-python"]
[source,python]
----
from earsketch import *
fitMedia(YG_TECHNO_VOX_2, 1, 1, 2)
setEffect(1, CHORUS, CHORUS_LENGTH, 15)
setEffect(1, CHORUS, CHORUS_NUMVOICES, 1)
setEffect(1, CHORUS, CHORUS_RATE, 10)
setEffect(1, CHORUS, MIX, 0.5)
----

[role="curriculum-javascript"]
[source,javascript]
----
fitMedia(YG_TECHNO_VOX_2, 1, 1, 2);
setEffect(1, CHORUS, CHORUS_LENGTH, 15);
setEffect(1, CHORUS, CHORUS_NUMVOICES, 1);
setEffect(1, CHORUS, CHORUS_RATE, 10);
setEffect(1, CHORUS, MIX, 0.5);
----

`CHORUS` creates a subtle ensemble-like effect by making various copies of the sound, changing them slightly in pitch, and mixing them back into the sound.

|===
|פרמטר |תיאור |ערך ברירת-מחדל |minValue |maxValue

|CHORUS_LENGTH |משך הזמן (במילישניות) מהצליל המקורי בו הופעל אפקט ה-chorus. |15.0 |1.0 |250.0

|CHORUS_NUMVOICES |מספר העותקים של הצליל המקורי. ערכים גבוהים יוצרים אפקט דמוי אנסמבל. |1.0 |1.0 |8.0

|CHORUS_RATE |The rate (in Hz) which the pitch cycles or "wobbles" at. ערכים נמוכים יוצרים צלילים במחזורים חלקים, בעוד ערכים גבוהים יוצרים אפקט של צלילים רוטטים. |0.5 |0.1 |16.0

|CHORUS_MOD |עומק הרטט של גובה הצליל (כלומר, כמה מחזוריות של גובה הצליל בשימוש). ערכים נמוכים יוצרים צליל טבעי יותר, בעוד שערכים גבוהים יוצרים צליל מלאכותי יותר. |0.7 |0.0 |1.0

|MIX |The amount of the sound effect that is mixed into the original sound. At the minimum value 0.0, it only plays the original ("dry") audio. At the maximum value 1.0, it only plays the affected ("wet") audio. |1.0 |0.0 |1.0

|BYPASS |When you bypass an effect, the effect turns off. The only valid values for `BYPASS` are 1.0 (to turn the effect off) and 0.0 (to keep the effect on). |0.0 |0.0 |1.0
|===

[[compressor]]
=== COMPRESSOR

++++
<div class="effect-examples">
    <div class="audio-label">With Effect:</div>
    <div class="curriculum-mp3">audioMedia/compressor_wet.mp3</div>
    <div class="audio-label">Without Effect:</div>
    <div class="curriculum-mp3">audioMedia/compressor_dry.mp3</div>
</div>
++++

[role="curriculum-python"]
[source,python]
----
from earsketch import *
fitMedia(EIGHT_BIT_ANALOG_DRUM_LOOP_001, 1, 1, 3)
setEffect(1, COMPRESSOR, COMPRESSOR_THRESHOLD, -30)
setEffect(1, COMPRESSOR, COMPRESSOR_RATIO, 100)
----

[role="curriculum-javascript"]
[source,javascript]
----
fitMedia(EIGHT_BIT_ANALOG_DRUM_LOOP_001, 1, 1, 3);
setEffect(1, COMPRESSOR, COMPRESSOR_THRESHOLD, -30);
setEffect(1, COMPRESSOR, COMPRESSOR_RATIO, 100);
----

`COMPRESSOR` reduces the volume of the loudest sections of a sound and amplifies the quietest sections. This creates a smaller dynamic range, which means that the volume of the track stays more constant throughout. Music producers often use compressors to fine-tune and add “punch” to drums.

|===
|פרמטר |תיאור |ערך ברירת-מחדל |minValue |maxValue

|COMPRESSOR_THRESHOLD |רמת העוצמה (ב-dB) מעליה הקומפרסור יתחיל להנחית. |-18.0 |-30.0 |0.0

|COMPRESSOR_RATIO |רמת ההנחתה. A ratio of 3:1 means that if the original sound is 3 dB over the threshold, then the affected sound will be 1 dB over the threshold. |10.0 |1.0 |100.0

|BYPASS |When you bypass an effect, the effect turns off. The only valid values for `BYPASS` are 1.0 (to turn the effect off) and 0.0 (to keep the effect on). |0.0 |0.0 |1.0
|===

[[delay]]
=== DELAY

++++
<div class="effect-examples">
    <div class="audio-label">With Effect:</div>
    <div class="curriculum-mp3">audioMedia/delay_wet.mp3</div>
    <div class="audio-label">Without Effect:</div>
    <div class="curriculum-mp3">audioMedia/delay_dry.mp3</div>
</div>
++++

[role="curriculum-python"]
[source,python]
----
from earsketch import *
fitMedia(YG_TECHNO_VOX_2, 1, 1, 3)
setEffect(1, DELAY, DELAY_TIME, 370)
setEffect(1, DELAY, DELAY_FEEDBACK, -3.5)
setEffect(1, DELAY, MIX, 1)
----

[role="curriculum-javascript"]
[source,javascript]
----
fitMedia(YG_TECHNO_VOX_2, 1, 1, 3);
setEffect(1, DELAY, DELAY_TIME, 370);
setEffect(1, DELAY, DELAY_FEEDBACK, -3.5);
setEffect(1, DELAY, MIX, 1);
----

`DELAY` creates a repeated echo of the original sound. It does this by playing the original sound as well as a delayed, quieter version of the original. After this first echo, it plays an echo of the echo (quieter than the first), then an echo of the echo of the echo (even quieter), and so on. If you set the time between each echo (`DELAY_TIME`) to the length of a beat, you can create an interesting rhythmic effect.

|===
|פרמטר |תיאור |ערך ברירת-מחדל |minValue |maxValue

|DELAY_TIME |אורך הזמן במילישניות (ms) שהערוץ המקורי מעוכב, והזמן בין חזרות עוקבות של העיכוב. |300.0 |0.0 |4000.0

|DELAY_FEEDBACK |מספר החזרות היחסי שיוצר האפקט. Higher values create more "echoes". Be careful of applying "too much" feedback! |-3.0 |-120.0 |-1.0

|MIX |The amount of the sound effect that is mixed into the original sound. At the minimum value 0.0, it only plays the original ("dry") audio. At the maximum value 1.0, it only plays the affected ("wet") audio. |0.5 |0.0 |1.0

|BYPASS |When you bypass an effect, the effect turns off. The only valid values for `BYPASS` are 1.0 (to turn the effect off) and 0.0 (to keep the effect on). |0.0 |0.0 |1.0
|===

[[distortion]]
=== DISTORTION

++++
<div class="effect-examples">
    <div class="audio-label">With Effect:</div>
    <div class="curriculum-mp3">audioMedia/distortion_wet.mp3</div>
    <div class="audio-label">Without Effect:</div>
    <div class="curriculum-mp3">audioMedia/distortion_dry.mp3</div>
</div>
++++

[role="curriculum-python"]
[source,python]
----
from earsketch import *
fitMedia(RD_UK_HOUSE_ACOUSTICGUITAR_1, 1, 1, 3)
setEffect(1, DISTORTION, DISTO_GAIN, 27)
setEffect(1, DISTORTION, MIX, 1)
----

[role="curriculum-javascript"]
[source,javascript]
----
fitMedia(RD_UK_HOUSE_ACOUSTICGUITAR_1, 1, 1, 3);
setEffect(1, DISTORTION, DISTO_GAIN, 27);
setEffect(1, DISTORTION, MIX, 1);
----

`DISTORTION` adds a dirty, fuzzy, and gritty effect to a sound by overdriving it, which clips the sound wave and adds overtones (higher frequencies related to the original sound). `DISTORTION` is commonly used on electric guitars in rock and grunge music, but you can use it for many different sounds.

|===
|פרמטר |תיאור |ערך ברירת-מחדל |minValue |maxValue

|DISTO_GAIN |כמות הגברת-היתר של הצליל המקורי. |20.0 |0.0 |50.0

|MIX |The amount of the sound effect that is mixed into the original sound. At the minimum value 0.0, it only plays the original ("dry") audio. At the maximum value 1.0, it only plays the affected ("wet") audio. |1.0 |0.0 |1.0

|BYPASS |When you bypass an effect, the effect turns off. The only valid values for `BYPASS` are 1.0 (to turn the effect off) and 0.0 (to keep the effect on). |0.0 |0.0 |1.0
|===

[[eq3band]]
=== EQ3BAND

++++
<div class="effect-examples">
    <div class="audio-label">With Effect:</div>
    <div class="curriculum-mp3">audioMedia/eq3band_wet.mp3</div>
    <div class="audio-label">Without Effect:</div>
    <div class="curriculum-mp3">audioMedia/eq3band_dry.mp3</div>
</div>
++++

[role="curriculum-python"]
[source,python]
----
from earsketch import *
fitMedia(EIGHT_BIT_ANALOG_DRUM_LOOP_001, 1, 1, 3)
setEffect(1, EQ3BAND, EQ3BAND_LOWGAIN, -15)
setEffect(1, EQ3BAND, EQ3BAND_MIDGAIN, -5)
setEffect(1, EQ3BAND, EQ3BAND_HIGHGAIN, 15)
setEffect(1, EQ3BAND, EQ3BAND_HIGHFREQ, 2000)
setEffect(1, EQ3BAND, MIX, 1)
----

[role="curriculum-javascript"]
[source,javascript]
----
fitMedia(EIGHT_BIT_ANALOG_DRUM_LOOP_001, 1, 1, 3);
setEffect(1, EQ3BAND, EQ3BAND_LOWGAIN, -15);
setEffect(1, EQ3BAND, EQ3BAND_MIDGAIN, -5);
setEffect(1, EQ3BAND, EQ3BAND_HIGHGAIN, 15);
setEffect(1, EQ3BAND, EQ3BAND_HIGHFREQ, 2000);
setEffect(1, EQ3BAND, MIX, 1);
----

`EQ3BAND` is a three-band equalizer, which is a tool used to adjust the volume of three separate frequency ranges in an audio track: bass, midrange, and treble (low, mid, high). EQ is used in music production to get rid of unwanted frequencies, create balance between tracks to get a radio-ready mix, or simply change the "vibe" of a sound.

|===
|פרמטר |תיאור |ערך ברירת-מחדל |minValue |maxValue

|EQ3BAND_LOWGAIN |ההגבר (dB) של טווח התדרים הנמוכים. ערכים שליליים מקטינים את העוצמה של התדרים הנמוכים. ערכים חיוביים מגבירים אותה. |0.0 |-24.0 |18.0

|EQ3BAND_LOWFREQ |קובע את התדר הגבוה (Hz) של פס התדרים הנמוך. |200.0 |20.0 |20000.0

|EQ3BAND_MIDGAIN |ההגבר (dB) של פס התדרים האמצעי. ערכים שליליים מקטינים את העוצמה של התדרים האמצעיים. ערכים חיוביים מגבירים אותה. |0.0 |-24.0 |18.0

|EQ3BAND_MIDFREQ |קובע את התדר המרכזי (Hz) של פס התדרים האמצעי. |2000.0 |20.0 |20000.0

|EQ3BAND_HIGHGAIN |ההגבר (dB) של טווח התדרים הגבוהים. ערכים שליליים מקטינים את העוצמה של התדרים הגבוהים. ערכים חיוביים מגבירים אותה. |0.0 |-24.0 |18.0

|EQ3BAND_HIGHFREQ |קובע את תדר הקטעון (Hz) של הפס הגבוה. |2000.0 |20.0 |20000.0

|MIX |The amount of the sound effect that is mixed into the original sound. At the minimum value 0.0, it only plays the original ("dry") audio. At the maximum value 1.0, it only plays the affected ("wet") audio. |1.0 |0.0 |1.0

|BYPASS |When you bypass an effect, the effect turns off. The only valid values for `BYPASS` are 1.0 (to turn the effect off) and 0.0 (to keep the effect on). |0.0 |0.0 |1.0
|===

[[filter]]
=== FILTER

++++
<div class="effect-examples">
    <div class="audio-label">With Effect:</div>
    <div class="curriculum-mp3">audioMedia/filter_wet.mp3</div>
    <div class="audio-label">Without Effect:</div>
    <div class="curriculum-mp3">audioMedia/filter_dry.mp3</div>
</div>
++++

[role="curriculum-python"]
[source,python]
----
from earsketch import *
fitMedia(EIGHT_BIT_ANALOG_DRUM_LOOP_001, 1, 1, 3)
setEffect(1, FILTER, FILTER_FREQ, 20, 1, 4000, 3)
setEffect(1, FILTER, FILTER_RESONANCE, 0.9)
setEffect(1, FILTER, MIX, 1)
----

[role="curriculum-javascript"]
[source,javascript]
----
fitMedia(EIGHT_BIT_ANALOG_DRUM_LOOP_001, 1, 1, 3);
setEffect(1, FILTER, FILTER_FREQ, 20, 1, 4000, 3);
setEffect(1, FILTER, FILTER_RESONANCE, 0.9);
setEffect(1, FILTER, MIX, 1);
----

`FILTER` can soften, darken, or add depth to sound. It does this by applying a low-pass filter which lowers the volume of high frequencies.

|===
|פרמטר |תיאור |ערך ברירת-מחדל |minValue |maxValue

|FILTER_FREQ |תדר הקיטעון (Hz), שכל התדרים הגבוהים ממנו יונחתו. ככל שהתדר גבוה יותר, הוא יונחת יותר. |1000.0 |20.0 |20000.0

|FILTER_RESONANCE |The boost of frequencies near the FILTER_FREQ level. Higher values of resonance strongly boost a small window of frequencies near the FILTER_FREQ, creating a sharper, more ringing sound around those frequencies, while lower values of resonance subtly boost a larger window. |0.8 |0.0 |1.0

|MIX |The amount of the sound effect that is mixed into the original sound. At the minimum value 0.0, it only plays the original ("dry") audio. At the maximum value 1.0, it only plays the affected ("wet") audio. |1.0 |0.0 |1.0

|BYPASS |When you bypass an effect, the effect turns off. The only valid values for `BYPASS` are 1.0 (to turn the effect off) and 0.0 (to keep the effect on). |0.0 |0.0 |1.0
|===

[[flanger]]
=== FLANGER

++++
<div class="effect-examples">
    <div class="audio-label">With Effect:</div>
    <div class="curriculum-mp3">audioMedia/flanger_wet.mp3</div>
    <div class="audio-label">Without Effect:</div>
    <div class="curriculum-mp3">audioMedia/flanger_dry.mp3</div>
</div>
++++

[role="curriculum-python"]
[source,python]
----
from earsketch import *
fitMedia(YG_TECHNO_VOX_2, 1, 1, 2)
setEffect(1, FLANGER, FLANGER_LENGTH, 10)
setEffect(1, FLANGER, FLANGER_FEEDBACK, -5)
setEffect(1, FLANGER, FLANGER_RATE, 20)
setEffect(1, FLANGER, MIX, 1)
----

[role="curriculum-javascript"]
[source,javascript]
----
fitMedia(YG_TECHNO_VOX_2, 1, 1, 2);
setEffect(1, FLANGER, FLANGER_LENGTH, 10);
setEffect(1, FLANGER, FLANGER_FEEDBACK, -5);
setEffect(1, FLANGER, FLANGER_RATE, 20);
setEffect(1, FLANGER, MIX, 1);
----

`FLANGER` creates a "whoosh"-like effect by making various copies of the sound, adjusting their delay time very slightly, and then mixing them back into the original sound. At extreme values of parameter settings, `FLANGER` produces more artificial and "robot-like" sounds.

|===
|פרמטר |תיאור |ערך ברירת-מחדל |minValue |maxValue

|FLANGER_LENGTH |משך הזמן (במילישניות) מהצליל המקורי בו הופעל אפקט הפלנג'ר. |6.0 |0.0 |200.0

|FLANGER_FEEDBACK |The amount (in dB) that the affected sound is "fed back" into the effect. ערכים גבוהים יותר יוצרים צלילים "מלאכותיים" יותר. |-50.0 |-80.0 |-1.0

|FLANGER_RATE |The rate (in Hz) which the pitch cycles or "whooshes" at. ערכים נמוכים יותר יוצרים צלילים שחוזרים בצורה חלקה, בעוד ערכים גבוהים יותר יוצרים צלילים בעלי אפקט "וווש". |0.6 |0.001 |100.0

|MIX |The amount of the sound effect that is mixed into the original sound. At the minimum value 0.0, it only plays the original ("dry") audio. At the maximum value 1.0, it only plays the affected ("wet") audio. |1.0 |0.0 |1.0

|BYPASS |When you bypass an effect, the effect turns off. The only valid values for `BYPASS` are 1.0 (to turn the effect off) and 0.0 (to keep the effect on). |0.0 |0.0 |1.0
|===

[[pan]]
=== PAN

++++
<div class="effect-examples">
    <div class="audio-label">With Effect:</div>
    <div class="curriculum-mp3">audioMedia/pan_wet.mp3</div>
    <div class="audio-label">Without Effect:</div>
    <div class="curriculum-mp3">audioMedia/pan_dry.mp3</div>
</div>
++++

[role="curriculum-python"]
[source,python]
----
from earsketch import *
fitMedia(RD_UK_HOUSE_ACOUSTICGUITAR_1, 1, 1, 3)
setEffect(1, PAN, LEFT_RIGHT, -100, 1.5, 100, 2.5)
----

[role="curriculum-javascript"]
[source,javascript]
----
fitMedia(RD_UK_HOUSE_ACOUSTICGUITAR_1, 1, 1, 3);
setEffect(1, PAN, LEFT_RIGHT, -100, 1.5, 100, 2.5);
----

`PAN` affects the mix between the left and right audio channels. If you are wearing headphones, adjusting `PAN` changes how much of the sound you hear in your left ear versus the right.

|===
|פרמטר |תיאור |ערך ברירת-מחדל |minValue |maxValue

|LEFT_RIGHT |מציין את המיקום (ימין או שמאל) של הצליל המקורי בשדה הסטראופוני (0.0 זה המרכז, -100.0 זה לחלוטין בשמאל, 100.0 זה לחלוטין בימין). |0.0 |-100.0 |100.0

|BYPASS |When you bypass an effect, the effect turns off. The only valid values for `BYPASS` are 1.0 (to turn the effect off) and 0.0 (to keep the effect on). |0.0 |0.0 |1.0
|===

[[phaser]]
=== PHASER

++++
<div class="effect-examples">
    <div class="audio-label">With Effect:</div>
    <div class="curriculum-mp3">audioMedia/phaser_wet.mp3</div>
    <div class="audio-label">Without Effect:</div>
    <div class="curriculum-mp3">audioMedia/phaser_dry.mp3</div>
</div>
++++

[role="curriculum-python"]
[source,python]
----
from earsketch import *
fitMedia(RD_UK_HOUSE_ACOUSTICGUITAR_1, 1, 1, 3)
setEffect(1, PHASER, PHASER_RATE, 0.7)
setEffect(1, PHASER, PHASER_RANGEMIN, 440)
setEffect(1, PHASER, PHASER_RANGEMIN, 1600)
setEffect(1, PHASER, PHASER_FEEDBACK, -2)
setEffect(1, PHASER, MIX, 1)
----

[role="curriculum-javascript"]
[source,javascript]
----
fitMedia(RD_UK_HOUSE_ACOUSTICGUITAR_1, 1, 1, 3);
setEffect(1, PHASER, PHASER_RATE, 0.7);
setEffect(1, PHASER, PHASER_RANGEMIN, 440);
setEffect(1, PHASER, PHASER_RANGEMIN, 1600);
setEffect(1, PHASER, PHASER_FEEDBACK, -2);
setEffect(1, PHASER, MIX, 1);
----

`PHASER` creates a sweeping-sounding effect by making a copy of the original sound, delaying it slightly, and playing it against the original. When this happens, some of the frequencies in the original sound and the copy temporarily cancel each other out by going "in and out of phase" with each other.

|===
|פרמטר |תיאור |ערך ברירת-מחדל |minValue |maxValue

|PHASER_RATE |הקצב (Hz) בו זמן העיכוב הקצרצר משתנה. ערכים נמוכים יותר יוצרים צלילים שחוזרים בצורה חלקה, בעוד ערכים גבוהים יותר יוצרים צלילים "רובוטיים". |0.5 |0.0 |10.0

|PHASER_RANGEMIN |ערך התדר הנמוך ביותר (Hz) בטווח התדרים המושפע. |440.0 |40.0 |20000.0

|PHASER_RANGEMAX |ערך התדר הגבוה ביותר (Hz) בטווח התדרים המושפע. |1600.0 |40.0 |20000.0

|PHASER_FEEDBACK |The amount that the affected sound is "fed back" into the effect. ערכים גבוהים יותר יוצרים צלילים "מלאכותיים" יותר. |-3.0 |-120.0 |-1.0

|MIX |The amount of the sound effect that is mixed into the original sound. At the minimum value 0.0, it only plays the original ("dry") audio. At the maximum value 1.0, it only plays the affected ("wet") audio. |1.0 |0.0 |1.0

|BYPASS |When you bypass an effect, the effect turns off. The only valid values for `BYPASS` are 1.0 (to turn the effect off) and 0.0 (to keep the effect on). |0.0 |0.0 |1.0
|===

[[pitchshift]]
=== PITCHSHIFT

++++
<div class="effect-examples">
    <div class="audio-label">With Effect:</div>
    <div class="curriculum-mp3">audioMedia/pitchshift_wet.mp3</div>
    <div class="audio-label">Without Effect:</div>
    <div class="curriculum-mp3">audioMedia/pitchshift_dry.mp3</div>
</div>
++++

[role="curriculum-python"]
[source,python]
----
from earsketch import *
fitMedia(YG_TECHNO_VOX_2, 1, 1, 2)
setEffect(1, PITCHSHIFT, PITCHSHIFT_SHIFT, -10)
----

[role="curriculum-javascript"]
[source,javascript]
----
fitMedia(YG_TECHNO_VOX_2, 1, 1, 2);
setEffect(1, PITCHSHIFT, PITCHSHIFT_SHIFT, -10);
----

`PITCHSHIFT` raises or lowers the pitch of a sound. It can be helpful for making multiple tracks sound better together.

|===
|פרמטר |תיאור |ערך ברירת-מחדל |minValue |maxValue

|PITCHSHIFT_SHIFT |מציין את מספר חצאי הטונים (ושבריהם, המצוינים כספרות אחרי הנקודה העשרונית) בו יש לשנות את הצליל המקורי. 12 חצאי טונים הם אוקטבה אחת. |0.0 |-12.0 |12.0

|BYPASS |When you bypass an effect, the effect turns off. The only valid values for `BYPASS` are 1.0 (to turn the effect off) and 0.0 (to keep the effect on). |0.0 |0.0 |1.0
|===

[[reverb]]
=== REVERB

++++
<div class="effect-examples">
    <div class="audio-label">With Effect:</div>
    <div class="curriculum-mp3">audioMedia/reverb_wet.mp3</div>
    <div class="audio-label">Without Effect:</div>
    <div class="curriculum-mp3">audioMedia/reverb_dry.mp3</div>
</div>
++++

[role="curriculum-python"]
[source,python]
----
from earsketch import *
fitMedia(EIGHT_BIT_ANALOG_DRUM_LOOP_001, 1, 1, 3)
setEffect(1, REVERB, REVERB_TIME, 2000)
setEffect(1, REVERB, REVERB_DAMPFREQ, 18000)
setEffect(1, REVERB, MIX, 0.5)
----

[role="curriculum-javascript"]
[source,javascript]
----
fitMedia(EIGHT_BIT_ANALOG_DRUM_LOOP_001, 1, 1, 3);
setEffect(1, REVERB, REVERB_TIME, 2000);
setEffect(1, REVERB, REVERB_DAMPFREQ, 18000);
setEffect(1, REVERB, MIX, 0.5);
----

`REVERB` adds a slowly decaying ambience to a sound, making it sound denser, dreamier, or as if it was recorded in a smaller or larger room than it actually was.

|===
|פרמטר |תיאור |ערך ברירת-מחדל |minValue |maxValue

|REVERB_TIME |זמן הדעיכה של צליל האווירה במילישניות (ms). כאשר REVERB_TIME מאופנן בעזרת עקומת אוטומציה, בגלל הטבע של reverb מבוסס קונבולוציה, הערך מעודכן כל רבע (time=0/25) במדרגות מנקודת ההתחלה של האוטומציה. (אתם, בכל מקרה, בקושי תבחינו בכך). |1500.0 |100.0 |4000.0

|REVERB_DAMPFREQ |תדר הקיטעון (Hz) של המסנן מעביר נמוכים המופעל של צליל האווירה. ככל שהערך נמוך יותר, האפקט ישמע כהה יותר. |10000.0 |200.0 |18000.0

|MIX |The amount of the sound effect that is mixed into the original sound. At the minimum value 0.0, it only plays the original ("dry") audio. At the maximum value 1.0, it only plays the affected ("wet") audio. |0.3 |0.0 |1.0

|BYPASS |When you bypass an effect, the effect turns off. The only valid values for `BYPASS` are 1.0 (to turn the effect off) and 0.0 (to keep the effect on). |0.0 |0.0 |1.0
|===

[[ringmod]]
=== RINGMOD

++++
<div class="effect-examples">
    <div class="audio-label">With Effect:</div>
    <div class="curriculum-mp3">audioMedia/ringmod_wet.mp3</div>
    <div class="audio-label">Without Effect:</div>
    <div class="curriculum-mp3">audioMedia/ringmod_dry.mp3</div>
</div>
++++

[role="curriculum-python"]
[source,python]
----
from earsketch import *
ffitMedia(YG_TECHNO_VOX_2, 1, 1, 2)
setEffect(1, RINGMOD, RINGMOD_MODFREQ, 100)
setEffect(1, RINGMOD, RINGMOD_FEEDBACK, 80)
setEffect(1, RINGMOD, MIX, 1)
----

[role="curriculum-javascript"]
[source,javascript]
----
fitMedia(YG_TECHNO_VOX_2, 1, 1, 2);
setEffect(1, RINGMOD, RINGMOD_MODFREQ, 100);
setEffect(1, RINGMOD, RINGMOD_FEEDBACK, 80);
setEffect(1, RINGMOD, MIX, 1);
----

`RINGMOD` creates many different artificial-sounding effects by multiplying the signals from the original and a pure sine wave (which sounds like a tuning fork). Some parameter settings will produce effects similar to ones used in old science fiction movies.

|===
|פרמטר |תיאור |ערך ברירת-מחדל |minValue |maxValue

|RINGMOD_MODFREQ |התדר (Hz) של מתנד גל הסינוס אשר מוכפל בצליל המקורי. |40.0 |0.0 |100.0

|RINGMOD_FEEDBACK |The amount of affected sound that is fed-back into the effect. ערכים גבוהים יוצרים צלילים "רובוטיים". |0.0 |0.0 |100.0

|MIX |The amount of the sound effect that is mixed into the original sound. At the minimum value 0.0, it only plays the original ("dry") audio. At the maximum value 1.0, it only plays the affected ("wet") audio. |1.0 |0.0 |1.0

|BYPASS |When you bypass an effect, the effect turns off. The only valid values for `BYPASS` are 1.0 (to turn the effect off) and 0.0 (to keep the effect on). |0.0 |0.0 |1.0
|===

[[tremolo]]
=== TREMOLO

++++
<div class="effect-examples">
    <div class="audio-label">With Effect:</div>
    <div class="curriculum-mp3">audioMedia/tremolo_wet.mp3</div>
    <div class="audio-label">Without Effect:</div>
    <div class="curriculum-mp3">audioMedia/tremolo_dry.mp3</div>
</div>
++++

[role="curriculum-python"]
[source,python]
----
from earsketch import *
fitMedia(RD_UK_HOUSE_ACOUSTICGUITAR_1, 1, 1, 3)
setEffect(1, TREMOLO, TREMOLO_FREQ, 7.5)
setEffect(1, TREMOLO, TREMOLO_AMOUNT, -10)
setEffect(1, TREMOLO, MIX, 1)
----

[role="curriculum-javascript"]
[source,javascript]
----
fitMedia(RD_UK_HOUSE_ACOUSTICGUITAR_1, 1, 1, 3);
setEffect(1, TREMOLO, TREMOLO_FREQ, 7.5);
setEffect(1, TREMOLO, TREMOLO_AMOUNT, -10);
setEffect(1, TREMOLO, MIX, 1);
----

`TREMOLO` produces a wobbly-sounding effect by quickly changing the volume of the sound back and forth.

|===
|פרמטר |תיאור |ערך ברירת-מחדל |minValue |maxValue

|TREMOLO_FREQ |הקצב (Hz) בו העוצמה משתנה, הלוך וחזור. |4.0 |0.0 |100.0

|TREMOLO_AMOUNT |הכמות (dB) בה העוצמה משתנה בכל מחזור. |-6.0 |-60.0 |0.0

|MIX |The amount of the sound effect that is mixed into the original sound. At the minimum value 0.0, it only plays the original ("dry") audio. At the maximum value 1.0, it only plays the affected ("wet") audio. |1.0 |0.0 |1.0

|BYPASS |When you bypass an effect, the effect turns off. The only valid values for `BYPASS` are 1.0 (to turn the effect off) and 0.0 (to keep the effect on). |0.0 |0.0 |1.0
|===

[[volume]]
=== VOLUME

++++
<div class="effect-examples">
    <div class="audio-label">With Effect:</div>
    <div class="curriculum-mp3">audioMedia/volume_wet.mp3</div>
    <div class="audio-label">Without Effect:</div>
    <div class="curriculum-mp3">audioMedia/volume_dry.mp3</div>
</div>
++++

[role="curriculum-python"]
[source,python]
----
from earsketch import *
fitMedia(EIGHT_BIT_ANALOG_DRUM_LOOP_001, 1, 1, 3)
setEffect(1, VOLUME, GAIN, -55, 1, 0, 3)
----

[role="curriculum-javascript"]
[source,javascript]
----
fitMedia(EIGHT_BIT_ANALOG_DRUM_LOOP_001, 1, 1, 3);
setEffect(1, VOLUME, GAIN, -55, 1, 0, 3);
----

`VOLUME` allows you to change the loudness of a sound.

|===
|פרמטר |תיאור |ערך ברירת-מחדל |minValue |maxValue

|GAIN |מציין את עוצמת הצליל ביציאה של הצליל המקורי. |0.0 |-60.0 |12.0

|BYPASS |When you bypass an effect, the effect turns off. The only valid values for `BYPASS` are 1.0 (to turn the effect off) and 0.0 (to keep the effect on). |0.0 |0.0 |1.0
|===

[[wah]]
=== WAH

++++
<div class="effect-examples">
    <div class="audio-label">With Effect:</div>
    <div class="curriculum-mp3">audioMedia/wah_wet.mp3</div>
    <div class="audio-label">Without Effect:</div>
    <div class="curriculum-mp3">audioMedia/wah_dry.mp3</div>
</div>
++++

[role="curriculum-python"]
[source,python]
----
from earsketch import *
fitMedia(RD_UK_HOUSE_ACOUSTICGUITAR_1, 1, 1, 3)
setEffect(1, WAH, WAH_POSITION, 0, 1, 0.5, 2)
setEffect(1, WAH, WAH_POSITION, 0, 2, 0.5, 3)
setEffect(1, WAH, MIX, 1)
----

[role="curriculum-javascript"]
[source,javascript]
----
fitMedia(RD_UK_HOUSE_ACOUSTICGUITAR_1, 1, 1, 3);
setEffect(1, WAH, WAH_POSITION, 0, 1, 0.5, 2);
setEffect(1, WAH, WAH_POSITION, 0, 2, 0.5, 3);
setEffect(1, WAH, MIX, 1);
----

`WAH` can make the sound mimic someone saying "Wah Wah" when the `WAH_POSITION` parameter is changed over time using the setEffect() function. It is a resonant bandpass filter, which means it lowers the volume of high and low frequencies while boosting a narrow window of frequencies in the middle.

|===
|פרמטר |תיאור |ערך ברירת-מחדל |minValue |maxValue

|WAH_POSITION |התדר המרכזי של טווח התדרים, בעל הרוחב הקבוע, המוגבר. |0.0 |0.0 |1.0

|MIX |The amount of the sound effect that is mixed into the original sound. At the minimum value 0.0, it only plays the original ("dry") audio. At the maximum value 1.0, it only plays the affected ("wet") audio. |1.0 |0.0 |1.0

|BYPASS |When you bypass an effect, the effect turns off. The only valid values for `BYPASS` are 1.0 (to turn the effect off) and 0.0 (to keep the effect on). |0.0 |0.0 |1.0
|===