[[mixingwithconditionnals]]
== ¡Mezclar con condicionales!

:nofooter:

En la programación, se pueden automatizar las cosas. Un ejemplo de automatización es si estás programando un robot para que se detenga cuando se detecta un obstáculo. Así el robot no necesita que un ser humano le diga que se detenga manualmente. En cambio, el robot usará un sensor para detectar los obstáculos, y si hay uno, se detendrá. Podemos crear automatizaciones musicales en EarSketch, usando condicionales (declaraciones "if", una palabra en inglés que significa "si"). Vamos a ver cómo automatizar la mezcla de las pistas musicales (tracks). Mezclar consiste en reducir el volumen cuando es demasiado alto y aumentar el volumen cuando es demasiado bajo.

[[analyzetrack]]
=== Use `analyzeTrack()`

Vamos a ver cómo detectar la intensidad sonora, o volumen, de la pista. Asegúrate de entender la diferencia entre el registro (agudo o grave) y el volumen (alto o bajo) de un sonido. We’ll use an EarSketch function called `analyzeTrack()`. Copia y ejecuta el siguiente código:

[role="curriculum-python"]
[source,python]
----
# código python
#
# nombre_del_script: La función analyseTrack()
#
# autor: El Equipo de EarSketch
#
# descripción: Cómo usar la función analyseTrack() para desplegar (o imprimir) el volumen de una pista
#
# Configuración
from earsketch import *
init()
setTempo(120)

# Colocar un sonido en la pista 1
sonido = COMMON_LOVE_VOX_COMMON_1
fitMedia(sonido, 1, 1, 9)

# Crear una variable para almacenar el volumen de la pista 1
volumen1 = analyzeTrack(1, RMS_AMPLITUDE)

# Mostrar el volumen en la consola
print(volumen1)

# Fin
finish()
----

[role="curriculum-javascript"]
[source,javascript]
----
// código javascript
//
// nombre_del_script: La función analyzeTrack()
//
// autor: El Equipo de EarSketch
//
// descripción: Cómo usar la función analyzeTrack() para desplegar (o imprimir) el volumen de una pista
//
// Configuración
init();
setTempo(120);

// Colocar un sonido en la pista 1
sonido = COMMON_LOVE_VOX_COMMON_1;
fitMedia(sonido, 1, 1, 9);

// Crear una variable para almacenar el volumen de la pista 1
volumen1 = analyzeTrack(1, RMS_AMPLITUDE);

// Mostrar el volumen en la consola
println(volumen1);

// Fin
finish();
----

Puedes leer en tu consola que el volumen impreso es de 0.10306035109110138.

* El volumen puede ir desde 0 (silencio) hasta 1 (el volumen máximo).
* A veces verás un número así: 1.74630733714e-05. Se llama notación científica. ¿Ves el e-05 al final? Significa que el punto decimal se mueve izquierda 5 lugares hacia la izquierda (se reemplaza con 0 si es necesario). Es igual a 0.0000174630733714.
* La mayoría de los sonidos tendrá un volumen por debajo de 0.4

The `analyzeTrack()` function takes 2 arguments:

. el número de pista
. el parámetro que se quiere analizar. For loudness it's: `RMS_AMPLITUDE`.

.PRÁCTICA
****
. Trata de usar el código del ejemplo anterior con diferentes sonidos (cambia la variable "sonido") y verás los resultados.
. Add a second track and use the `analyzeTrack()` function to print its loudness in the console. Cuando ejecutes el código, antes de mirar tu consola, escucha tu música y trata de adivinar cuál de las pistas tiene el volumen más alto.
****

The parameter for `analyzeTrack()` can either be `RMS_AMPLITUDE`, to evaluate the loudness, or `SPECTRAL_CENTROID` to analyze the brightness of the sound. We'll focus on analyzing loudness in this chapter.

[[booleansandcomparisons]]
=== Los booleanos y las comparaciones

We will now see how *Boolean logic* works, this will help us automate some tasks.

[role="curriculum-python"]
*Booleans* are a data type. The boolean data type only has 2 possible values, `True` and `False`. `True` and `False` start with a capital letter and do not have quotes.

[role="curriculum-javascript"]
*Booleans* are a data type. The boolean data type only has 2 possible values, `true` and `false`. `true` and `false` start with a lower-case letter and do not have quotes.

[role="curriculum-python"]
--
To create a boolean, you can either initialize a variable (`variable1 = True`), or you can use a comparison. To make a comparison, we use a *comparison operator*. Aquí están los operadores de comparación:

[cols="^h,1"]
|===
|==
|es idéntico a

|!=
|no es idéntico a

|>
|es mayor que

|>=
|es mayor o igual a

|<
|es menor que

|\<=
|es menor o igual a
|===
--

[role="curriculum-javascript"]
--
To create a boolean, you can either initialize a variable (`var variable1 = true;`), or you can use a comparison. To make a comparison, we use a *comparison operator*. Aquí están los operadores de comparación:

[cols="^h,1"]
|===
|==
|es idéntico a

|!=
|no es idéntico a

|>
|es mayor que

|>=
|es mayor o igual a

|<
|es menor que

|\<=
|es menor o igual a
|===
--

Observa la diferencia entre:

1. Comparing two values to see if they are identical: `==`
1. Assigning a value to a variable: `=`

[role="curriculum-python curriculum-mp4"]
[[video17apy]]
video::./videoMedia/6_2_1_boolean_py.mp4[]

[role="curriculum-javascript curriculum-mp4"]
[[video17ajs]]
video::./videoMedia/6_2_1_boolean_js.mp4[]

// this video will be cut at 2' to delete the section about boolean operators//

[role="curriculum-python"]
.PRÁCTICA
****
* Crea un nuevo script y agrega sonidos a 2 pistas.
* Print `True` if the first track is louder than the second track, and `False` otherwise.
* Use a for loop with the counter `track` to check for each track if the loudness is strictly greater than 0.01. If it is, print `True`, if not, print `False`.
* You can use additional print statements before printing `True` or `False` so that when you read the console, you know what is `True` or `False`. Por ejemplo, puedes imprimir el número de pista primero y luego 'True' o 'False'.
****

[role="curriculum-javascript"]
.PRÁCTICA
****
* Crea un nuevo script y agrega sonidos a 2 pistas.
* Print `true` if the first track is louder than the second track, and `false` otherwise.
* Use a for loop with the counter `track` to check for each track if the loudness is strictly greater than 0.01. If it is, print `true`, if not, print `false`.
* You can use additional print statements before printing `true` or `false` so that when you read the console, you know what is `true` or `false`. Por ejemplo, puedes imprimir el número de pista primero y luego 'true' o 'false'.
****

Aquí hay un ejemplo:

[role="curriculum-python"]
[source, python]
----
# python code
# script_name: Boolean Example
#
# author: The EarSketch Team
# description: We analyze the loudness of our tracks
#

# Setup
from earsketch import *
init()
setTempo(120)

# Creating 2 tracks
melody1 = RD_CINEMATIC_SCORE_STRINGS_14
melody2 = RD_UK_HOUSE__5THCHORD_1
fitMedia(melody1, 1, 1, 9)
fitMedia(melody2, 2, 1, 9)

# Evaluating the loudness of the tracks
loudnessTrack1 = analyzeTrack(1, RMS_AMPLITUDE)
loudnessTrack2 = analyzeTrack(2, RMS_AMPLITUDE)

# Checking if track 1 is louder than track 2
# We create the boolean comparison1
comparison1 = (loudnessTrack1 > loudnessTrack2)
print('Is Track 1 louder than track 2?')
print(comparacion1)

# Crear un ciclo for para comparar con 0.01 el volumen de cada pista
for pista in range (1, 3):
  volumen = analyzeTrack(pista, RMS_AMPLITUDE)
  print('Es el número de pista' + str(pista) + 'mayor que 0.01?')
  print(loudness > 0.01)

# Finish
finish()
----

[role="curriculum-javascript"]
[source, javascript]
----
// javascript code
//
// script_name: Boolean Example
//
// author: The EarSketch Team
//
// description: We analyze the loudness of our tracks
//
//
// Setup
init();
setTempo(120);

// Creating 2 tracks
var melody1 = RD_CINEMATIC_SCORE_STRINGS_14;
var melody2 = RD_UK_HOUSE__5THCHORD_1;
fitMedia(melody1, 1, 1, 9);
fitMedia(melody2, 2, 1, 9);

// Evaluating the loudness of the tracks
var loudnessTrack1 = analyzeTrack(1, RMS_AMPLITUDE);
var loudnessTrack2 = analyzeTrack(2, RMS_AMPLITUDE);

// Checking if track 1 is louder than track 2
// We create the boolean comparison1
var comparison1 = (loudnessTrack1 > loudnessTrack2);
println('Is track 1 louder than track 2?');
println(comparison1);

// Creating a for loop to compare each track's loudness to 0.01
for (var track = 1; track < 3; track++) {
  var loudness = analyzeTrack(track, RMS_AMPLITUDE);
  println ('Is track number ' + track + ' greater than 0.01?');
  println (loudness > 0.01);
}

//Finish
finish();

----

[role="curriculum-python"]
Nota: en este ejemplo, usamos algunas declaraciones de impresión con cadenas de caracteres (o strings en inglés) para ayudarnos a leer el contenido de la consola. We used the operator `+` to *concatenate*, or add strings, and the function str() to convert numbers to strings.

[role="curriculum-javascript"]
Nota: en este ejemplo, usamos algunas declaraciones de impresión con cadenas de caracteres (o strings en inglés) para ayudarnos a leer el contenido de la consola. We used the operator `+` to *concatenate*, or add strings.

[[conditionalstatements]]
=== Declaraciones condicionales

¿Qué es una declaración condicional? A *statements* is an instruction for the computer. A *conditional statement* is an instruction that must be executed only if a certain *condition* is true. Por ejemplo, si se programa que un robot pare en frente de un obstáculo, la condición es "¿hay un obstáculo?". Si hay, entonces para. If no, don't do anything (keep going).

A continuación, hay un ejemplo de una declaración condicional. Observa sus similitudes con un ciclo for:

[role="curriculum-python"]
[source, python]
----
if (condicion):
    # Escribe aquí las instrucciones que la computadora tiene que ejecutar si se calcula que la condición es True.
----

[role="curriculum-javascript"]
[source, javascript]
----
if (condicion){
    // Escribe aquí las instrucciones que la computadora tiene que ejecutar si se calcula que la condición es true.
----

.PRÁCTICA
****
* Crea un nuevo script con 2 pistas musicales (tracks).
* Si la primera pista tiene más volumen que la segunda, entonces reduce su volumen. You'll need the `analyzeTrack()` and `setEffect()` functions, plus an if statement.
* Tiene que haber una reducción en el valor GAIN (entre -1 y -60dB) para reducir el volumen.
****

Aquí hay un ejemplo:

[role="curriculum-python"]
[source, python]
----
# python code
#
# script_name: Remixing 1
#
# author: The EarSketch Team
#
# description: If track 1 is louder than track 2, we'll reduce its volume
#
# Setup
from earsketch import *
init()
setTempo(120)

# Creating 2 tracks
melody1 = RD_CINEMATIC_SCORE_STRINGS_14
melody2 = RD_UK_HOUSE__5THCHORD_1
fitMedia(melody1, 1, 1, 9)
fitMedia(melody2, 2, 1, 9)

# Evaluating the loudness of the tracks
loudnessTrack1 = analyzeTrack(1, RMS_AMPLITUDE)
loudnessTrack2 = analyzeTrack(2, RMS_AMPLITUDE)

# If track 1 is louder than track 2, we reduce its volume
if (loudnessTrack1 > loudnessTrack2):
	setEffect(1, VOLUME, GAIN, -10)

# Finish
finish()
----

[role="curriculum-javascript"]
[source, javascript]
----
// javascript code
//
// script_name: Remixing 1
//
// author: The EarSketch Team
//
// description: If track 1 is louder than track 2, we'll reduce its volume

// Setup
init();
setTempo(120);

// Creating 2 tracks
var melody1 = RD_CINEMATIC_SCORE_STRINGS_14;
var melody2 = RD_UK_HOUSE__5THCHORD_1;
fitMedia(melody1, 1, 1, 9);
fitMedia(melody2, 2, 1, 9);

// Evaluating the loudness of the tracks
var loudnessTrack1 = analyzeTrack(1, RMS_AMPLITUDE);
var loudnessTrack2 = analyzeTrack(2, RMS_AMPLITUDE);

// If track 1 is louder than track 2, we reduce its volume
if (loudnessTrack1 > loudnessTrack2){
	setEffect(1, VOLUME, GAIN, -10);
}

//Finish
finish();
----

Tal vez nos gustaría revisar varias condiciones y ejecutar otra serie de declaraciones dependiendo de cada condición. Puedes agregar todas las condiciones que quieras. Usamos la siguiente sintaxis:

[role="curriculum-python"]
[source, python]
----
if (condicion1):
    # Escribe aquí las instrucciones que la computadora tiene que ejecutar si se calcula que la condicion1 es True. Si es False, prosigue a la siguiente línea. elif (condicion2):
	# Escribe aquí las instrucciones si la condicion2 es True. Si la condicion2 es False, prosigue a la siguiente línea. elif (condicion3):
	# Escribe aquí las instrucciones si la condicion3 es True. Si la condicion3 es False, prosigue a la siguiente línea. else:
	# Escribe aquí las instrucciones si todas las 3 condiciones son False.
----

[role="curriculum-javascript"]
[source, javascript]
----
if (condicion1) {
    // Escribe aquí las instrucciones que la computadora tiene que ejecutar si se calcula que la condicion1 es true. } else if (condicion2) {
	// # Escribe aquí las instrucciones si la condicion2 es true. Si la condicion2 es false, prosigue a la siguiente línea. // elif es una abreviatura de "else if" ("de lo contrario, si" en español)
} else if (condicion3) {
	// Escribe aquí las instrucciones si la condicion3 es true. Si la condicion3 es false, prosigue a la siguiente línea. } else {
	// Escribe aquí las instrucciones si todas las 3 condiciones son false.
----

[[mixingyourtracks]]
=== Cómo mezclar tus pistas

Let's use all these tools to mix your song. Mezclar es el acto de modificar el volumen de tus pistas para que suenen equilibradas al tocarlas juntas.

[role="curriculum-python"]
.PRÁCTICA
****
* Crea un nuevo script.
* Añade sonidos a por lo menos 3 pistas durante por lo menos 16 compases.
* You can use the `makeBeat()` function and a for loop to add percussions.
* Elije tu pista "principal". Puede ser tu melodía, o una pista que quieras destacar.
* If your main track is not louder than the other tracks, make sure to increase its volume using the `setEffect()` function. Don't take the percussive track into account, as `analyzeTrack()` is not relevant for percussions. `analyzeTrack()` returns a mean whereas percussions are bursts of sound, so a mean doesn't really evaluate the loudness.
* Usa declaraciones de impresión para mostrar tu proceso en la consola. Here is an example of a print statement: `print('Is track number' + str(track) + 'greater than 0.01?')`, if the counter `track` is equal to `1`, this will print 'Is track number 1 greater than 0.01?'. The function `str()` converts a number (ex: 1) into a string (ex: '1').
****

[role="curriculum-javascript"]
.PRÁCTICA
****
* Crea un nuevo script.
* Añade sonidos a por lo menos 3 pistas durante por lo menos 16 compases.
* You can use the `makeBeat()` function and a for loop to add percussions.
* Elije tu pista "principal". Puede ser tu melodía, o una pista que quieras destacar.
* If your main track is not louder than the other tracks, make sure to increase its volume using the `setEffect()` function. Don't take the percussive track into account, as `analyzeTrack()` is not relevant for percussions. `analyzeTrack()` returns a mean whereas percussions are bursts of sound, so a mean doesn't really evaluate the loudness.
* Usa declaraciones de impresión para mostrar tu proceso en la consola. Here is an example of a print statement: `println('Is track number' + track + 'greater than 0.01?')`, if the counter `track` is equal to `1`, this will print 'Is track number 1 greater than 0.01?'.
****

Let's review some vocabulary:

1. *Operator*: a character that represents an action. We have seen arithmetic operators (`\+`, `-`, `\*`, `=`) and comparison operators (`>`, `>=`, `<`, `\<=`, `==`, `!=`).
1. *Expression*: A combination of values, constants, variables, operators, and functions. La computadora evalúa las expresiones para producir un resultado, usualmente un solo valor numérico o booleano.  For example: `1+2` (evaluated to 3) or `1<2` (evaluated to True) or `analyzeTrack(1, RMS_AMPLITUDE)` (evaluated to the loudness of track 1, a float between 0 and 1).
1. *Statements*: instructions for the computer to execute.

A continuación, hay un ejemplo de una mezcla automatizada. We can say it's automated because if you change one or more sounds, you won't have to check their loudness and modify the volume accordingly yourself, since it's already included in the code.

[role="curriculum-python"]
[source, python]
----
# python code
# script_name: Mixing
#
# author: the EarSketch team
# description: Creating a short song and using conditional statements to mix the tracks
#
# Setup
from earsketch import *
init()
setTempo(120)

# Adding a melody and bass
melody1 = YG_ALT_POP_GUITAR_3
melody2 = YG_ALT_POP_GUITAR_1
bass1 = YG_ALT_POP_BASS_1
bass2 = DUBSTEP_SUBBASS_008
strings = YG_HIP_HOP_STRINGS_4
fitMedia(melody1, 1, 1, 9)
fitMedia(melody2, 1, 9, 17)
fitMedia(bass1, 2, 1, 9)
fitMedia(bass2, 2, 9, 17)
fitMedia(strings, 3, 9, 17)

# Adding percussions using makeBeat()
beatKick = '0---0-----0-0---'
beatSnare = '--0-0------000-'
soundKick = OS_KICK02
soundSnare = OS_SNARE06
for measure in range(5,17):
  makeBeat(soundKick, 4, measure, beatKick)
  makeBeat(soundSnare, 5, measure, beatSnare)

# Mixing my tracks
# First, we analyze the tracks for loudness
loudnessTrack1 = analyzeTrack(1, RMS_AMPLITUDE)
print('The loudness of track 1 is' + str(loudnessTrack1))
loudnessTrack2 = analyzeTrack(2, RMS_AMPLITUDE)
print('The loudness of track 2 is' + str(loudnessTrack2))
loudnessTrack3 = analyzeTrack(3, RMS_AMPLITUDE)
print('The loudness of track 3 is' + str(loudnessTrack3))

if (loudnessTrack1 < loudnessTrack2):
  # if track 1 is quieter than track 2 then we increase the volume of track 1
  setEffect(1, VOLUME, GAIN, +5)
  print ('track 1 was quieter than track 2')
elif (loudnessTrack1 < loudnessTrack3):
  # if track 1 is louder than track 2 but quieter than track 3, we increase the volume of track 1
  setEffect(1, VOLUME, GAIN, +5)
  print ('track 1 was quieter than track 3')
else:
  # if track 1 is louder than tracks 2 and 3, then we change nothing
  print('track 1 was the loudest track already')


# Finish
finish()
----

[role="curriculum-javascript"]
[source, javascript]
----
"use strict";

// javascript code
// script_name: Mixing
//
// author: The EarSketch team
// description: Creating a short song and using conditional statements to mix the tracks
//

// Setup
init();
setTempo(120);

// Adding a melody and bass
var melody1 = YG_ALT_POP_GUITAR_3;
var melody2 = YG_ALT_POP_GUITAR_1;
var bass1 = YG_ALT_POP_BASS_1;
var bass2 = DUBSTEP_SUBBASS_008;
var strings = YG_HIP_HOP_STRINGS_4;
fitMedia(melody1, 1, 1, 9);
fitMedia(melody2, 1, 9, 17);
fitMedia(bass1, 2, 1, 9);
fitMedia(bass2, 2, 9, 17);
fitMedia(strings, 3, 9, 17);

// Adding percussions using makeBeat()
var beatKick = '0---0-----0-0---';
var beatSnare = '--0-0------000-';
var soundKick = OS_KICK02;
var soundSnare = OS_SNARE06;
for (var measure = 5; measure > 17; measure++){
  makeBeat(soundKick, 4, measure, beatKick);
  makeBeat(soundSnare, 5, measure, beatSnare);
}


// Mixing my tracks
// First, we analyze the tracks for loudness
var loudnessTrack1 = analyzeTrack(1, RMS_AMPLITUDE);
println('The loudness of track 1 is' + loudnessTrack1);
var loudnessTrack2 = analyzeTrack(2, RMS_AMPLITUDE);
println('The loudness of track 2 is' + loudnessTrack2);
var loudnessTrack3 = analyzeTrack(3, RMS_AMPLITUDE);
println('The loudness of track 3 is' + loudnessTrack3);

if (loudnessTrack1 < loudnessTrack2){
  // if track 1 is quieter than track 2 then we increase the volume of track 1
  setEffect(1, VOLUME, GAIN, +5);
  println ('track 1 was quieter than track 2');
} else if (loudnessTrack1 < loudnessTrack3){
  // if track 1 is louder than track 2 but quieter than track 3, we increase the volume of track 1
  setEffect(1, VOLUME, GAIN, +5);
  println ('track 1 was quieter than track 3');
} else {
  // if track 1 is louder than tracks 2 and 3, then we change nothing
  println('track 1 was the loudest track already');
}

// Finish
finish();
----

{nbsp} +

[[chapter6summary]]
=== Resumen del capítulo 6

[role="curriculum-python"]
* The `analyzeTrack()` function takes two arguments: the track number and a parameter. When the parameter is `RMS_AMPLITUDE`, the function will return the loudness of the track (a number between 0 and 1). When the parameter is `SPECTRAL_CENTROID`, the function will return the brightness of the track.
* The *boolean* data type has only two possible values, `True` and `False`.
* Boolean values are generated by comparison operators: `==`, `!=`, `>`, `>=`, `<`, `\<=`.
* `==` evaluates if 2 values are equal, whereas `=` assigns a value to a variable.
* An *operator* is a character that represents an action.
* *Expressions* are evaluated by the computer to produce a value.
* A *statement* is an instruction for the computer.
* A *condition* is an expression that evaluates to `True` or `False`.
* The _if_ statement only executes its code block when its condition is `True`.
* In the event that an _if_ statement's condition is `False`, an optional _else_ statement allows an alternative code block to be executed.

[role="curriculum-javascript"]
* The `analyzeTrack()` function takes two arguments: the track number and a parameter. When the parameter is `RMS_AMPLITUDE`, the function will return the loudness of the track (a number between 0 and 1). When the parameter is `SPECTRAL_CENTROID`, the function will return the brightness of the track.
* The *boolean* data type has only two possible values, `true` and `false`.
* Boolean values are generated by comparison operators: `==`, `!=`, `>`, `>=`, `<`, `\<=`.
* `==` evaluates if 2 values are equal, whereas `=` assigns a value to a variable.
* An *operator* is a character that represents an action.
* *Expressions* are evaluated by the computer to produce a value.
* A *statement* is an instruction for the computer.
* A *condition* is an expression that evaluates to `true` or `false`.
* The _if_ statement only executes its code block when its condition is `true`.
* In the event that an _if_ statement's condition is `false`, an optional _else_ statement allows an alternative code block to be executed.

[[chapter-questions]]
=== Preguntas

[question]
--
¿Cuál de los siguientes elementos es un booleano?

[answers]
* `5+4 == 5`
* `measure = 1`
* `2<3<4`
* `False()`
--

[question]
--
¿Cuál sería el resultado de este bloque de código (qué se imprimiría en la consola)?

[source,python]
----
n = 5
if (n * 3 == 15):
    print(n + 5)
else:
    print(n)
----

[answers]
* 10
* 5
* True
* False
--

[question]
--
¿Cuál sería el resultado de este bloque de código (qué se imprimiría en la consola)?

[source,javascript]
----
var n = 5;
if (n * 3 == 15) {
    println(5 + n);
} else {
    print(n);
}
----

[answers]
* 10
* 5
* True
* False
--

[question]
--
¿Qué significa mezclar?

[answers]
* adaptar el volumen de cada pista para que suenen equilibradas
* adaptar el registro de cada pista para suenen equilibradas
* añadir un <em>fade in</em>
* añadir un <em>fade out</em>
--

[question]
--
¿Cuántas condiciones se pueden evaluar en una declaración condicional?

[answers]
* cualquier número de condiciones
* 1 condición
* 2 condiciones
* 3 condiciones
--