[[mixingwithconditionnals]]
== Mix mit Bedingungen!

:nofooter:

Beim Programmieren kann man Dinge automatisieren. Ein Beispiel für Automatisierung ist die Programmierung eines Roboters, der anhält, wenn ein Hindernis erkannt wird. In diesem Szenario braucht der Roboter kein menschliches Wesen, um ihn manuell zu stoppen. Stattdessen wird der Roboter einen Sensor haben, um Hindernisse zu erkennen, und wenn es eins gibt, wird er stoppen. Wir können musikalische Automatisierungen in EarSketch mit Bedingungen (`if` Statements) durchführen. Wir werden sehen, wie man das Mischen der Spuren automatisiert. Mischen bedeutet, dass wir die Lautstärke eines Tracks reduzieren, wenn er zu laut ist, und die Lautstärke erhöhen, wenn er zu leise ist.

[[analyzetrack]]
=== Verwende `analyzeTrack()`

Wir werden sehen, wie man die Lautstärke eines Tracks erkennt. Achte darauf, dass du den Unterschied zwischen der Tonhöhe (hoch oder tief) und der Lautstärke (laut oder leise) eines Geräuschs kennst. Wir verwenden eine EarSketch Funktion namens `analyzeTrack()`. Importiere und führe folgenden Code aus:

[role="curriculum-python"]
[source,python]
----
include::code-examples/mixing-with-conditionals-analyzetrack.py.txt[]
----

[role="curriculum-javascript"]
[source,javascript]
----
include::code-examples/mixing-with-conditionals-analyzetrack.js.txt[]
----

In der Konsole kannst du lesen, dass die ausgegebene Lautstärke 0.10306035109110138 ist.

* Die Lautstärke kann von 0 (Stille) bis 1 (maximale Lautstärke) gehen.
* Manchmal sieht eine Zahl wie folgt aus: 1.74630733714e-05. Dies wird als wissenschaftliche Notation bezeichnet: Siehst du das e-05 am Ende? Das bedeutet, dass die Dezimalstelle um 5 Stellen nach links verschoben wird (ggf. wird sie durch 0 ersetzt). Dies entspricht 0,0000174630733714.
* Die meisten Sounds werden unter 0.4 laut sein

Die `analyzeTrack()` Funktion benötigt 2 Argumente:

. *Track*: Die Tracknummer
. *feature*: Analyse-Konstante, wie `RMS_AMPLITUDE`

.ÜBUNG
****
. Probiere den obigen Code mit verschiedenen Sounds aus (ändere die Variable `Sound`), um zu sehen, wie die Ausgabe ist.
. Füge einen zweiten Track hinzu und verwende die `analyzeTrack()` Funktion, um seine Lautstärke in der Konsole auszugeben. Wenn du den Code ausführst, höre, bevor du auf die Konsole schaust, deine Musik an und versuche zu erraten, welcher Track lauter ist.
****

Der Parameter für `analyzeTrack()` kann entweder `RMS_AMPLITUDE` sein, um die Lautstärke zu bewerten, oder `SPECTRAL_CENTROID`, um die Helligkeit des Klangs zu analysieren. Wir werden uns in diesem Kapitel auf die Analyse der Lautstärke konzentrieren.

[[booleansandcomparisons]]
=== Booleans und Vergleiche

Wir werden nun sehen, wie *boolesche Logik* funktioniert. Dies wird uns helfen, einige Aufgaben zu automatisieren.

[role="curriculum-python"]
*Booleans* sind ein Datentyp. Der boolsche Datentyp hat nur 2 mögliche Werte, `True` und `False`. `True` und `False` beginnen mit einem Großbuchstaben und haben keine Anführungszeichen.

[role="curriculum-javascript"]
*Booleans* sind ein Datentyp. Der boolsche Datentyp hat nur 2 mögliche Werte, `true` und `false`. `true` und `false` beginnen mit einem Kleinbuchstaben und haben keine Anführungszeichen.

[role="curriculum-python"]
--
Um einen booleschen Wert zu erzeugen, kannst du entweder eine Variable initialisieren (`variable1 = True`), oder du kannst einen Vergleich verwenden. Zum Vergleich verwenden wir einen *Vergleichsoperator*. Hier sind die Vergleichsoperatoren:

[cols="^h,1"]
|===
|==
|ist gleich

|!=
|ist nicht gleich

|>
|ist größer als

|>=
|ist größer als oder gleich

|<
|ist kleiner als

|\<=
|ist kleiner als oder gleich
|===

Beachte den Unterschied unter:

1. Vergleiche zwei Werte, um zu sehen, ob sie identisch sind: `==`
1. Zuweisen eines Wertes zu einer Variable: `=`
--

[role="curriculum-javascript"]
--
Um einen booleschen Wert zu erzeugen, kannst du entweder eine Variable initialisieren (`var variable1 = true;`), oder du kannst einen Vergleich verwenden. Zum Vergleich verwenden wir einen *Vergleichsoperator*. Hier sind die Vergleichsoperatoren:

[cols="^h,1"]
|===
|===
|ist gleich

|!==
|ist nicht gleich

|>
|ist größer als

|>=
|ist größer als oder gleich

|<
|ist kleiner als

|\<=
|ist kleiner als oder gleich
|===

Beachte den Unterschied unter:

1. Vergleiche zwei Werte, um zu sehen, ob sie gleich sind: `===`
1. Zuweisen eines Wertes zu einer Variable: `=`
--

[role="curriculum-python curriculum-mp4"]
[[video17apy]]
video::./videoMedia/6_2_1_boolean_py.mp4[]

[role="curriculum-javascript curriculum-mp4"]
[[video17ajs]]
video::./videoMedia/6_2_1_boolean_js.mp4[]

// this video will be cut at 2' to delete the section about boolean operators//

[role="curriculum-python"]
.ÜBUNG
****
* Erstelle ein neues Skript und füge Sounds auf zwei Tracks hinzu.
* Gib `True` aus, wenn der erste Track lauter ist als der zweite Track und andernfalls `False`.
* Verwende einen for-loop mit dem Zähler `track`, um für jeden Track zu prüfen, ob die Lautheit größer als 0,01 ist. Wenn ja, wird `True` ausgegeben, wenn nicht, wird `False` ausgegeben.
* Du kannst zusätzliche Ausgabeanweisungen verwenden, bevor du `True` oder `False` ausgibst, so dass du, wenn du die Konsole liest, weißt, was `True` oder `False` ist. Du kannst zum Beispiel zuerst die Tracknummer und dann ‚True‘ oder ‚False‘ ausgeben.
****

[role="curriculum-javascript"]
.ÜBUNG
****
* Erstelle ein neues Skript und füge Sounds auf zwei Tracks hinzu.
* Gib `true` aus, wenn der erste Track lauter ist als der zweite Track und andernfalls `false`.
* Verwende einen for-loop mit dem Zähler `track`, um für jeden Track zu prüfen, ob die Lautheit größer als 0,01 ist. Wenn ja, wird `true` ausgegeben, wenn nicht, wird `false` ausgegeben.
* Du kannst zusätzliche Ausgabeanweisungen verwenden, bevor du `true` oder `false` ausgibst, so dass du, wenn du die Konsole liest, weißt, was `true` oder `false` ist. Du kannst zum Beispiel zuerst die Tracknummer und dann ‚true‘ oder ‚false‘ ausgeben.
****

Hier ein Beispiel:

[role="curriculum-python"]
[source,python]
----
include::code-examples/mixing-with-conditionals-boolean-example.py.txt[]
----

[role="curriculum-javascript"]
[source,javascript]
----
include::code-examples/mixing-with-conditionals-boolean-example.js.txt[]
----

[role="curriculum-python"]
In diesem Beispiel haben wir `print()` mit Strings verwendet, um den Inhalt der Konsole leichter zu lesen. Wir haben den Operator `+` zum *Verketten* oder Hinzufügen von Strings und die Funktion str() zur Umwandlung von Zahlen in Strings verwendet.

[role="curriculum-javascript"]
In diesem Beispiel haben wir `println()` mit Strings verwendet, um den Inhalt der Konsole zu lesen. Wir haben den Operator `+` benutzt, um *zu verketten* oder Strings hinzuzufügen.

[[conditionalstatements]]
=== Bedingte Anweisungen

Was ist eine bedingte Anweisung? Ein *Statement* ist eine Anweisung für den Computer. Eine *bedingte Anweisung* ist eine Anweisung, die nur ausgeführt werden muss, wenn eine bestimmte *Bedingung* wahr ist. Wenn du zum Beispiel einen Roboter so programmierst, dass er vor einem Hindernis anhält, lautet die Bedingung „Gibt es ein Hindernis?“. Wenn ja, dann stoppen. Wenn nein, nichts tun (weiter gehen).

Unten findest du ein Beispiel für eine bedingte Anweisung, beachte die Ähnlichkeit mit einem for-loop:

[role="curriculum-python"]
[source,python]
----
include::code-examples/mixing-with-conditionals-untitled1.py.txt[]
----

[role="curriculum-javascript"]
[source,javascript]
----
include::code-examples/mixing-with-conditionals-untitled1.js.txt[]
----

.ÜBUNG
****
* Erstelle ein neues Skript mit zwei Tracks.
* Wenn der erste Titel lauter ist als der zweite, dann senke seine Lautstärke. Du brauchst die `analyzeTrack()` und `setEffect()` Funktionen sowie eine `if` Anweisung.
* Du brauchst eine negative Verstärkung (zwischen -1dB und -60dB), um die Lautstärke zu reduzieren.
****

Hier ein Beispiel:

[role="curriculum-python"]
[source,python]
----
include::code-examples/mixing-with-conditionals-automatic-mixing-1.py.txt[]
----

[role="curriculum-javascript"]
[source,javascript]
----
include::code-examples/mixing-with-conditionals-automatic-mixing-1.js.txt[]
----

Möglicherweise möchten wir mehrere Bedingungen prüfen und je nach Bedingung einen anderen Satz von Anweisungen ausführen. Du kannst mehrere Bedingungen miteinander verketten. Wir verwenden folgende Syntax:

[role="curriculum-python"]
[source,python]
----
include::code-examples/mixing-with-conditionals-untitled2.py.txt[]
----

[role="curriculum-javascript"]
[source,javascript]
----
include::code-examples/mixing-with-conditionals-untitled2.js.txt[]
----

[[mixingyourtracks]]
=== Mische deine Tracks

Lass uns all diese Tools nutzen, um deinen Song zu mischen. Das Mixen verändert die Lautstärke der Tracks so dass sie gut ausgeglichen klingen.

[role="curriculum-python"]
.ÜBUNG
****
* Erstelle ein neues Skript.
* Füge Sounds auf mindestens drei Spuren für mindestens sechzehn Takte hinzu.
* Du kannst die `makeBeat()` Funktion und einen `for` Loop verwenden, um Percussion hinzuzufügen.
* Wähle deinen "Haupt"-Track. Es kann deine Melodie sein, oder ein Track den du hervorheben möchtest.
* Wenn dein Haupttrack nicht lauter ist als die anderen Tracks, solltest du seine Lautstärke mit der Funktion `setEffect()` erhöhen. Don't take the percussive track into account, as `analyzeTrack()` is not relevant for percussion. `analyzeTrack()` returns a mean whereas percussion are bursts of sound, so a mean doesn't really evaluate the loudness.
* Use `print()` to show your process in the console. Here is an example: `print("Is track number" + str(track) + "greater than 0.01?")`, if the counter `track` is equal to `1`, this will print "Is track number 1 greater than 0.01?". The function `str()` converts a number (ex: `1`) into a string (ex: `"1"`).
****

[role="curriculum-javascript"]
.ÜBUNG
****
* Erstelle ein neues Skript.
* Füge Sounds auf mindestens drei Spuren für mindestens sechzehn Takte hinzu.
* Du kannst die `makeBeat()` Funktion und einen `for` Loop verwenden, um Percussion hinzuzufügen.
* Wähle deinen "Haupt"-Track. It can be your melody, or the track that you wish to highlight.
* Wenn dein Haupttrack nicht lauter ist als die anderen Tracks, solltest du seine Lautstärke mit der Funktion `setEffect()` erhöhen. Don't take the percussive track into account, as `analyzeTrack()` is not relevant for percussion. `analyzeTrack()` returns a mean whereas percussion are bursts of sound, so a mean doesn't really evaluate the loudness.
* Use `println()` to show your process in the console. Here is an example: `println("Is track number" + track + "greater than 0.01?")`, if the counter `track` is equal to `1`, this will print "Is track number 1 greater than 0.01?".
****

Let's review some vocabulary:

1. *Operator*: a character that represents an action. We have seen arithmetic operators (`\+`, `-`, `\*`, `=`) and comparison operators (`>`, `>=`, `<`, `\<=`, `===`, `!==`).
1. *Expression*: A combination of values, constants, variables, operators, and functions. The computer evaluates expressions to produce a result, usually a single numeric or boolean value.  For example: `1 + 2` (evaluated to 3) or `1 < 2` (evaluated to True) or `analyzeTrack(1, RMS_AMPLITUDE)` (evaluated to the loudness of track `1`, a float between 0 and 1).
1. *Statements*: instructions for the computer to execute.

Below is an example of automated mixing. We can say it's automated because if you change one or more sounds, you won't have to check their loudness and modify the volume accordingly yourself, since it's already included in the code.

[role="curriculum-python"]
[source,python]
----
include::code-examples/mixing-with-conditionals-automatic-mixing-2.py.txt[]
----

[role="curriculum-javascript"]
[source,javascript]
----
include::code-examples/mixing-with-conditionals-automatic-mixing-2.js.txt[]
----

{nbsp} +

[[chapter6summary]]
=== Chapter 6 Summary

[role="curriculum-python"]
* The `analyzeTrack()` function takes two arguments: the track and feature. When the feature is `RMS_AMPLITUDE`, the function will return the loudness of the track (a number between 0 and 1). When the feature is `SPECTRAL_CENTROID`, the function will return the brightness of the track.
* The *boolean* data type has only two possible values, `True` and `False`.
* Boolean values are generated by comparison operators: `==`, `!=`, `>`, `>=`, `<`, `\<=`.
* `==` evaluates if 2 values are equal, whereas `=` assigns a value to a variable.
* An *operator* is a character that represents an action.
* *Expressions* are evaluated by the computer to produce a value.
* Ein *Statement* ist eine Anweisung für den Computer.
* A *condition* is an expression that evaluates to `True` or `False`.
* The `if` statement only executes its code block when its condition is `True`.
* In the event that an `if` statement's condition is `False`, an optional `else` statement allows an alternative code block to be executed.

[role="curriculum-javascript"]
* The `analyzeTrack()` function takes two arguments: the track and feature. When the feature is `RMS_AMPLITUDE`, the function will return the loudness of the track (a number between 0 and 1). When the feature is `SPECTRAL_CENTROID`, the function will return the brightness of the track.
* The *boolean* data type has only two possible values, `true` and `false`.
* Boolean values are generated by comparison operators: `===`, `!==`, `>`, `>=`, `<`, `\<=`.
* `===` evaluates if 2 values are equal, whereas `=` assigns a value to a variable.
* An *operator* is a character that represents an action.
* *Expressions* are evaluated by the computer to produce a value.
* Ein *Statement* ist eine Anweisung für den Computer.
* A *condition* is an expression that evaluates to `true` or `false`.
* The `if` statement only executes its code block when its condition is `true`.
* In the event that an `if` statement's condition is `false`, an optional `else` statement allows an alternative code block to be executed.

[[chapter-questions]]
=== Questions

[question]
--
Which of the following elements is a boolean?

[answers]
* `5+4 === 5`
* `measure = 1`
* `2<3<4`
* `False()`
--

[role="curriculum-python"]
[question]
--
What would the output of this block of code be (what would print to the console)?

[source,python]
----
include::code-examples/mixing-with-conditionals-untitled3.py.txt[]
----

[answers]
* 10
* 5
* True
* False
--

[role="curriculum-javascript"]
[question]
--
What would the output of this block of code be (what would print to the console)?

[source,javascript]
----
include::code-examples/mixing-with-conditionals-untitled3.js.txt[]
----

[answers]
* 10
* 5
* True
* False
--

[question]
--
What is mixing?

[answers]
* adapting the volume of each track so they sound well balanced
* adapting the pitch of each track so they sound well balanced
* adding a fade in
* adding a fade out
--

[question]
--
How many conditions can you check in a conditional statement?

[answers]
* any number of conditions
* 1 condition
* 2 conditions
* 3 conditions
--