[[customizeyourfirstsong]]
== Customize your first song

:nofooter:

In this chapter you will learn how to change the tempo of your song, add comments to your code, and upload your own sounds to enhance the message of your song.

[[settempo]]
=== The `setTempo()` function

[role="curriculum-python"]
--
By now you've noticed that when you create a new script, there are preexisting elements added for your benefit:

. Some comments starting with `#`: we'll cover that in next section
. the `from earsketch import*` line, which adds the EarSketch functions (like `fitMedia()`) to the project
. the `setTempo(120)` function, which we will see in detail below
--

[role="curriculum-javascript"]
--
By now you've noticed that when you create a new script, there are preexisting elements added for your benefit:

. Some comments starting with `//`: we'll cover that in next section
. the `setTempo(120)` function, which we will see in detail below
--

The `setTempo()` function will determine the speed of your song. The *tempo* is a number of beats per minute (bpm) in Western music. In EarSketch, the default tempo (i.e. the initial value of the tempo) is set to 120bpm, which corresponds to a fast walk or march speed. To change the tempo, just change the number between the parentheses of the `setTempo()` function. The higher the tempo, the faster your music. You can select a tempo between _45bpm and 220bpm_.

.PRACTICE
****
. Create a new script.
. Place sounds on two different tracks.
. Modify your tempo and listen to the song.
. Play your song at three different tempos for a friend. Then ask them to rank from slowest to fastest tempo.
****

A genre is a category of artistic composition (e.g. music), characterized by similarities in form, style, or subject matter. Different genres have different tempo ranges. For instance:

[cols="^3*"]
|===
|GENRE |BPM |EXAMPLE

|Pop
|110-130
|"Thriller" - Michael Jackson

"I Wanna Dance With Somebody" - Whitney Houston

|Hip-Hop
|70-100
|"Rapper's Delight" - The Sugar Hill Gang

"Fight the Power" - Public Enemy

|Country
|90-110
|"I Walk the Line" - Johnny Cash

"Jolene" - Dolly Parton

|House / EDM
|110-130
|"One More Time" - Daft Punk

"Good Vibrations" - Marky Mark

|Dubstep / Trap
|140-150
|"Scary Monsters and Nice Sprites" - Skrillex

"Turn Down for What" - Lil Jon
|===

.PRACTICE
****
. Select one artist you really like and find out what genre they belong to.
. Search that genre (on https://soundcloud.com/[Soundcloud] or something similar) and listen to a few snippets of songs in that genre.
. Listen for similarities between the songs.
. You can also research the genre on Wikipedia to get more information about it.
****

Sounds are automatically stretched to fit your song's tempo. This is why sounds previewed in the Sound Browser sometimes appear different from in your song. The effect can be extreme if the tempos are very different.

To find the original tempo of sound, hover over the sound constant Sound Browser.

[[comments]]
=== Adding comments to your code

*Comments* are lines of code ignored by the computer. People use comments to make notes within the code.

EarSketch scripts begin with comments that you can use to enter a description of your song. These details make it easier for other programmers to understand what your code is about.

[role="curriculum-python"]
In Python, comments are indicated by a line starting with a pound `#` symbol.

[role="curriculum-javascript"]
In JavaScript, comments are indicated by a line starting with two forward slashes, `//`.

.PRACTICE
****
In your current script, write a comment with a description of your song on the first line.
****

You can also use comments to describe what different sections of your code do. Here is an example below. You can paste and run the code. Note how the comments describe the different sections:

[role="curriculum-python"]
[source,python]
----
include::code-examples/your-first-song-comments.py.txt[]
----

[role="curriculum-javascript"]
[source,javascript]
----
include::code-examples/your-first-song-comments.js.txt[]
----

{nbsp} +

[[uploadingsounds]]
=== Deine eigenen Sounds hochladen

Du kannst deine eigenen Sounds über den Sound-Browser auf der linken Seite deines Bildschirms hochladen. Klicke unter der Registerkarte „Sounds“ auf die Schaltfläche „Sound hinzufügen“.

Du musst eingeloggt sein, um Töne hochzuladen.

Lass uns die ersten drei Optionen erkunden.

. *Upload Sound* erlaubt dir Audiodateien auf Ihrem Computer auszuwählen.
. *Quick Record* ermöglicht die Aufnahme direkt vom Mikrofon deines Computers.
. *Freesound* erlaubt dir den Import von Sounds von http://freesound.org[freesound.org^], einer Open-Source-Audio-Datenbank. In der Suchleiste kannst du nach einem Soundtyp suchen. Wähle dann die Umschalttaste vor dem Dateinamen, um die Datei auszuwählen.

[role="curriculum-mp4"]
[[video101rec]]
video::./videoMedia/010-01-Recording&UploadingSounds-PY-JS.mp4[]

.PRACTICE
****
Musik und Kunst im Allgemeinen sind oft eine Möglichkeit, eine Botschaft zu vermitteln. Das kann entweder durch den Text und/oder durch die Stimmung des Liedes geschehen. Wir möchten, dass du einen kurzen Song schreibst, der etwas ausdrückt. Das kann ein Gefühl sein, das du gerne teilen möchtest, oder eine Geschichte.

. Überlege dir, was du zum Ausdruck bringen möchtest
. Dann entweder:
.. Schreibe einen Text und nimm dich selbst auf, wie du ihn singst oder liest oder
.. Nimm einige Töne auf oder lade sie herunter, die mit deiner Botschaft in Verbindung stehen
. Füge diese Aufnahmen mit `fitMedia()` zu deinem Song hinzu
. Füge dann zusätzliche Sounds mit `fitMedia()` hinzu
. Zeige deinen Song deinem Freund
. Ihr könnt über eure Lieder und die Dinge, die ihr ausdrücken wolltet, diskutieren
****

Ein aktives Computerprogramm wird *Prozess* genannt.

Wenn du einen Prozess startest, wird der Computercode zunächst im *Arbeitsspeicher* des Computers gespeichert, um einen schnellen Zugriff zu ermöglichen. Die *CPU*, oder Central Processing Unit, greift jede Anweisung aus dem Speicher auf und führt sie aus. Die CPU wird oft als das "Gehirn" des Computers betrachtet.

Der Arbeitsspeicher eines Computers wird manchmal als primärer Speicher oder RAM bezeichnet. Er ist so konzipiert, dass er schnell und temporär ist, nur für aktive Prozesse.

Es gibt einen Unterschied zwischen Arbeitsspeicher (oder Kurzzeitspeicher) und Langzeitspeicher. Langzeitspeicher, wie eine Festplatte oder eine Cloud, werden als Sekundärspeicher bezeichnet. *Sekundärer Speicher* hält hohe Datenmengen für lange Zeiträume, auch nach dem Herunterfahren eines Computers. Die CPU interagiert nicht direkt mit dem Sekundärspeicher. Wenn die CPU einen Prozess ausführt, müssen die Daten aus dem Sekundärspeicher erst in den Arbeitsspeicher übertragen werden, damit die CPU schnell darauf zugreifen kann.

Manchmal stammen die Daten im Arbeitsspeicher, die die CPU verwenden soll, nicht aus dem Sekundärspeicher, sondern von einem Eingabegerät. *Inputs* sind die Signale oder Daten, die vom Computer empfangen werden, wie Audio von einem Mikrofon. Genauso sind *Outputs* die Signale oder Daten, die von ihm gesendet werden, wie Audio über einen Lautsprecher. Input/Output oder I/O ist die Art und Weise, wie der Computer mit der Außenwelt, einschließlich Menschen, kommuniziert!

Betrachten wir die Aufnahme eines Sounds in EarSketch als Beispielprozess. Zuerst nehmen wir mit dem Eingabegerät, dem Mikrofon, Daten auf dem Computer auf. Die CPU speichert diese Audiodaten in ihrem Speicher. Wenn du die Abspieltaste drückst, um deine Aufnahme zu hören, greift die CPU auf die Daten zu und sendet sie an einen Ausgang, also an die Lautsprecher oder Kopfhörer. Wenn du die Upload-Taste drückst, führt die CPU einen Prozess aus, der die Audiodaten in ein Standard-Tondateiformat (eine WAV-Datei, oder .wav) umwandelt und an den EarSketch-Server sendet. Der Server ist ein externes System, das allen EarSketch-Benutzern Dienste zur Verfügung stellt, auch deinem eigenen Computer. Der EarSketch-Server speichert die Tondatei auf dem Sekundärspeicher des Servers, damit du in Zukunft darauf zugreifen kannst.

Sieh dir das folgende Zusatzvideo an:

[role="curriculum-mp4"]
[[video11cpu]]
video::./videoMedia/010-02-ProcessesandMemory-PY-JS.mp4[]

////
END OF OPTIONAL
////

[[copyright]]
=== Benutze Copyright weise

*Copyright* ist der Teil des Gesetzes, der *geistiges Eigentum*, oder das Eigentum an kreativen Werken wie Musik abdeckt. Wenn du Samples (kleine Musikstücke) verwendest oder bereits vorhandene Musik remixt, musst du die Urheber nennen und kannst dies in den Kommentaren deines Codes tun. Bevor du Sounds von anderen Musikern verwendest und deine eigene Musik weitergibst, solltest du mehr über das Urheberrecht erfahren!

Wenn du etwas Originelles und Wesentliches geschaffen hast, erhältst du automatisch ein Urheberrecht! In den USA bedeutet das, dass du Kopien anfertigen, Änderungen vornehmen und deine Werke weitergeben darfst.

Bei einem Lied gibt es zwei Urheberrechte: die Rechte am Lied (vom Autor oder Komponisten) und die Rechte an der Tonaufnahme (oft von der Plattenfirma). Einnahmen aus öffentlichen Auftritten gehen an den Songwriter und die meisten Einnahmen aus Plattenverkäufen gehen an die Plattenfirma.

*Urheberrechtsverletzung* ist eine Verletzung des Urheberrechts, wie zum Beispiel das illegale Herunterladen von Musik. In den Vereinigten Staaten erlaubt *fair use* die Verwendung von urheberrechtlich geschützten Inhalten unter bestimmten Bedingungen wie erzieherische oder kritische Zwecke, wobei nur geringe Mengen der Arbeit wiederverwendet werden. Streitigkeiten über eine gerechte Nutzung werden von einem Richter von Fall zu Fall entschieden.

Neben der fairen Nutzung gibt es auch andere Möglichkeiten, Musik offen zu nutzen und zu teilen. EarSketch funktioniert, weil Künstlerinnen und Künstler ihre Arbeit in Form von *Samples* (also kleinen Teilen von Soundaufnahmen) in der Sound-Bibliothek mit dir geteilt haben.

Bei dem Urheberrecht geht es nicht nur darum, Menschen in Schwierigkeiten zu bringen. Wenn du einen Song ins Internet hochlädst, macht es dir vielleicht nichts aus, wenn jemand ihn ohne Fragen herunterlädt; du möchtest, dass Leute deine Musik teilen! Das Urheberrecht sollte uns helfen, mehr Kunst zu machen und zu teilen, nicht weniger. Wenn du Songs in EarSketch erstellst, möchten wir, dass du weniger an _Diebstahl_ und mehr an _Austausch_ denkst. EarSketch funktioniert, weil Künstler ihre Arbeit mit dir geteilt haben, was zu einer Bibliothek von Samples geführt hat, die du zum Erstellen neuer Musik verwendest. Wenn du deine Musik weitergibst oder anderen Mitschülern erlaubst, deinen Code zu remixen, trägst du damit dazu bei, dass neue Kunst in die Welt kommt.

Wenn du Töne in deinen EarSketch-Skripten verwendest, musst du sicher sein, dass du die Erlaubnis des Urheberrechtsinhabers hast, die Töne zu verwenden, oder dass du sie im Einklang mit der Fair Use-Regelung verwendest.

Für alle Details siehe https://earsketch.gatech.edu/landing/#/license[LICENSE^].

[[chapter2summary]]
=== Zusammenfassung von Kapitel 2

[role="curriculum-python"]
* Das *Tempo* ist die Geschwindigkeit, mit der ein Musikstück gespielt wird, angegeben in Schlägen pro Minute (bpm). Das Tempo ist an ein Genre gebunden.
* Die Clips in der Sound-Bibliothek von EarSketch sind in Ordnern mit verwandten Sounds organisiert. Um das genaue Tempo eines Clips zu sehen, bewege den Mauszeiger über den Namen im Sound-Browser.
* Kommentare sind Codezeilen, die vom Computer nicht ausgeführt werden. Sie sind aber nützlich, um Notizen innerhalb eines Skripts zu machen.
* `von earsketch import *` fügt die EarSketch-API zu deinem Projekt hinzu.
* `setTempo()` lässt dich das Tempo deines Songs angeben. Dies muss in jedem EarSketch-Skript enthalten sein.
* Du kannst deine eigenen Sounds über den Sound-Browser in EarSketch hochladen. Klicke einfach auf „Sound hinzufügen“.
* Ein *Prozess* ist ein Programm, das auf einem Computer läuft. Die Verarbeitung erfolgt durch die *CPU* eines Computers, die für die Ausführung von Programmanweisungen zuständig ist.
* *Arbeitsspeicher* (a.k.a RAM oder Primärspeicher) enthält temporäre Daten und Verarbeitungsanweisungen, die die CPU verwenden kann.
* *Sekundärspeicher* bezieht sich auf die langfristige Speicherung von Daten, oft in hohen Volumen. Daten aus dem Sekundärspeicher müssen in den Arbeitsspeicher übertragen werden, bevor die CPU auf sie zugreifen kann.
* *Copyright* ist ein Teil des Gesetzes, der das Eigentum an kreativen Werken wie Musik abdeckt. Es ist wichtig für Musiker, weil es definiert, wie die Arbeit einer anderen Person verwendet und geteilt werden kann.
* Wenn du ein musikalisches Werk erstellst, das greifbar und neu ist, hast du automatisch ein Urheberrecht. Mit anderen Worten: Du hast Rechte an dem Werk, das du geschaffen hast.
* Die *Lizenzierung* eines Musikstücks gibt anderen die Erlaubnis, es zu verwenden.

[role="curriculum-javascript"]
* Das *Tempo* ist die Geschwindigkeit, mit der ein Musikstück gespielt wird, angegeben in Schlägen pro Minute (bpm). Das Tempo ist an ein Genre gebunden.
* Die Clips in der Sound-Bibliothek von EarSketch sind in Ordnern mit verwandten Sounds organisiert. Um das genaue Tempo eines Clips zu sehen, bewege den Mauszeiger über den Namen im Sound-Browser.
* Kommentare sind Codezeilen, die vom Computer nicht ausgeführt werden. Sie sind aber nützlich, um Notizen innerhalb eines Skripts zu machen.
* `setTempo();` lässt dich das Tempo deines Liedes angeben. Dies muss in jedem EarSketch-Skript enthalten sein.
* Du kannst deine eigenen Sounds über den Sound-Browser in EarSketch hochladen. Klicke einfach auf „Sound hinzufügen“.
* Ein *Prozess* ist ein Programm, das auf einem Computer läuft. Die Verarbeitung erfolgt durch die *CPU* eines Computers, die für die Ausführung von Programmanweisungen zuständig ist.
* *Arbeitsspeicher* (a.k.a RAM oder Primärspeicher) enthält temporäre Daten und Verarbeitungsanweisungen, die die CPU verwenden kann.
* *Sekundärspeicher* bezieht sich auf die langfristige Speicherung von Daten, oft in hohen Volumen. Daten aus dem Sekundärspeicher müssen in den Arbeitsspeicher übertragen werden, bevor die CPU auf sie zugreifen kann.
* *Copyright* ist ein Teil des Gesetzes, der das Eigentum an kreativen Werken wie Musik abdeckt. Es ist wichtig für Musiker, weil es definiert, wie die Arbeit einer anderen Person verwendet und geteilt werden kann.
* Wenn du ein musikalisches Werk erstellst, das greifbar und neu ist, hast du automatisch ein Urheberrecht. Mit anderen Worten: Du hast Rechte an dem Werk, das du geschaffen hast.
* Die *Lizenzierung* eines Musikstücks gibt anderen die Erlaubnis, es zu verwenden.

[[chapter-questions]]
=== Fragen

[question]
--
Was kannst du mit `setTempo()` in EarSketch tun?

[answers]
* Das Tempo eines Songs festlegen
* Einen Sound zu einem Track hinzufügen
* Einen Drum-Beat erstellen
* Die Soundeigenschaften in einem Projekt ändern
--

[question]
--
Was ist die Maßeinheit für das Tempo?

[answers]
* Beats per Minute (BPM)
* Takte
* Dezibel (dB)
* Sekunden
--

[question]
--
Wofür kannst du Kommentare verwenden?

[answers]
* Alles oben Genannte
* Deinen Code organisieren
* Eine Beschreibung deines Skripts am Anfang deines Skripts schreiben
* Den Code für andere Programmierer leicht lesbar machen
--

[question]
--
Welche der folgenden Aussagen ist richtig?

[answers]
* Eine Festplatte ist ein Beispiel für einen Sekundärspeicher
* Audiodaten werden in der CPU eines Computers gespeichert
* Die CPU speichert Anweisungsdaten für Programme
* Der Sekundärspeicher speichert Daten für kurze Zeiträume
--

[question]
--
Wie erhältst du ein Urheberrecht?

[answers]
* Indem man ein neues Werk schafft und veröffentlicht
* Indem du ein Patent erwirbst
* Indem du einer Geheimorganisation beitrittst
* Indem du eine Lizenz für dein Werk auswählst
--

[question]
--
Was ist eine Musiklizenz?

[answers]
* Eine Lizenz gibt anderen die Erlaubnis, ein musikalisches Werk zu verwenden
* Ein Kompositionsprozess
* Ein Musikgenre
* Eine Beschreibung deines Songs
--